ckeditor/ckeditor4

core/dom/text.js

Fixes https://dev.ckeditor.com/ticket/13268
Thanks for the great product!

fix documentation issue with creating a text node

---

README.md

...since the GitHub Issues tab is disabled

Link to where issues should be reported

---

plugins/menu/plugin.js

it expects an Object, not an array

improve documentation for menu plugin addMenuItems method - 

---

plugins/templates/plugin.js

Typo in Template plugin docs

---

styles.js
tests/core/style/manual/embedstyles.html
tests/core/style/manual/embedstyles.md

See https://github.com/ckeditor/ckeditor-sdk/issues/194#issuecomment-260570374 for more details.

Additional style set for embed plugin. 

---

core/resourcemanager.js

Comments don't match code examples.

Fixed wrong paths in docs to addExternal

---

CHANGES.md
bender.ci.js
plugins/mathjax/dev/mathjax.html
plugins/mathjax/plugin.js

See [#16958](https://dev.ckeditor.com/ticket/16958) for more details.

T/16958 Change MathJax CDN to cdnjs.

---

CHANGES.md
plugins/embed/plugin.js
tests/plugins/embed/manual/embedprovider.html
tests/plugins/embed/manual/embedprovider.md
tests/plugins/embed/provider.js

_Merge message proposal:_
Embed plugin provider url is now empty by default.

T/13793 Embed plugin: use empty embed_provider by default.

---

tests/plugins/autoembed/manual/autoembed.html
tests/plugins/autoembed/manual/notifications.html
tests/plugins/autoembed/manual/spontaneousreembed.html
tests/plugins/autoembed/manual/undoautoembed.html
tests/plugins/embed/manual/embed.html
tests/plugins/embed/manual/iframefocus.html
tests/plugins/embedsemantic/manual/embedsemantic.html
tests/tickets/13158/1.html

See [#17017](https://dev.ckeditor.com/ticket/17017).

Fixed missing 'embed_provider' in manual tests.

---

plugins/tableresize/plugin.js
tests/plugins/tableresize/manual/empty.html
tests/plugins/tableresize/manual/empty.md
tests/plugins/tableresize/tableresize.html
tests/plugins/tableresize/tableresize.js

https://dev.ckeditor.com/ticket/14762

Preventing of null reference when table is empty.

---

.travis.yml

Using new apt plugin for Travis should do the trick.

Force Travis to use new version of Chrome

---

tests/plugins/autolink/manual/autolink.html

Put URLs in the inptus so it can be easier copied.

Improve autolink/manual/autolink test usability

---

tests/plugins/clipboard/manual/pastecommands.md

Improvements for manual tests description.

[2399] improvements for manual test description

---

tests/plugins/tableselection/manual/integrations/clipboard/xss.html

FIxed incorrect ignore in test

---

tests/plugins/clipboard/manual/pastenotification.md

Added some explanation about behavior in browsers.

Fixed incorrect test description

---

tests/plugins/tabletools/manual/transformations/mixedBackground.html

Removed unnecessary ignore in test.

Test for cell background transformation shouldn't be ignored in IEs

---

tests/plugins/tableselection/manual/integrations/clipboard/nestedtable.md
tests/plugins/tableselection/manual/integrations/clipboard/nestedtablemultiple.md

Fixed incorrect test tags in two tests for tableselection (missing comma…).

Incorrect test tags

---

core/selection.js

Fixed typos in selection.js docs

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Otherwise it was rendering a nasty todolist in the issue list.

Issue type is no longer marked as a checkbox

---

tests/_benderjs/ckeditor/static/tools.js
tests/core/htmldataprocessor.js

Other: unit test fix.
See #431 for details (https://github.com/ckeditor/ckeditor-dev/issues/431#issuecomment-305422790).
Closes #431.

Ignore one XSS test on Chrome Linux

---

CHANGES.md
core/filter.js
tests/core/filter/manual/margintransformation.html
tests/core/filter/manual/margintransformation.md
tests/core/filter/transformations.js
tests/plugins/pastefromword/generated/_fixtures/Only_paragraphs/expected.html
tests/plugins/pastefromword/generated/_fixtures/Only_paragraphs/word2013/expected_safari.html
tests/plugins/pastefromword/generated/_fixtures/Tickets/11215sample_error_word/expected.html

With this test couple of PFW tests had to be adjusted, as due to the bug paragraph did not get margin in these scenarios.
It might be a good idea to strip 0px margin, but that's a separate issue, and out of the scope of current issue.
Closes #450.

Fixed splitMarginShorthand transformation

---

plugins/fakeobjects/plugin.js

task
No. Doesn't have to. Only documentation change.
Add JSDuck to 3 fake object methods.
close #495

Update fake element docs

---

CHANGES.md
plugins/link/dialogs/anchor.js
tests/plugins/link/anchor.js
tests/plugins/link/manual/anchorediting.html
tests/plugins/link/manual/anchorediting.md

Bug fix
yes
Correct condition to check anchor elements to use fake element properties.
close #476

Fix edition of empty anchor

---

.github/ISSUE_TEMPLATE.md

Other: GitHub template update.
No need for tests.
Added an information that security reports should go though contact form.

Security report instructions in GitHub template

---

CHANGES.md

Changelog entry
Added changelog entry for #582.

Updated changelog.

---

core/selection.js

Extend documentation of `getNative` method.
Documentation is building properly.
Closes #519

#519 update selection API documentation(getNative method)

---

tests/plugins/notification/notoolbarlayout.js

bug fix
no it fix test
IE8 setTimeout failed when regular function was returned, now code is surround with anonymous function and it works on IE8.
close #660

Fix for unit test for IE8

---

.github/ISSUE_TEMPLATE.md

Typo fix
N/A
A minor clarification in the issue template.

Issue template reworded

---

tests/plugins/copyformatting/getSelectedWordOffset.js

bug fix
no it corrects 2 tests.
Remove hacks from test for IE8.
close #725

Fix failing tests under IE8

---

plugins/tableselection/plugin.js
tests/plugins/tableselection/integrations/clipboard/pasteflow.js
tests/plugins/tableselection/integrations/clipboard/pastemerge.js
tests/plugins/tableselection/integrations/clipboard/pastenested.js
tests/plugins/tableselection/integrations/clipboard/xss.js

Bug fix
No, just changes to existing, failing tests.
Force reselecting all previously selected cells after emptying them to allow to create correct undo snapshot.

Integration between undo and tableselection

---

tests/plugins/tableselection/manual/integrations/image2/paste.md
tests/plugins/widgetselection/addfillers.js
tests/plugins/widgetselection/filler.js
tests/plugins/widgetselection/integration.js
tests/plugins/widgetselection/iswholecontentselected.js
tests/plugins/widgetselection/paste.js
tests/plugins/widgetselection/removeFillers.js

Other
I've removed last tests with `tc` tag, both manual and unit ones. I've also corrected references to trac issues in widgetselection tests.

Correct tags in tests

---

tests/plugins/tableselection/manual/tableselection.html
tests/plugins/tableselection/manual/tableselection.md

Task
Nope, this PR just modifies existing manual test
I've removed tags from `tests/plugins/tableselection/manual/tableselection` and added some cases with `caption` and combined `[colspan]` with `[rowspan]`.
closes #786.

Generic manual test for tableselection

---

dev/pastefromword/getclipboard.html

Task
Does not incldue unit/manual tests as this is just a helper that is not covered.
See the #827 for details.
Closes 827.

Make sure PFW fixture generator return entire raw html data

---

CHANGES.md

Typo fix
No need for tests, just a markdown fix.
[Our user pointed out](https://ckeditor.com/blog/CKEditor-4.7-released#comment-3492115829) that we said that we have used incorrect changelog description for the CSP fix in 4.7.0.

Fixed changelog entry for CSP enhancement added in 4.7.0 version

---

plugins/tableselection/plugin.js

Comment typo fix
- Add `*` to comment, so docs will properly parse it and generate documentation.
close #852

Fix docs comment for tableselection.isSupportedEnvironment

---

CHANGES.md

Changelog entry
It's just changelog entry.
Add changelog entry about WSC plugin update in 4.7.3.
Closes #876.

Add changelog entry about WSC update

---

CHANGES.md

Changelog entry for https://github.com/ckeditor/ckeditor-dev/commit/37f6a4bbc2ebb171bc6876134ded61cb80cfa2f3 merge.

Changelog entry for #704. [skip ci]

---

dev/langtool/meta/ckeditor.plugin-easyimage/meta.txt
plugins/easyimage/dialogs/easyimagealt.js
plugins/easyimage/dialogs/eiAltText.js
plugins/easyimage/lang/en.js
plugins/easyimage/plugin.js
plugins/easyimage/samples/easyimage.html
plugins/easyimage/styles/easyimage.css
tests/plugins/easyimage/commands.js
tests/plugins/easyimage/manual/easyimage.html
tests/plugins/easyimage/manual/easyimage.md

New feature
Initial implementation of "Full Image", "Side image" and "Change alternative text" commands for Easy Image.

Initial implementation of commands in Easy Image

---

CHANGES.md

Changelog update
- Changelog update after merginin #994

Update changelog after merging 994

---

core/selection.js

Typo fix
_No tests needed for typo fix._
The specs incorrectly pointed to `unlockSelection` method instead of `lockSelection` method.

The `unlockSelection` method docs fix

---

ckeditor.js

Changed one URL

---

CHANGES.md
plugins/colorbutton/plugin.js
tests/plugins/colorbutton/highlightedcolor.html
tests/plugins/colorbutton/highlightedcolor.js
tests/plugins/colorbutton/manual/highlightedcolor.html
tests/plugins/colorbutton/manual/highlightedcolor.md

Bug fix
Yes
Colors which wasn't highlighted was written in shorthand hex notation. What I did, I changed it from 3-characters format to 6-characters.
---
Closes #1008

T/1008 Highlight colors in color panel

---

tests/plugins/inlinetoolbar/manual/focus.html
tests/plugins/inlinetoolbar/manual/focus.md
tests/plugins/inlinetoolbar/view.js

Bug fix 
Unit and manual test for focus in inline toolbar.

Test for focus in inline toolbar

---

CHANGES.md
plugins/widget/plugin.js
tests/plugins/widget/widgetapi.js

Bug fix
I've extracted 6232b54a198f1c002ecacfdaad033236db00488f into this PR and add some unit tests.
Closes #1097

#1097 Fix scope of widget's upcast methods

---

plugins/easyimage/plugin.js
tests/plugins/easyimage/config.html
tests/plugins/easyimage/config.js
tests/plugins/easyimage/manual/figuresnoclass.html
tests/plugins/easyimage/manual/figuresnoclass.md
tests/plugins/easyimage/widget.html
tests/plugins/easyimage/widget.js

Other
A set of corrections to #978 PR.
Changes are limited to `easyimage` plugin, so there are few things to be addressed in the `imagebase`.

Easy Image widget post review fixes

---

plugins/inlinetoolbar/plugin.js

Bug fix
Var name changed in the example.

Change var name in using example of inline toolbar

---

plugins/easyimage/plugin.js
tests/plugins/easyimage/manual/upload.html
tests/plugins/easyimage/manual/upload.md
tests/plugins/easyimage/uploadwidget.js
tests/plugins/easyimage/widget.html
tests/plugins/easyimage/widget.js

Other
This PR has all the corrections requested to #1052.

Corrections to Easy Image upload feature

---

plugins/inlinetoolbar/plugin.js

Other
Proper unit/manual tests are already in place.
Simplified `inlineToolbarView.renderItems` method implementation, created in #1114.

Review corrections for inline toolbar grouping

---

plugins/inlinetoolbar/plugin.js
plugins/inlinetoolbar/samples/js/sample.js
tests/plugins/inlinetoolbar/manual/focus.html
tests/plugins/inlinetoolbar/manual/inlinetoolbar.html
tests/plugins/inlinetoolbar/manual/kama.html
tests/plugins/inlinetoolbar/manual/moono-lisa.html
tests/plugins/inlinetoolbar/manual/moono.html
tests/plugins/inlinetoolbar/positioning.js
tests/plugins/inlinetoolbar/view.js

New feature 
- Removed `create` method from both classes.
- Added `show` and `hide` methods.
- Added `attach` method in both classes.
- Updated tests and documentation.

API change in inlineToolbarView and inlineToolbar

---

plugins/easyimage/plugin.js
tests/plugins/easyimage/commands.js
tests/plugins/easyimage/manual/dndimagetype.html
tests/plugins/easyimage/manual/dndimagetype.md
tests/plugins/easyimage/manual/pasteimagetype.html
tests/plugins/easyimage/manual/pasteimagetype.md
tests/plugins/easyimage/widget.html
tests/plugins/easyimage/widget.js

Bug fix for new feature
I've modified commands. Now they just set appropriate data (`type`) and whole logic with adding and removing classes was moved to widget's `data` callback.

Fix for missing styles after paste/d&d

---

plugins/inlinetoolbar/plugin.js
tests/plugins/inlinetoolbar/loading.js

Bug fix 
We are just checking if beforeInit function was already executed.

Prototype overwriting workaround in inlinetoolbarView

---

plugins/imagebase/plugin.js
tests/plugins/imagebase/features/api.js
tests/plugins/imagebase/features/link.html
tests/plugins/imagebase/features/link.js
tests/plugins/imagebase/features/manual/link.html
tests/plugins/imagebase/imagebase.html

Other
Set of review corrections to #1137.
Most of changes are just:
* Fix for features not to override already registered feature information.
* Renamed `widgetFeatures` to `features`.
* Additional test cases.
* Test simplifications.

Review corrections to Easy Image linking

---

plugins/clipboard/plugin.js

Bug fix
Tests are already covering this part of code.
See https://github.com/ckeditor/ckeditor-dev/issues/1156#issuecomment-344178308 for more details.
Closes #1156.

Cannot drag and drop widget (with t/468)

---

tests/core/ckeditor/basepathglobal.js

Test `/tests/core/ckeditor/basepathglobal` improvement.
---
Closes #1061.

T/1089 Rename hostname in test

---

tests/plugins/inlinetoolbar/manual/kama.html
tests/plugins/inlinetoolbar/manual/moono-lisa.html
tests/plugins/inlinetoolbar/manual/moono.html

Bug fix 
Now `divarea` editor is created in manual tests.

Fix manual divarea tests for inlinetoolbar.

---

plugins/inlinetoolbar/skins/moono-lisa/inlinetoolbar.css

Bug fix
Small CSS fix to remove this effect:

Inactive button hover fix in inline toolbar

---

plugins/inlinetoolbar/skins/kama/inlinetoolbar.css
plugins/inlinetoolbar/skins/moono-lisa/inlinetoolbar.css
plugins/inlinetoolbar/skins/moono/inlinetoolbar.css

Bug fix
now all padding in all skins looks equal

Make all paddings in inline toolbar to looks equal

---

plugins/inlinetoolbar/plugin.js

Docs and initialization fix in inlinetoolbar

---

plugins/balloonpanel/plugin.js
tests/plugins/balloonpanel/cssloading.js

Bug fix
CSS loading fix in balloon panel.
closes #1221

CSS loading fix in balloonpanel

---

CHANGES.md

Task: changelog corrections
Splitted changelog entry into two separate entries so it is more clear what was fixed.

Changelog corrections

---

plugins/balloontoolbar/plugin.js

Other, post review corrections
Just a couple of changes from my review summary in #1242.

Review changes to editor.ballonToolbars#create docs

---

tests/plugins/balloontoolbar/view.js

Bug fix 
change one unit test.

Ballonpanel toolbar unit test fix for IE/Edge

---

plugins/clipboard/plugin.js
tests/plugins/clipboard/datatransfer.js
tests/plugins/clipboard/fallbackdatatransfer.js
tests/plugins/clipboard/manual/customtypes.md
tests/plugins/clipboard/manual/customtypesasync.html
tests/plugins/clipboard/manual/customtypesasync.md

Getting native data from clipboard return empty string with asynchronous requests

---

tests/plugins/pastefromword/generated/nested_list.js

This PR fixes failing test, so no need for additional tests.
I've adjusted editor's config for built version of editor.
Closes #1252.

Fix failing PFW nested_list test

---

plugins/balloontoolbar/plugin.js
plugins/balloontoolbar/skins/default.css
plugins/balloontoolbar/skins/kama/balloontoolbar.css
plugins/balloontoolbar/skins/moono-lisa/balloontoolbar.css
plugins/balloontoolbar/skins/moono/balloontoolbar.css

Task
Decreased size of balloon toolbar triangle to 7x7 px (instead of 10x10 px).

Decreased balloon toolbar triangle size

---

plugins/balloontoolbar/plugin.js
tests/plugins/balloontoolbar/manual/windowresize.md
tests/plugins/balloontoolbar/view.js

Other, PR corrections
This is a followup PR to #1253.
It corrected a TC mentioned in review notes: https://github.com/ckeditor/ckeditor-dev/pull/1253#pullrequestreview-79570790

Corrections to Balloon Toolbar window resize reposition fix

---

CHANGES.md
core/selection.js
plugins/clipboard/plugin.js
plugins/tableselection/plugin.js
plugins/uploadimage/plugin.js
plugins/widget/plugin.js
tests/plugins/clipboard/datatransfer.js
tests/plugins/clipboard/manual/customtypes.html
tests/plugins/clipboard/paste.js
tests/plugins/indent/indent.js
tests/plugins/pastefromword/parsestyles.js
tests/plugins/tableselection/integrations/image2/manual/deselectwidget.md
tests/plugins/uploadwidget/manual/skipnotification.md
tests/plugins/widget/integration/table/manual/widgetintable.md
tests/plugins/widget/integration/table/manual/widgetintablewithtableselection.md
tests/plugins/widget/manual/scrolloncut.md

Various corrections in source files before 4.8 release

---

tests/core/editable/misc.js

Other, failing test fix
This PR addresses https://github.com/ckeditor/ckeditor-dev/issues/895#issuecomment-348155804.

Ignore tests/core/editable/misc test for Chrome

---

CHANGES.md
core/tools.js
plugins/pastefromword/filter/default.js
plugins/pastefromword/plugin.js

Language corrections - batch 2.

Review major target

---

plugins/widget/plugin.js
tests/plugins/widget/customstylehandlerloading.js

Bug fix (kind of)
See https://github.com/ckeditor/ckeditor-dev/issues/1278#issuecomment-348136691 for in depth explanaiton.
Closes #1278, closes #1287.

 Add custom style handler only when loading widget plugin

---

CHANGES.md

Missing changelog entry for #1287.

Missing changelog entry for #1287 ticket

---

tests/plugins/tableselection/integrations/selectall/selectall.js

Task: Failing test fix
Closes #1277.

Remove widget plugin from tableselection/integration/selectall test

---

CHANGES.md

Other, changelog entry
_no need_
Just added a changelog for the Balloon Toolbar feature.

Added missing changelog entry

---

plugins/clipboard/plugin.js
tests/plugins/clipboard/datatransfer.js

Exception after clicking on the widget's drag icon with unfocused editor

---

tests/core/htmldataprocessor.js

Other, test fix.
- fix test case in opera
close #1291

Fix failing unit test on Opera.

---

tests/plugins/clipboard/fallbackdatatransfer.js

Task: Failing tests fix
Closes #1296.

Tests: fix for failing dataTransfer tests

---

tests/plugins/colordialog/manual/addhash.md

Task
I've removed now unnecessary `tc` tag, which is redundant.

Remove tc tag

---

package.json
plugins/cloudservices/plugin.js
tests/plugins/cloudservices/cloudservices.js
tests/plugins/cloudservices/manual/errors.html
tests/plugins/cloudservices/manual/errors.md
tests/plugins/cloudservices/unit.js

New feature
error logs for missing token or url in cloudservices.

Error logs for URL and TOKEN in cloudservice plugin

---

CHANGES.md
plugins/filebrowser/plugin.js
plugins/filetools/plugin.js
tests/plugins/filebrowser/manual/uploadxhr.html
tests/plugins/filebrowser/manual/uploadxhr.md
tests/plugins/filebrowser/manual/uploadxhrwitherror.html
tests/plugins/filebrowser/manual/uploadxhrwitherror.md
tests/plugins/filebrowser/uploadbutton.js
tests/plugins/filetools/_helpers/tools.js
tests/plugins/filetools/fileloader.js
tests/plugins/filetools/static.js

New feature
Corrections to #1352 PR.
There are multiple minor changes, like:
* renaming config options,
* adding missing API doc tags,
* adding some unit tests,
* multiple simplifications.

Corrections to XHR support for File Browser plugin uploads

---

tests/plugins/balloonpanel/manual/balloonpanel.html
tests/plugins/balloonpanel/manual/focus.html
tests/plugins/balloonpanel/manual/positioning.html
tests/plugins/balloontoolbar/context/manual/complex.html
tests/plugins/balloontoolbar/context/manual/context.html
tests/plugins/balloontoolbar/context/manual/toolbar.html
tests/plugins/balloontoolbar/context/manual/widget.html
tests/plugins/balloontoolbar/manual/balloontoolbar.html
tests/plugins/balloontoolbar/manual/drag.html
tests/plugins/balloontoolbar/manual/fallbackstyles.html
tests/plugins/balloontoolbar/manual/focus.html
tests/plugins/balloontoolbar/manual/kama.html
tests/plugins/balloontoolbar/manual/moono-lisa.html
tests/plugins/balloontoolbar/manual/moono.html
tests/plugins/balloontoolbar/manual/refreshposition.html
tests/plugins/balloontoolbar/manual/skinpath.html
tests/plugins/balloontoolbar/manual/windowresize.html

Tests refactoring
Both skipped as it simply corrects manual tests. All the manual tests are passing/working correctly.
See #1384 for more description.
Closes #1384.

Removed workarounds for Balloon Panel issue related to horizontal margin

---

plugins/easyimage/plugin.js
tests/plugins/easyimage/commands.js
tests/plugins/easyimage/manual/balloontoolbar.html
tests/plugins/easyimage/manual/balloontoolbar.md
tests/plugins/easyimage/manual/upload.md

New feature for new feature
I've added basic integration with balloon toolbar for Easy Image.

Add integration with balloon toolbar

---

plugins/filetools/plugin.js

Typo fix
No need, this is just a typo fix.
As in title.

Corrected typos in XHR name (filetools plugin)

---

plugins/balloonpanel/plugin.js

Other, doc fix
This issue could cause some frustration 😉

Corrected the order of BalloonPanel#move parameters

---

tests/plugins/easyimage/manual/dndimagetype.md
tests/plugins/easyimage/manual/easyimage.md
tests/plugins/easyimage/manual/figuresnoclass.md
tests/plugins/easyimage/manual/pasteimagetype.md
tests/plugins/easyimage/manual/progressbar.md
tests/plugins/easyimage/manual/styles.md
tests/plugins/easyimage/manual/upload.md

Task
Updated bender-tags version from 4.8.0 to 4.9.0

Version update of the Easy Image plugin bender tests

---

plugins/imagebase/plugin.js

Refactoring
Existing tests cover all changes.
I've introduced method `getLinkFeature` that includes all code related to `link`.

Refactoring: link feature definition moved to seperate method.

---

plugins/easyimage/styles/easyimage.css
tests/plugins/easyimage/manual/imageoutline.html
tests/plugins/easyimage/manual/imageoutline.md

Bug fix.
Replaced default link outline with border to align an image to the rest of the widget.
Closes #3302

Fixed misaligned link border with caption background

---

plugins/easyimage/styles/easyimage.css
tests/plugins/easyimage/manual/captionflickering.html
tests/plugins/easyimage/manual/captionflickering.md

Bug fix
Adjusted CSS so the caption does not flicker on focus.

Prevent caption flickering on focus

---

dev/langtool/meta/ckeditor.plugin-easyimage/meta.txt
plugins/balloontoolbar/plugin.js
plugins/balloontoolbar/skins/default.css
plugins/balloontoolbar/skins/kama/balloontoolbar.css
plugins/balloontoolbar/skins/moono-lisa/balloontoolbar.css
plugins/balloontoolbar/skins/moono/balloontoolbar.css
plugins/cloudservices/plugin.js
plugins/easyimage/dialogs/easyimagealt.js
plugins/easyimage/lang/en.js
plugins/easyimage/plugin.js
plugins/easyimage/samples/easyimage.html
plugins/easyimage/styles/easyimage.css
plugins/imagebase/lang/en.js
plugins/imagebase/plugin.js

task, update license headers.
Doesn't need to.
- just header update

Update license header for files related to easyimage.

---

core/editor.js
plugins/balloonpanel/plugin.js
plugins/balloontoolbar/plugin.js
plugins/filebrowser/plugin.js
plugins/filetools/plugin.js
tests/core/config/manual/startupfocusend.md
tests/core/filter/manual/bordershorthandtransformation.md
tests/plugins/balloonpanel/manual/positioning.md
tests/plugins/balloontoolbar/context/manual/focusablebuttons.md
tests/plugins/balloontoolbar/context/manual/imgselect.md
tests/plugins/balloontoolbar/manual/contextapi.md
tests/plugins/balloontoolbar/manual/refreshposition.md
tests/plugins/clipboard/manual/forcepasteasplaintext.md
tests/plugins/filebrowser/manual/uploadxhr.md
tests/plugins/filebrowser/manual/uploadxhrwitherror.md
tests/plugins/image/manual/wrongvaluedialog.md
tests/plugins/image2/manual/wrongvaluedialog.md
tests/plugins/widgetselection/manual/specialcharacters.md

Task
Updated target version from 4.8.1 to 4.9.0 in test files and docs.
Closes #1509

Version change from 4.8.1 to 4.9.0

---

dev/langtool/_common.sh
dev/langtool/meta/ckeditor.plugin-easyimage/meta.txt
dev/langtool/meta/ckeditor.plugin-imagebase/meta.txt

bugfix
Tests are not required.
- update 'easyimage` meta tags for langtools
- generate `imagebase` meta.txt file
- update config to not miss those plugins in langtool

Update langtool with 2 new plugins

---

dev/langtool/meta/ckeditor.plugin-easyimage/meta.txt
dev/langtool/meta/ckeditor.plugin-imagebase/meta.txt

Description fix
- fix description for langtool
found here: https://github.com/ckeditor/ckeditor-dev/pull/1519/files#r164999825

Fix caption placeholder description

---

ckeditor.js
config.js
contents.css
styles.js

Task
Some files had links to terms of use instead of license. Updated them so all point to license.
Closes #1512

Updated licese URLs

---

plugins/balloontoolbar/skins/default.css
plugins/balloontoolbar/skins/kama/balloontoolbar.css
plugins/balloontoolbar/skins/moono-lisa/balloontoolbar.css
plugins/balloontoolbar/skins/moono/balloontoolbar.css

Task
Moved duplicated styles from balloon toolbar skins to default styles file.
Closes #1270

Moved duplicated styles from balloon toolbar skins to default styles file

---

contents.css
plugins/easyimage/styles/easyimage.css
tests/plugins/easyimage/manual/tableselection.html
tests/plugins/easyimage/manual/tableselection.md

bugfix
I've removed background on `figure` and on `cke_widget_wrapper_easyimage`.
Closes #1542

Fixed bug: Table selection leaves white space around the image

---

plugins/filebrowser/plugin.js

task
dosen't need to
- add dependacy
- update docs
close: #1568

Add dependency to filebrowser from filetools

---

tests/plugins/easyimage/widget.js

This PR fixes existing tests, it does not need any new ones.
I've just explicitly remove link plugin from editors.
Closes #1594

Fix for failing easyimage link integration tests 

---

plugins/clipboard/plugin.js
plugins/menu/plugin.js
tests/plugins/clipboard/manual/pastedialogmenumobile.html
tests/plugins/clipboard/manual/pastedialogmenumobile.md
tests/plugins/clipboard/manual/pastedialogmobile.md
tests/plugins/clipboard/mobilefix.js
tests/plugins/clipboard/mobilefixcontextmenu.js
tests/plugins/contextmenu/integration.js

New feature
It is a part of #595, extending the solution from #595 by adding context menu integration.
Closes #1347.

Paste dialog context menu integration for mobile

---

plugins/imagebase/plugin.js

Task
Cleaned some leftovers and misused ProgressReporter type.

Progressbar code cleanup

---

tests/plugins/contextmenu/integration.js

Bug fix
I've removed redundant assert that tested for removed property.
Closes #1616

Fixed: Failing test: tests/plugins/contextmenu/integration - test "menuShow" event params 

---

plugins/easyimage/plugin.js
plugins/imagebase/plugin.js

Other: version tags update
Some `@since` tags weren't properly updated (or get broken during merge).
Follow-up of #1611.

Updated some 4.8.0 tags leftovers to 4.9.0

---

tests/plugins/button/buttonicon.js

I've added quotes to the list of allowed characters as IE wraps URLs in them.
Closes #1621.

Fix for failing tests/plugins/button/buttonicon

---

CHANGES.md

Task
Add missing entry about Easy Image plugin.

Add changelog entry about Easy Image

---

tests/plugins/clipboard/_helpers/pasting.js
tests/plugins/easyimage/uploadintegrations.js
tests/plugins/imagebase/features/_helpers/tools.js

Other: failing tests fix
See https://github.com/ckeditor/ckeditor-dev/issues/1631#issuecomment-364394985 for detailed explanation.
Closes #1631.

Extended 'pasteFiles' helper in unit tests

---

tests/plugins/embed/manual/embed.html
tests/plugins/embedsemantic/manual/embedsemantic.html

task
- update test case, to have easy to copy-paste links
close: #1659

Update embed and embedsemantic manual tests

---

core/style.js

Task
Added missing [style](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_style.html) definition docs.
Closes #1567

Added style definition docs

---

plugins/easyimage/samples/easyimage.html
tests/plugins/easyimage/_helpers/tools.js
tests/plugins/easyimage/manual/imagestretch.html
tests/plugins/easyimage/manual/progressbar.html
tests/plugins/easyimage/manual/removeafterpaste.html
tests/plugins/easyimage/manual/undo.html
tests/plugins/easyimage/manual/upload.html
tests/plugins/imagebase/features/manual/upload.html

Other, task
Changed Cloud Services token/gateway URL to the new production-ready URLs.
Closes #1741.

Use new upload and token URLs for code related to Cloud Services

---

plugins/autocomplete/plugin.js
plugins/autocomplete/samples/customview.html
plugins/autocomplete/samples/mentions.html
plugins/autocomplete/samples/smiley.html
plugins/autocomplete/samples/utils.js
plugins/autocomplete/skins/moono-lisa/autocomplete.css
plugins/autocomplete/skins/moono/autocomplete.css
plugins/caretposition/plugin.js
plugins/caretposition/samples/caretposition.html
plugins/textmatch/plugin.js
plugins/textwatcher/plugin.js
tests/plugins/textwatcher/textwatcher.js

Task
Updated license headers for mentions.

Updated license headers for mentions

---

core/editable.js
plugins/clipboard/plugin.js

API docs change
Fixed two incorrect links in API docs.

Fix incorrect links in API docs

---

plugins/easyimage/styles/easyimage.css
tests/plugins/easyimage/manual/sideimagebig.html
tests/plugins/easyimage/manual/sideimagebig.md
tests/plugins/easyimage/manual/styles.html
tests/plugins/easyimage/manual/styles.md

New feature
No need for unit tests, it's a styling thing.
Just a minor CSS change, followed up with changes in manual styles.
Closes #1784.

Easy Image side widget restyled to take up to 50% width

---

core/ckeditor_base.js

Documentation fix
- Update documentation
Closes: #1788

Added missing event mixin for CKEDITOR namespace

---

tests/plugins/imagebase/features/caption.js

Refactored small typo https://github.com/ckeditor/ckeditor-dev/commit/83494f5dd317f2eb082fb7ef995fa5250978066f#diff-0ea1b71ff8587a169d30c3e2ca0811f2R462

Refactored small typo

---

plugins/filebrowser/plugin.js
tests/plugins/filebrowser/manual/uploadckfinder.html
tests/plugins/filebrowser/uploadbutton.js

PR corrections
Corrections to #1840 PR.
* Minor API docs adjusments.
* Used more precise assertions in the unit tests.
* Skipped the manual test when browser does not support XHR upload.

Corrections to CKFinder and filebrowser regression

---

tests/_benderjs/ckeditor/static/tools.js
tests/plugins/easyimage/_helpers/tools.js
tests/plugins/easyimage/commands.js

New test tools feature
Updated `bender.tools.createTestsForEditors` to allow run tests in isolation by creating new editor instance for each test case. Refactored easyimage tests to use new function.
Closes #1696

Added support to run tests in isolation

---

core/creators/themedui.js
core/skin.js

Documentation fixes
- add missing documentation which are used in our guides.
Closes #1781.

Add description for missing features linked in docs

---

tests/plugins/imagebase/features/link.js

Test fix
When running on IE tests are executed in isolation i.e. for each test case new editor instance is created.
This PR depends on #1697 
Closes #1552

Fixed failing tests for imagebase link feature

---

tests/plugins/easyimage/manual/easyimage.html

Task
Add CS configuration to generic Easy Image test.
Closes #1744.

Add CS config to the test

---

tests/_benderjs/ckeditor/static/tools.js
tests/core/selection/fake.js
tests/plugins/autoembed/autoembed.js
tests/plugins/codesnippet/editing.js
tests/plugins/codesnippet/highlighter.js
tests/plugins/codesnippet/undo.js
tests/plugins/codesnippet/upcast.js
tests/plugins/codesnippetgeshi/codesnippetgeshi.js
tests/plugins/easyimage/uploadintegrations.js
tests/plugins/embed/integration.js
tests/plugins/embedbase/undo.js
tests/plugins/embedsemantic/integration.js
tests/plugins/image2/upcast.js
tests/plugins/imagebase/features/_helpers/tools.js
tests/plugins/imagebase/features/caption.js
tests/plugins/mathjax/mathjax-mock.js
tests/plugins/placeholder/dialog.js
tests/plugins/widget/_helpers/tools.js
tests/plugins/widget/acf.js
tests/plugins/widget/nestedwidgets.js
tests/plugins/widget/undo.js
tests/plugins/widget/widgetapi.js
tests/plugins/widget/widgetsintegration.js

New feature
Moved objToArray to bender tools and changed some tests to use new function.
Closes #1690

Moved objToArray to bender tools

---

core/dom/rect.js

Typo fix
No need for tests, just a typo fix.
Corrected a typo.

Fixed a typo in DOM Rect docs

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/security-issue.md
.github/ISSUE_TEMPLATE/task.md

Task
**NO**
Added new issues templates to enhance our issue reporting flow. There are templates for:
* bug report,
* feature request,
* task,
* security issue.

Add issues templates

---

tests/plugins/autocomplete/autocomplete.js

The test is no longer dependent on document position.
Closes #2051

Fixed autocomplete failing test from the dashboard

---

CHANGES.md

Update chaneglog with SCAYT and WSC information
- update changelog
Close #2050

Add changelog entry for SCAYT and WSC

---

tests/core/dom/range/getclientrectsabsolute.js
tests/core/tools/absoluterectposition.js

Fixing failing test
Toolbar height affects absolute rects, so I've added empty toolbar to editor to make it consistent.
Closes #2092

Fixed failing test on build editor

---

tests/plugins/autocomplete/autocomplete.js
tests/plugins/autocomplete/model.js
tests/plugins/autocomplete/view.js
tests/plugins/autocomplete/viewposition.js

Task
Ignored autocomplete tests for ie8.
Closes #2115

Ignored autocomplete tests for ie8

---

tests/core/tools/manual/throttle.html
tests/plugins/autocomplete/manual/itemslimit.html
tests/plugins/textmatch/manual/fillingcharsequence.html

Failing test
Fixed autocomplete related tests for ie8.
Closes #2153

Fixed autocomplete related tests for ie8

---

core/filter.js

Task/bugfix
Fixed few links from API docs to guides.
#1700

Fixed: Broken links with anchors from API docs to guides

---

tests/plugins/autocomplete/manual/itemslimit.html
tests/plugins/tableresize/manual/mergedcells.html
tests/plugins/textmatch/manual/fillingcharsequence.html
tests/plugins/textwatcher/manual/movementkeys.html

Task
Added `bender.tools.env.mobile` as condition to ignore tests.
Closes #2170

Ignoring tests on mobile devices

---

CHANGES.md
plugins/emoji/plugin.js
tests/plugins/emoji/basic.js
tests/plugins/emoji/manual/caseinsensitive.html
tests/plugins/emoji/manual/caseinsensitive.md

Bug fix
Testing emoji match with case insensitive RegExp.
Closes #2167.

Matching emoji case insensitive

---

CHANGES.md

Changelog fix
Several entries for bug fixes didn't have `Fixed:` prefix. I added it.

Add missing Fixed: prefix

---

tests/plugins/colorbutton/colorbutton.js

Task
Removed redundant frame variable.
Closes #2233

Removed redundant frame variable from colorbutton tests

---

CHANGES.md

Missing "#" typo in changelog ticket number.

Fixed typo in changelog

---

plugins/bbcode/plugin.js
tests/plugins/bbcode/bbcode.js

New feature
yes, or at least, they will contai, wait for it
Added support for div tags having style text-align

Add support for align (left, center, right tags)

---

CHANGES.md
plugins/bbcode/plugin.js
tests/plugins/bbcode/bbcode.js
tests/plugins/bbcode/manual/justify.html
tests/plugins/bbcode/manual/justify.md

New feature
Brings justification handling to the BBCode plugin.
This is a followup from #434 where I added all my review corrections.
Closes #2248.

Justify support in BBCode plugin

---

CHANGES.md
plugins/widget/plugin.js
tests/plugins/widget/definition.js

New feature
No need for manual test as this is API only change.
Simply added proper argument, and tests.
Follow-up of a #235.
Closes #2253.

Widget definition's insert method provides commandData and editor instance

---

core/filter.js
tests/core/filter/filter.js

Added missing docs on array type of CKEDITOR.filter.check first param

---

plugins/widgetselection/plugin.js

https://github.com/ckeditor/ckeditor-dev/issues/1719
Bugfix for https://github.com/ckeditor/ckeditor-dev/issues/1719
No
Applied the fix by @casjonker as requested by @jacekbogdanski.

Fixed widgetselection plugin receiving keystrokes from outside of the editable

---

CHANGES.md
core/style.js
tests/plugins/dialogadvtab/dialog.js
tests/plugins/dialogadvtab/manual/multiplelinks.html
tests/plugins/dialogadvtab/manual/multiplelinks.md

Bug fix
I took the PR, added tests - however the initial fix was in a wrong place (see the comment linked below).
Most of the issue has been described here: https://github.com/ckeditor/ckeditor-dev/pull/1914#discussion_r206872504
The code itself is not fancy, but it does not make sense to refactor it all around, just revert it to initial state where …

Fixed id attribute for new subsequent links

---

tests/plugins/tableselection/manual/integrations/clipboard/clipboard.html
tests/plugins/tableselection/manual/integrations/clipboard/mixedcontent.html
tests/plugins/tableselection/manual/tableselection.html

Task
I moved `tfoot` element below `tbody`.
Closes #2165

Fixed table structures for tableselection manual tests

---

CHANGES.md
plugins/tableselection/styles/tableselection.css
tests/plugins/tableselection/manual/selectioncursor.html
tests/plugins/tableselection/manual/selectioncursor.md

New feature
Added additional CSS style for cells selection.
Closes #706

Changed cursor type when selecting cells

---

plugins/dialog/plugin.js

Task
Added docs for `CKEDITOR.dialog.validation`.
Closes #2230

Added dialog validation docs

---

samples/js/sample.js

Typo fix
No, only a comment typo fix.
As I said above I fixed a typo in the comment. Grrr.

Fixed typo in plugin name

---

CHANGES.md
adapters/jquery.js
core/config.js
core/editor.js
core/env.js
core/filter.js
core/plugindefinition.js
core/style.js
plugins/autogrow/plugin.js
plugins/basicstyles/plugin.js
plugins/clipboard/plugin.js
plugins/cloudservices/plugin.js
plugins/codesnippet/plugin.js
plugins/codesnippetgeshi/plugin.js
plugins/colorbutton/plugin.js
plugins/copyformatting/plugin.js
plugins/devtools/plugin.js
plugins/embed/plugin.js
plugins/filebrowser/plugin.js
plugins/filetools/plugin.js
plugins/format/plugin.js
plugins/image2/plugin.js
plugins/magicline/plugin.js
plugins/mathjax/plugin.js
plugins/pastefromword/filter/default.js
plugins/resize/plugin.js
plugins/sharedspace/plugin.js
plugins/toolbar/plugin.js
plugins/widget/plugin.js

Docs improvements
- correct relative markdown links to `glink` format supported in Umberto.
Closes #2310

Correct relative links in code

---

plugins/pastefromword/plugin.js

Failing test / bug fix
I fixed what was causing tests to fail, but I'm not sure if they shouldn't just be ignored instead, as failing tests are related to PFW.
Closes #1638

Fixed: Failing test mobile Safari tests/plugins/clipboard/forcepasteasplaintext

---

tests/plugins/image2/manual/easyimage.html

Fixed tests/plugins/image2/manual/easyimage manual test

---

tests/plugins/justify/justify.js

Fix to failing tests
Assertions are now called asynchronously.
Closes #2349

Fixed failing tests tests/plugins/justify/justify n Firefox

---

CHANGES.md
plugins/tableselection/plugin.js
tests/plugins/tableselection/manual/rightclick.html
tests/plugins/tableselection/manual/rightclick.md
tests/plugins/tableselection/rightclick.html
tests/plugins/tableselection/rightclick.js

Fixed: Right-click doesn't clear selection created with tableselection plugin

---

tests/plugins/balloonpanel/positioningnonstatic.js
tests/plugins/easyimage/balloontoolbar.js

failing test fix
fix test for iOS
- add 1px error margin for easyimage on iOS
- rearrange test to work on iOS
Close #2350

Fix failing tests for iOS

---

CHANGES.md

Task
Removed API Changes duplicated header.

Removed redundant header

---

tests/plugins/balloonpanel/manual/balloonpanel.html

Test fix
Fixed invalid balloon panel creation.
Closes #1054

Fixed manual test causing balloon panel arrow reposition

---

plugins/dialogui/plugin.js
plugins/floatpanel/plugin.js
tests/plugins/imagebase/features/link.js

Most important was separating each test. Another thing was restoring selection in editor after selecting dialogs text input.
Closes #1686

Fixed failing tests on Edge

---

CHANGES.md

Task
Created new section in changelog, and moved bugfix entry there.

Added Fixed Issues section in changelog, moved 1477 entry.

---

package.json

Added package.json keywords

---

CHANGES.md
plugins/balloontoolbar/skins/moono-lisa/balloontoolbar.css
skins/moono-lisa/richcombo.css
tests/plugins/balloontoolbar/manual/moonolisaflickering.html
tests/plugins/balloontoolbar/manual/moonolisaflickering.md

Bug fix
Replaced border style hacking with `outline`.
Closes #1682

Fixed balloon toolbar flickering

---

plugins/autolink/plugin.js
tests/plugins/autoembed/autoembed.js
tests/plugins/autoembed/manual/notifications.html
tests/plugins/autoembed/manual/notifications.md
tests/plugins/autoembed/manual/spontaneousreembed.md
tests/plugins/autoembed/manual/undoautoembed.md
tests/plugins/autolink/autolink.js

Bug fix
Restored the old autolink behavior on paste event so it integrates with autoembed plugin smoothly.
Closes #2340

Fixed integration between autolink and autoembed

---

CHANGES.md

Task
I moved changelog entry for fixed issue from "API Changes" section into "Fixed Issues" one.

Move fixed issue into Fixed Issues section

---

core/filter.js

Task
I've explicitly link to `CKEDITOR.editor#destroy` method.
Closes #2524.

Fix docs warning about ambiguous link

---

plugins/autocomplete/samples/customview.html
plugins/autocomplete/samples/smiley.html
plugins/easyimage/samples/easyimage.html
plugins/emoji/samples/emoji.html
plugins/mentions/samples/mentions.html
samples/index.html
samples/toolbarconfigurator/index.html
tests/plugins/easyimage/manual/imageoutline.html

task
- fix broken links
Close #2402

Fix broken links in samples

---

tests/plugins/emoji/manual/repeated.html
tests/plugins/emoji/manual/spacerequired.html

Other: test fix
- add environment check for manual test
Close #2536

Ignore emoji manual test on unsupported environemnt.

---

tests/core/editor/manual/commandkeystrokeall.html
tests/core/selection/manual/focusnestededitable.md
tests/plugins/emoji/manual/twoeditors.md

Task
I've fixed typos in tests.
Closes #2531.

Fix typos in tests

---

tests/plugins/button/manual/label.html

I've removed unnecessary buttons from toolbar and explicitly selected "Set Language" button.
Closes #2542.

Fix for tests/plugins/button/manual/label

---

tests/plugins/autoembed/manual/notifications.md

Description improvement.
* Correct manual test description
Close #2553

Correct test case description, to describe IE8 situation

---

tests/plugins/widget/manual/nestededitablefilters.html

* Correct test for IE8
Close #2557

Correct usage of addEventListener for IE8 test

---

plugins/emoji/skins/default.css
tests/plugins/emoji/manual/dropdown/statusbar.md

Bug fix
Fixed line height will improve status bar visibility which differs between OS.
Closes #2561

Fixed emoji status bar visibility

---

adapters/jquery.js

Docs: corrected wrong link.

---

CHANGES.md
package.json

Task
No need for tests, this is only a change in `package.json`.
Just license adjustment.
Closes #2603.

Added explicit information that GPL 2.0 and later are supported in the package.json

---

CHANGES.md
skins/moono-lisa/toolbar.css
tests/core/skin/manual/moonolisaseparator.html
tests/core/skin/manual/moonolisaseparator.md

Bug fix
Added missing styles.
Closes #2546

Fix for: Separator in toolbar moves when buttons are focused

---

tests/_benderjs/ckeditor/static/tools.js

Task
Corrected docs entry for test tool.
Closes #2684

Tests: updated docs entry.

---

plugins/codesnippet/plugin.js
plugins/easyimage/plugin.js

Docs improvements
* change links which points to invalid places
Close #2636

Correct docs links

---

CHANGES.md

task/typo
Added missing backticks and typo fix in changelog.

Added missing backticks and typo fix in changelog

---

CHANGES.md

Task
Skipped the unit test /  manual test as this is external library. Though I'll propose to make manual test for that kind of fixes on our next meeting.
This PR assumes that https://github.com/ckeditor/ckeditor-presets/pull/26 gets merged.
Closes #2716.

Added changelog entry for SCAYT upgrade

---

tests/plugins/list/blockconversion.js

Test fix
Entities plugin changes dot character encoding.
Closes #2722

Fix failing test tests/plugins/list/blockconversion

---

tests/plugins/tabletools/allowedcontent.js

Failing test
I've explicitly selected "Table Cell" menu via CSS class.
Closes #2621.

Fix for failing test in plugins/tabletools/allowedcontent

---

plugins/undo/plugin.js

Typo fix
None, just a few typo fixes so it's safe.
Typo fixes in undo plugin.

Docs: fixed couple typos in undo plugin comments

---

dev/builder/build-config.js

Task
* Add `.github` folder to ignored in builder
Close #2767

Update build script to ignore .github

---

core/htmlparser/filterRulesDefinition.js

Fixes docs reference to the method.

Fix docs reference typo for filterRulesDefinition

---

tests/plugins/pastefromword/generated/tickets2.js

Fix failing test caused by pagebreak PFW integration

---

CHANGES.md
plugins/clipboard/plugin.js
tests/plugins/clipboard/drop.js
tests/plugins/clipboard/manual/droponmargin.html
tests/plugins/clipboard/manual/droponmargin.md

Fix disappearing content when dropped on editor's margin

---

tests/_benderjs/ckeditor/static/bot.js

See https://github.com/ckeditor/ckeditor-dev/pull/2828#pullrequestreview-205822343

Fix typo in mouse button name in test tools

---

core/tools.js

Bug fix
Added additional check for quirks mode in `CKEDITOR.tools.getMouseButton`, as IE9 QM still advertise it as IE9.

QM button fix

---

tests/_benderjs/ckeditor/static/bot.js
tests/core/tools.js
tests/plugins/easyimage/uploadintegrations.js
tests/plugins/imagebase/features/upload.js

Task
* Improve travis behaviour
Close #2818

Travis improvements

---

tests/plugins/autolink/manual/sourcemode.html
tests/plugins/clipboard/manual/droponmargin.html
tests/plugins/elementspath/manual/dragging.html

Task
Corrected wrong property to check for env.mobile.

Corrected wrong env.mobile check in manual test

---

tests/plugins/clipboard/readonly.js

Failing test
Add target to mocke event, so listeners won't throw typeerror.
Closes #3016

Fix for: [Edge] Failing test on built version /tests/plugins/clipboard/readonly

---

samples/index.html

Task
I've added `meta[name="viewport"]` to sample.
Closes #3033

Add meta viewport to sample

---

core/plugindefinition.js

Property didn't exist even though it is used heavily.
I added icons property to type pluginDefinition and documented the changes.
Closes #2947

Add icons property to class pluginDefinition

---

plugins/pastefromword/filter/default.js

Task
When working on #2935 we did plenty of refactoring of initial code. One unused param slipped, this PR fixes it.

Remove leftover unused param

---

CHANGES.md
core/config.js
core/editor.js
core/filter.js
core/style.js
core/ui.js
plugins/autoembed/plugin.js
plugins/autogrow/plugin.js
plugins/basicstyles/plugin.js
plugins/codesnippet/plugin.js
plugins/codesnippetgeshi/README.md
plugins/codesnippetgeshi/plugin.js
plugins/colorbutton/plugin.js
plugins/copyformatting/plugin.js
plugins/devtools/plugin.js
plugins/embed/plugin.js
plugins/format/plugin.js
plugins/image2/plugin.js
plugins/magicline/plugin.js
plugins/mathjax/plugin.js
plugins/resize/plugin.js
plugins/sharedspace/plugin.js
plugins/stylesheetparser/plugin.js
plugins/toolbar/plugin.js
samples/index.html

Task
This is required by ckeditor/ckeditor-docs#249

Change links from Functionality Overview subsection to new Features section

---

tests/plugins/tableselection/integrations/clipboard/xss.js

I've restored initial version of ignore assertion.
Closes #3181.

Fix for failing test in tests/plugins/tableselection/integrations/clipboard/xss

---

tests/plugins/balloontoolbar/positioning.js

Balloon toolbar should be clean up between tests

---

tests/plugins/tabletools/manual/cellheight.md

Other
I've added missing tag to one of manual tests.

Add missing tag to cellheight manual test

---

.github/PULL_REQUEST_TEMPLATE.md

Other
I've added "proposed changelog entry" section to our PR template.

Add field for changelog entry in our PR template

---

tests/plugins/pastefromword/generated/vertical_margin.js

Fix tests/plugins/pastefromword/generated/vertical_margin test suite

---

tests/plugins/notification/manual/_helpers/manualplayground.js

none
Added extra check for console, so that it won't break code when executing tests in IE with console closed.
Closes #3200

Fix for: Failing test tests/plugins/notification/manual/classic

---

samples/index.html

Task
None
Corrected link href.
Closes #3295

Fix for: broken features link on CKEditor sample page

---

core/ckeditor_base.js

Remove note about an already resolved issue.
Closes #3372.

Remove outdated reference to closed issue in docs for CKEDITOR.timestamp property

---

.travis.yml

Task
None.
Closes #3410. Closes #3407.

Updated Ubuntu distro

---

core/dom/element.js

*Describe the purpose of the pull request in a few simple sentences.*
QM should be treated as ~IE8 support (it's actually IE6).

Quirk mode fix for detached elements

---

README.md

No changelog entry should be added with this PR.
I have reused part of the readme which is used for `ckeditor` NPM package, but extended **Getting started** section. Also left previous part of the readme (but moved to the end) describing how to work with `ckeditor-dev` repository.
Closes #3176.

README file improvements

---

tests/core/dom/range/manual/followingfcs.html
tests/core/dom/range/manual/gettableelement.html
tests/core/editable/manual/insertgetdata.html
tests/plugins/panel/manual/keydown.html
tests/plugins/pastefromgdocs/detectgdocs.js
tests/plugins/pastefromgdocs/generated/basic.js
tests/plugins/pastefromgdocs/manual/nestedlists.html
tests/plugins/pastefromgdocs/manual/pastefromgdocs.html
tests/plugins/pastefromgdocs/multiplehandlers.js
tests/plugins/pastetools/manual/loadingfilters.html
tests/plugins/widget/manual/clipboardhtml.html
tests/plugins/widget/manual/clipboardhtmlselectall.html
tests/plugins/widget/manual/draghandlerreadonly.html

Task
I ignore tests 😎
Closes #3454.

Ignore some tests on mobile devices

---

.travis.yml

Task
None, as it's a change connected with CI.
None, as it's a change connected with CI.
I've created whitelist of branches that should be build on Travis CI:
* `master`,
* `major`,
* `stable`,
* version tags (e.g. `4.12.0`),
* release branches (e.g. `release/4.5.x`).

Create whitelist of branches to build on Travis

---

README.md

Task
```
none
```
Changed badge links from `ckeditor` to `ckeditor4`
Closes #3675.

Update npm badge.

---

README.md

Task
```
none
```
Bumped CDN script from `4.12.1` to `4.13.0`.
Closes #3679.

Update CDN link in README.md

---

.github/PULL_REQUEST_TEMPLATE.md
dev/docs/codestyle.md

Task
The code style guide has been copied from https://github.com/ckeditor/ckeditor-idiomatic.js/pull/2 - follow discussion for more information.
Closes #3740

Add code style guide

---

.github/ISSUE_TEMPLATE/1-bug-report.md

Task
No changelog entry needed.
I've added a short info about adding reproductions with a link to CodePen sample (based on https://github.com/ckeditor/ckeditor4/issues/3790#issuecomment-575141543). However I'm not sure if the sample is not too complex 🤔 I'm also thinking about adding another services, like JSFiddle and CodeSandbox (for more complex bugs). …

Add code templates to issue template

---

tests/plugins/widget/integration/selection/crosscontentselection.js
tests/plugins/widget/integration/selection/safaricrosscontentselection.js

Fix incorrect Safari test

---

plugins/colorbutton/plugin.js

Docs update
Not required.
Docs update.
Closes #3994

Update docs for setting custom colorbutton style definitions

---

CHANGES.md
plugins/notification/plugin.js
tests/plugins/autoembed/manual/bottomtoolbar.html
tests/plugins/autoembed/manual/bottomtoolbar.md
tests/plugins/notification/layout.js
tests/plugins/notification/manual/toolbarbottom.html
tests/plugins/notification/manual/toolbarbottom.md

Bug fix
```
*[#624](https://github.com/ckeditor/ckeditor4/issues/624): Fixed: [Notification](https://ckeditor.com/cke4/addon/notification) doesn't work with …
```

Fix notification with bottom toolbar

---

CHANGES.md
config.js
dev/builder/build-config.js
plugins/placeholdertext/plugin.js
tests/plugins/placeholdertext/manual/easyimage.html
tests/plugins/placeholdertext/manual/easyimage.md
tests/plugins/placeholdertext/manual/fullpage.html
tests/plugins/placeholdertext/manual/fullpage.md
tests/plugins/placeholdertext/manual/placeholdertext.html
tests/plugins/placeholdertext/manual/placeholdertext.md
tests/plugins/placeholdertext/placeholdertext.html
tests/plugins/placeholdertext/placeholdertext.js

Feature
```
*[#3793](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Introduce [Placeholder Text](https://ckeditor.com/cke4/addon/placeholdertext) …
```

Introduce placeholdertext plugin

---

tests/plugins/colorbutton/manual/customclassbackground.html

Bug fix.
No changelog entry for fixing tests.
Fix configuration option from `colorButton_backStyle` in manual test for color button plugin …

Fix config for manual test (customclassbackground).

---

README.md

Taskk
skip
Added Vue.js mention and link to npm package.
Closes #4089.

Add info about Vue.js integration to README file

---

plugins/print/plugin.js

Docs
skip
Instead of abstract external API [here](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_print.html) I used the `Export to PDF` …

Replace 'print' API example using 'Export to PDF' plugin

---

.github/PULL_REQUEST_TEMPLATE.md

Bug fix
skip
Added a ` ` character.
Closes #4149.

Add missing space character

---

core/dtd.js

Docs
skip
Added the information proposed in https://github.com/ckeditor/ckeditor4-docs/pull/261. Thanks to the user @lkmorlan for this initiative!
Closes …

Add use example of CKEDITOR.dtd object

---

core/event.js

Docs (api)
```
* [#4123](https://github.com/ckeditor/ckeditor4/issues/4123): Add info that a named function can't be listening for the same event more than …
```

Docs: add note about registered event listener (on event method).

---

tests/plugins/mathjax/mathjax.js

Skip.
See #4232 for more details on this issue.
Closes #4232.

Fix initialization flow in mathjax unit tests

---

tests/plugins/colorbutton/contentcolors.js
tests/plugins/colorbutton/customcolors.js
tests/plugins/easyimage/uploadintegrations.js

Some tests are failing due to localization differences.

Force language to ensure assertions

---

tests/plugins/autocomplete/manual/sourcemode.md
tests/plugins/clipboard/manual/buttons.html
tests/plugins/colorbutton/manual/colorhistory/tworows.html
tests/plugins/pastefromword/manual/pastefromword.html
tests/plugins/pastefromword/manual/pastefromword.md

Task
Skip.
Fixed some minor issues in manual tests we noticed during testing phase.
Closes #4250.

Minor manual tests adjustments after 4.15.0 testing phase

---

.github/workflows/stalebot.yml

Small automation for closing stale issues.

Add stalebot GitHub action

---

core/selection/optimization.js

Task
None
Added licence and file overview headers.
Closes #4311.

Missing missing headers in core/selection/optimization.js

---

CHANGES.md
core/creators/inline.js
core/editable.js
core/tools.js

Changelog 4.15.1

---

core/plugins.js
core/style.js

Bug fix
```
Skip
```
- Added note in API comments, that `CKEDITOR.stylesSet` is instance of `CKEDITOR.resourceManager`
- Removed `@extends` …

Fix Samples for CKEDITOR.stylesSet object's methods are calls of CKEDITOR.plugin

---

CHANGES.md
plugins/autolink/plugin.js
tests/plugins/autolink/autolink.js
tests/plugins/autolink/manual/autolink.html
tests/plugins/autolink/manual/autolink.md
tests/plugins/autolink/manual/continoustyping.html
tests/plugins/autolink/manual/continoustyping.md
tests/plugins/autolink/manual/customregex.html
tests/plugins/autolink/manual/customregex.md
tests/plugins/autolink/manual/fillingcharsequence.md
tests/plugins/autolink/manual/link.html
tests/plugins/autolink/manual/link.md
tests/plugins/autolink/manual/mail.html
tests/plugins/autolink/manual/mail.md
tests/plugins/autolink/manual/sourcemode.md
tests/plugins/autolink/manual/typing.html
tests/plugins/autolink/manual/typing.md
tests/plugins/autolink/typing.js

Bug fix
Updated autolink plugin to require link.
Closes #1824.
Closes #2208.

Link is now required by autolink plugin

---

tests/core/ckeditor/manual/hcdetection.html
tests/core/ckeditor/manual/hcdetection.md
tests/core/ckeditor/manual/hcdetectionunsupported.html
tests/core/ckeditor/manual/hcdetectionunsupported.md

Add missing information about.
```
Skip
```
Add manual tests information about unsupported browsers. Also, add test ignore for those browsers
Closes #4505 .

Add info about test ignore on specyfic browsers

---

.github/workflows-config.json
.github/workflows/setup-workflows.yml

Fix: setup-workflows.yml wasn't update itself from common workflows repo. 
```
Skip
```
Update setup-workflows.yml to the newest version (from …

Add workflows config, update setup-workflow

---

tests/plugins/balloontoolbar/positioning.js

Bug fix
Skip
After verifying that the test works on Chrome and IE9-11 I unignored it.
Closes #3868.

Unignore test in `tests/plugins/balloontoolbar/positioning` which no longer fails

---

CHANGES.md

Typo fix
```
none
```
I've linked the PR instead of the issue in the changelog 😞 
No issue.

Correct the ticket number linked in the changelog

---

tests/plugins/notification/notification.js

Bug fix
```
none
```
Removed a typo in if statement to correctly checking property.
Closes #4017

Fixing typo.

---

core/config.js

Docs
Not needed
I've added info that the option is used only in `<iframe>`-based editor. Additionally I've added some info about `divarea` plugin to the guide …

Clarify docs about contentsCss config option

---

core/ui.js

API docs 
null
The return object information was missing from the method `CKEDITOR.ui.get()`.
Closes #4337

Docs: Update info about retrieved object from method

---

.travis.yml

Skip.
The `if` defining branch names for non-PRs seems to be defined incorrectly and fails https://travis-ci.com/github/ckeditor/ckeditor4/jobs/510433850#L259. …

Fix defining branch names on main branches

---

core/editor.js

Typo fix
```
skip
```
Fix typo in editor.status API comments to `config.observableParent`

Fix typo in config link

---

.editorconfig
.travis.yml

Task
Not needed
I've added Travis config for Safari 🤞🏻
Also updated `.editorconfig` to correctly indent `*.yml` files.
Closes …

Enable Safari on CI

---

bender-runner.config.json

Task
Not needed
I've added Safari to the list of browsers available on macOS.

Hot fix for running Safari on CI

---

SECURITY.md

Add security contact file.
```
skip
```
Used our SECURITY file from CKE5.
Closes #4797

Add SECURITY.md with email for contact.

---

tests/plugins/font/manual/nestingclasses.html

Fix for test
N/A
I've added missing ACF rules to `tests/plugins/font/manual/nestingclasses` test.

Add missing ACF rules to the test

---

.travis.yml
package-lock.json

```
- skip
```
Just update package-lock file after installation with npm version 7.
According to: https://github.com/cksource/ckeditor4-team/issues/92
Also, we …

Migrate to npm7

---

tests/core/editable/keystrokes/delbackspacequirks/manual/nbspdeleting.html
tests/plugins/font/manual/nestingclasses.md
tests/plugins/uploadwidget/manual/escapecssuploadimage.html

Fix for failing tests
Not needed
I've ignored or modified tests for mobile devices.
Closes #4825.

Ignore tests on mobile

---

tests/plugins/widget/nestedwidgets.js

```
skip
```
Ignore test on IE, fix arguments order in assert.
Closes #4819

Ignore failing test on IE

---

tests/plugins/placeholder/dialog.js

Ignore failing test
```
not needed
```
Add return statement when the test is ignored.
Closes #3768.

Properly ignore failing test on IE8

---

tests/core/dom/element/element.js

Failing test fix.
```
skip
```
Failing test values were:
- Expected: 198.2
- Actual: 198.21
- Real width of the element on the mobile …

Decrease precision of calculations in failing test

---

tests/plugins/widget/nestededitables.js

Fix failing tests.
- [#] PR is consistent with the code style guide
```
skip
```
I run the test suite for IE11, IE9 15 times. More or less …

Ignore unstable tests on IE

---

plugins/flash/plugin.js
tests/plugins/flash/error.js
tests/plugins/flash/manual/error.md

Task
```
skip.
```
As mentioned in https://github.com/ckeditor/ckeditor4-docs/pull/372#pullrequestreview-765492546 due to a more generic plugin error code …

Update error reference object key

---

tests/core/htmldataprocessor/htmldataprocessor.js
tests/plugins/iframe/iframe.js

```
skip
```
We disabled any HTML content in iframe elements some time ago.
Closes #4822

Fix htmldataprocessor unit test

---

tests/core/editable/manual/notwantedelementsonselectallandbackspaceedge.html
tests/plugins/justify/justify.js
tests/plugins/pastefromword/manual/removedclasses.html
tests/plugins/wysiwygarea/contentscss.js

Fix failing tests.
```
skip
```
- Based on https://github.com/ckeditor/ckeditor4/issues/4903#issuecomment-929318478 - I added `%TEST_DIR%' to assets path in …

Ignore & fix failing tests on major

---

tests/plugins/clipboard/manual/pasteimageperformance.html
tests/plugins/clipboard/manual/pasteimageperformance.md

```
skip
```
Replaced backticks with single quotations. Also, grouped two variables declaration into a single one.
Now the test is properly …

Use single quote instead of backticks(support IE)

---

tests/plugins/a11yhelp/manual/focusinfo.html
tests/plugins/clipboard/manual/draganddrop.html
tests/plugins/clipboard/manual/draganddropfilenotification.html
tests/plugins/clipboard/manual/draganddropimage.html
tests/plugins/clipboard/manual/pastefilenotification.html
tests/plugins/clipboard/manual/pasteimage.html
tests/plugins/flash/manual/error.html
tests/plugins/maximize/manual/historyapi.html
tests/plugins/maximize/manual/historyapihash.html
tests/plugins/maximize/manual/historyapioff.html
tests/plugins/widget/manual/insertparagraphbetween.html
tests/plugins/widget/manual/insertparagraphblockwidget.html
tests/plugins/widget/manual/insertparagraphentermodes.html
tests/plugins/widget/manual/insertparagraphinlinewidget.html
tests/plugins/wysiwygarea/manual/detached.html
tests/plugins/wysiwygarea/manual/detachedembededimagesource.html
tests/plugins/wysiwygarea/manual/detachedtwoeditors.html
tests/plugins/wysiwygarea/manual/detachedundo.html
tests/plugins/wysiwygarea/manual/detachedwithplugins.html
tests/plugins/wysiwygarea/manual/detachedwithpluginsfullpage.html

Task
```
Not required.
```
Ignored tests not suitable for mobiles.

Ignore tests not suitable for mobiles

---

.travis.yml

Fix: enable travis for `next` branch
```
skip
```
add `next` branch to travis cfg

Add next branch to travis builds

---

CHANGES.md

Changelog review.

---

README.md

Task
```
skip
```
Removed deprecated David badges.
Closes #4998

Remove David badges from readme

---

.github/ISSUE_TEMPLATE/1-bug-report.md

Task
```
skip
```
I updated our editor bug templates. 
One inconsistency I notice is StackBlitz which does not allow linking to the full editor.
Closes #4902

Bump version of the editor bug templates

---

.travis.yml

Bug fix
```
skip
```
Pass PR repo slug to the bender runner as described in: https://github.com/ckeditor/ckeditor4-benderjs-runner/pull/23

Pass PR repo slug to the bender runner

---

package-lock.json
package.json

Task
skip
Simple update for `shelljs` dependency.

Update shelljs dev dependency

---

tests/plugins/bidi/bidi.js
tests/plugins/bidi/manual/usecomputedstate.html
tests/plugins/bidi/manual/usecomputedstate.md
tests/plugins/justify/justify.js
tests/plugins/justify/manual/usecomputedstate.html
tests/plugins/justify/manual/usecomputedstate.md
tests/plugins/justify/manual/usecomputedstatedir.html
tests/plugins/justify/manual/usecomputedstatedir.md

Task
skip
I've added both unit and manual tests for `config.useComputedState` for `bidi` and `justify` plugins. Unfortunately, I wasn't able to come up with …

Add tests for `config.useComputedState`

---

CHANGES.md

Changelog review.
```
* [#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few …
```

Docs: changelog review.

---

package-lock.json

Updated dev dependencies by patch/minor versions.

Update dev dependencies

---

CHANGES.md
adapters/jquery.js
bender.js
tests/adapters/jquery/events.js
tests/adapters/jquery/form.js

Update the jQuery Adapter to replace deprecated jQuery API calls
https://github.com/jquery/jquery-migrate/blob/main/warnings.md
Doesn't change the editor code.
Looks OK
```
* [#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few simple sentences.
```
Closes #5087.

Fixes for jQuery 3.6.0

---

.npm/README.md
README.md

Task
N/A
I've updated CI badge to point to Travis-CI.com instead of Travis-Ci.org.
I've also removed David badges from npm's readme.
Closes #5001 .

Update CI badge

---

core/dataprocessor.js

dataprocessor.js: fix typo in docs of toDataFormat

---

tests/core/skin/manual/kamamultiselect.html
tests/core/skin/manual/moonolisamultiselect.html
tests/core/skin/manual/moonomultiselect.html
tests/plugins/image2/link.js
tests/plugins/templates/templates.js

Bug fix / Failinig tests fix
```
none
```
For #5119 - added test ignore
For #5116 - enlarged test awaiting time. On slower networks …

Fix failing tests

---

core/dom/range.js

…cope
```
* none
```
Closes #5177 .

Fix strict mode: Move function declaration outside the switch statement

---

tests/plugins/maximize/aria.js

N/A
I've ignored tests on iOS as the plugin is disabled there.
Closes #5194.

Ignore maximize tests on iOS.

---

core/creators/inline.js
core/creators/themedui.js
core/dom/range.js
core/editor.js
core/htmlparser/fragment.js
plugins/clipboard/plugin.js
plugins/uploadwidget/plugin.js

Docs: API docs review for 4.19.0 release.
Closes: https://github.com/cksource/docs/issues/465
```
* …
```

Docs: 4.19.0 release review.

---

.travis.yml

```
* [#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few simple sentences.
``` …

Update travis bender runner dependency

---

tests/plugins/uploadfile/manual/uploadfilenotificationoff.html
tests/plugins/uploadimage/manual/unsupportedfileformat.html
tests/plugins/uploadwidget/manual/fileformatnotification.html
tests/plugins/uploadwidget/manual/unsupportedfileformat.html
tests/plugins/uploadwidget/manual/unsupportedfileformatmultiple.html
tests/plugins/wysiwygarea/manual/tabindex.html

Task
Skip.
Closes https://github.com/ckeditor/ckeditor4/issues/5206
Closes https://github.com/ckeditor/ckeditor4/issues/5207

Ignore tests on mobiles

---

tests/plugins/uploadwidget/manual/unsupportedfileformat.html

Ignore test on IE<11

---

.travis.yml

Bender runner CI testing PR.
Changed the bender runner branch used on CI

Update bender runner to v1.2.0

---

tests/plugins/emoji/dropdown.js

```
skip
```
I moved the problematic test case to second place in the test suite. The first one validates emojis caching …

Fix failing emoji dropdown test

---

tests/plugins/pastefromword/generated/_helpers/pfwTools.js

```
* skip
```
Removed language plugin from PFW generate tests.
Closes #5267 .

Fix failing test: Remove language plugin from PFW generated tests

---

tests/plugins/a11yhelp/manual/screenreader.html
tests/plugins/toolbar/manual/focus.html

```
* [#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few simple sentences.
``` …

Ignore a11y manual tests on mobile

---

CHANGES.md
plugins/basicstyles/plugin.js
tests/plugins/basicstyles/basicstyles.js
tests/plugins/basicstyles/manual/togglesubsupscript.html
tests/plugins/basicstyles/manual/togglesubsupscript.md

New feature
```
* [#5215](https://github.com/ckeditor/ckeditor4/issues/5215): Added a new config option to disallow adding subscript and superscript at the …
```

Disallow adding subscript and superscript at the same time

---

CHANGES.md

Changelog review.
```
* [#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few …
```

A changelog review

---

tests/core/selection/fake.js

N/A
Added missing `?` in the regex 🙈

Fix incorrect regex in test

---

core/ckeditor_version-check.js
tests/core/manual/versioncheckmultiple.html
tests/core/manual/versioncheckmultiple.md

* Error message should be displayed only once
* Simplified query parameter

Update version check

---

.travis.yml
bender.js

Add license key to CI tests
