ckeditor/ckeditor4

- plugins/dialogui/plugin.js
as noticed by my colleague @BFriedrichs
> fix variable name typo in dialogui plugin

- samples/toolbarconfigurator/js/fulltoolbareditor.js
Love the new configurator! I've had good success integrating it with our [php-based CRM](https://civicrm.org/blogs/colemanw/big-changes-wysiwyg-editing-47) to allow users to configure their editing experience in-app. One little problem was that the missing "type" attribute on the buttons would cause premature form submission. Thanks for considering this change.
> Set toolbarconfigurator button "type" attribute

- dev/builder/build.sh
I first noticed `arrgs` instead of `args`, then looked for other nitpicks to fix :)
> Fix typos and make comments consistent in build.sh

- plugins/link/dialogs/link.js
Relevant ticket: https://dev.ckeditor.com/ticket/13887#ticket
The issue with the current code is it removes valid ascii characters from the target attribute value. To fix this it should instead check for any character that is non-ascii or white space.
> #13887 remove any non-ascii or white space character

- plugins/clipboard/plugin.js
- Correct spelling of `Advanced`
> Fix clipboard/plugin.js doc typo

- .gitignore
- .travis.yml
- bender.ci.js
- bender.js
- tests/plugins/image/nolinktab.js
- tests/plugins/uploadfile/uploadfile.js
This branch is based on current master with some "enhancements":
* there is separate Bender configuration for CI (`bender.ci.js`), which tweaks Bender's default especially for `bender run` command (e.g. disabling manual tests in Chrome and choosing Chrome as a default browser).
* the build is run on latest, stable Chrome on Node 4. Unfortunately Bender seems to be too old to run on newer Nodes without refactoring.
* Some tests had issues with paths to the assets (they were hardcoded and not based on `%BASE_PATH%` variable or paths were incorrectly normalised).
> Basic integration with Travis CI

- styles.js
As [#13818](http://dev.ckeditor.com/ticket/13818) (_Allow to link widget style definitions, so applying one style might disable the other_) was merged to `master`, we can now utilize it in our `styles.js` file.
> Group embed widget size styles.

- .travis.yml
The `bender.ci.js` is removed during build (https://github.com/ckeditor/ckeditor-presets/pull/5) so it needs to be copied to build folder in order to run tests.
> Copy bender.ci.js to build folder.

- .travis.yml
- bender.ci.js
This PR adds support for Firefox in our CI builds.
Note that for the time being I've added it into `allow_failures` matrix, which basically means that even though it's tests fail overall build will be marked as success. This is for transistional period, and to test the stability.
I already see [one uploadimage test](https://dev.ckeditor.com/ticket/16861) failing __most__ of the time.
Also note that I did remove `fast_finish` flag on purpose, so that Travis will wait with reporting job as done until Firefox is done (we still care about it).
Also used `addons: firefox "latest"` to make sure it's running latest Firefox version, as by default Travis uses Firefox 38 which is... kida outdated. I suppose it's due to the fact that it's the last version fully compatible with selenium, but that's a …
> Add support for Firefox in Travis builds

- .travis.yml
Now that our random failing test is fixed, we are ready to enable Firefox builds.
> Fully enable Firefox in Travis builds

- plugins/templates/plugin.js
As [one of our users points out](http://ckeditor.com/addon/templates#comment-3196671844) template docs could use some improvements.
In terms of API docs one thing missing for me is a better explanation on how the template files should look like, the best example is to point to working code.
> Linked an example template file in API docs

- CHANGES.md
- core/template.js
- tests/tickets/8584/csp.html
- tests/tickets/8584/csp.md
This PR is based on #254 and fixes part of [ticket #8584](http://dev.ckeditor.com/ticket/8584), replacing template system based on implicit `eval` with a template system based only on regular expressions.
> Removed eval usage from template

- plugins/copyformatting/plugin.js
- tests/plugins/copyformatting/keystrokes.js
- tests/plugins/copyformatting/manual/customkeystroke.md
The fix introduces keystroke switching. The CF apply format keystroke is attached only when format is copied (copy formatting active). When format is applied (normal) or canceled (normal/sticky), the keystroke is restored to the default one.
The generic mechanism for keystroke switching was not introduced since we do not see any use for it in other places/plugins. The simpler approach with storing default command was implemented.
There is already a manual test covering this case, so there is no need for another one.
_Merge message proposal:_
The `Ctrl + Shift + V` shortcut works both with _paste as plain text_ and _apply format_ (copy formatting plugin), depending on the context.
> T/16857 Ctrl + Shift + V blocked by copy formatting.

- plugins/sourcedialog/plugin.js
- plugins/widget/dev/assets/simplebox/plugin.js
I checked all the plugins by checking which ones utilizes dialog API `CKEDITOR.dialog`, depends on `widget` or has its own dialogs.
Then all the plugins which somehow depends on dialogs, but do not have `dialog` plugin as a dependency were run with CKEditor on minimal config (with `toolbar` and `wysiwygarea` plugins) to check if it is needed (basically, those were the two plugins I made changes in).
_Merge message proposal:_
Fixed missing dialog dependencies in dialog dependent plugins.
> T/16920 Widget plugins not using dialog as a direct dependency

- CHANGES.md
- plugins/tabletools/plugin.js
- tests/plugins/tabletools/manual/transformations/mixedBackground.html
- tests/plugins/tabletools/manual/transformations/mixedBackground.md
- tests/plugins/tabletools/tabletools.html
- tests/plugins/tabletools/tabletools.js
This PR fixes [#16971](https://dev.ckeditor.com/ticket/16971).
Current implementation finds color based on a simple regexp. Some time ago we wrote utility that does a simplified [background parsing](http://docs.ckeditor.com/#!/api/CKEDITOR.tools.style.parse-method-background).
The only thing that bugs me is that it results with a duplicated color property, because it does not remove the color from `background` css prop, while adding a second `background-color`. This is how it was implemented so far in other cases so I decided to make it compatible with how it works today.
> Improve background color detection in tabletools plugin

- core/tools.js
- tests/core/tools/style.js
Fix for [#16972](http://dev.ckeditor.com/ticket/16972).
This method should return an object, [as described in our API docs](http://docs.ckeditor.com/#!/api/CKEDITOR.tools.style.parse-method-background).
> Method tools.style.parse#background should return an object

- plugins/pastefromword/filter/default.js
Resulted in methods definiton leaking to global scope:
> Paste from Word docs - missing member property.

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/paste.js
After enabling Clipboard API in Safari, all clipboard related tests are green and pasting seems to be working as usual.
> T/16982 Safari's clipboard API can be trusted

- plugins/pastefromword/filter/default.js
- tests/plugins/pastefromword/generated/_fixtures/Table_text_attributes/Mixed/expected.html
- tests/plugins/pastefromword/parsestyles.html
- tests/plugins/pastefromword/parsestyles.js
The fix keeps the order of the css rules when parsing. The rules containing class selectors have higher priority and are applied first.
The styles already existing on the element are not overwritten which means:
- inline styles are preserved
- styles with the highest priority are applied first
The second point above means that the styles inlining applies rules containing class selectors first in a reversed order (so the last on goes first) and then rest of the rules also in reversed order.
Please keep in mind that this solution is a minimalistic (almost) approach to solve this specific issue. There are some cases which are not covered (more complex selectors, rules with multiple selectors, etc), however as Excel or Word does not generate such styles it is sufficient.
> T/16957 [PFW] Styles.inliner.inline does not take selectors specificity into account and duplicates rules.

- CHANGES.md
- core/dom/range.js
- tests/core/dom/range/shrink.html
- tests/core/dom/range/shrink.js
This PR adds third parameter to `CKEDITOR.dom.range`, `options`, which groups two options for the method:
* `shrinkOnBlockBoundary`
* `skipBogus`
For the compatibility if `options` is passed a boolean, then it's treated as `options.shrinkOnBlockBoundary`.
> t/17010 [API] Range#shrink method should allow for skipping bogus BR elements

- core/dom/range.js
- tests/core/dom/range/find.js
Fix for [#17022](https://dev.ckeditor.com/ticket/17022).
This change doesn't deserve a changelog entry, since this method is marked as a private.
> Fixed: range#_find does not return boundary end element

- CHANGES.md
- package.json
This PR updates Bender so that it works correctly with Node 7.x.
Issue [#17025](http://dev.ckeditor.com/ticket/17025) on Trac.
> Update Benderjs to 0.4.2

- core/editor.js
- tests/core/command/events.js
Currently if command is not passed an object as a second argument, it fall backs to undefined, causing the unability to pass anything from command to afterCommandExec event.
This change is intended to introduce empty object as a default value for command's event data.
> T/17027 Commands event data should be initialized as an empty object

- tests/plugins/pastefromword/generated/generic.js
**For Edge I just ignored the tests as Edge still do not use datatransfer.**
**For Safari it was a little more interesting:**
The test failed because of the reversed order of the spans with font-family styles:
In the [generated/generic tests two custom filters are used](https://github.com/ckeditor/ckeditor-dev/blob/4cacb998a8ff0093ed9b9e5deffeb5bae0270c58/tests/plugins/pastefromword/generated/generic.js#L52) to make html output consistent:
* [pfwTools.filters.span](https://github.com/ckeditor/ckeditor-dev/blob/4cacb998a8ff0093ed9b9e5deffeb5bae0270c58/tests/plugins/pastefromword/generated/_helpers/pfwTools.js#L20)
* [pfwTools.filters.style](https://github.com/ckeditor/ckeditor-dev/blob/4cacb998a8ff0093ed9b9e5deffeb5bae0270c58/tests/plugins/pastefromword/generated/_helpers/pfwTools.js#L94) …
> Failing test Object word2013 datatransfer (Edge, Safari).

- tests/plugins/widgetselection/integration.js
- tests/plugins/widgetselection/selectall.js
This PR fixes two failing tests on Chrome. It's a result of recent Chrome internal selection changes, as tests are passing with Chrome @ 58.0.3009.0.
The reason was simply that Chrome aligned selection anchoring to Blink's strategy, meaning that the seleciton would be anchored inside of a div.
The reason is that [two lines in `tests updating filler references on undo flow`](https://github.com/ckeditor/ckeditor-dev/blob/6064dd9/tests/plugins/widgetselection/integration.js#L171-L172) behave much differently on latest chrome.
On old Chrome (v58) and Safari these two lines will cause browser selection **to be modified**. So that as `newFiller.replace( filler )` is called, it will change range.startOffset to `1` (after the `div[data-cke-filler-webkit=start]`). On new Chrome it **does not …
> Fixed failing tests\plugins\widgetselection

- tests/plugins/pagebreak/pagebreak.js
It seems that Blink inherits WebKit behavior connected with `page-break-*` and `break-*` properties. In this case enabling Blink-only fix also in WebKit seems to do the trick.
> Failing pagebreak tests in WebKit

- plugins/clipboard/plugin.js
- plugins/pastefromword/filter/default.js
This PR fixes following issues with docs:
* things leaking into global scope,
* links to non-existent classes and methods,
* incorrect or duplicated variables/parameters names.
> T/tp2322 Various docs fixes

- core/selection.js
- plugins/tableselection/plugin.js
- tests/core/style/applyremove.js
- tests/plugins/tableselection/integrations/core/getextractselectedhtml.js
- tests/plugins/tableselection/integrations/core/style.js
- tests/plugins/tableselection/integrations/tabletools/tabletools.js
- tests/plugins/tableselection/manual/enable.html
- tests/plugins/tableselection/manual/enable.md
- tests/plugins/tableselection/manual/integrations/tabletools/tabletools.html
- tests/plugins/tableselection/table.js
- tests/plugins/tabletools/tabletools.js
Since we extracted table selection into a separate plugin, we can now safely remove this config variable.
Now the proper way to disable table selection is simply by removing tableselection plugin.
> Remove config.tableImprovements

- plugins/tableselection/plugin.js
- tests/plugins/tableselection/integrations/clipboard/pastenested.js
- tests/plugins/tableselection/integrations/core/style.js
- tests/plugins/wysiwygarea/contentscss.js
Some simply were failing because of ACF transformations, the other was failing because tabletools was adding an extra CSS file. Also added extra safety check, which was failing in one of the tests.
Fixes tests:
* http://tests.ckeditor.dev:10470/tests/plugins/wysiwygarea/contentscss
* http://tests.ckeditor.dev:10470/tests/plugins/tableselection/integrations/clipboard/pastenested
* http://tests.ckeditor.dev:1030/tests/plugins/tableselection/integrations/core/style
> Fixed tests affected by tabletools in the built version

- tests/plugins/widget/dnd.js
- tests/plugins/widget/undo.js
- tests/plugins/widget/widgetselection.js
Tests are not adding evt.data or evt.data.target to simulated mouseup events, which is an artificial situation.
Fixes following tests:
* http://tests.ckeditor.dev:10470/tests/plugins/widget/dnd
* http://tests.ckeditor.dev:10470/tests/plugins/widget/undo
* http://tests.ckeditor.dev:10470/tests/plugins/widget/widgetselection
> Fixed failing widget tests on built version

- tests/plugins/wysiwygarea/contentscssgeturl.js
This PR fixes test http://tests.ckeditor.dev:1030/tests/plugins/wysiwygarea/contentscssgeturl in the built version.
> Fixed contentscssgeturl test for CKEditor built version

- tests/core/editable/keystrokes/keystrokes.js
These tests were created for "regular" table selection and do not result with our improved selection.
> Fixed failing keystrokes/keystrokes test for the built version

- tests/core/editor/getextractselectedhtml.js
Reason for this test to fail was that build version contains by default table selection plugin, so while selecting it was also adding a custom markup to the cell (classes in particular). Thus tests were failing.
This test was failing only on Firefox (as these tests are ignored for other browsers).
> Fixed failing editor/getextractselectedhtml test on built version

- tests/core/selection/selection.js
This test was failing on built version, because there was undo plugin used, [which checks for modifier keys on native event object](https://github.com/cksource/ckeditor-dev/blob/576dc67/plugins/undo/plugin.js#L1242). It make sense to mimic native evt object in the test.
> Fixed failing selection built test for IE/Edge

- plugins/tableselection/plugin.js
- tests/plugins/tableselection/manual/inlineeditor.html
- tests/plugins/tableselection/manual/inlineeditor.md
Tableselection plugin tries to add CSS to editor, however inline editors don't have this method. I've added a simple check to detect if we can use this method.
> Fix for inline editors

- plugins/tableselection/plugin.js
- tests/plugins/tableselection/integrations/clipboard/xss.js
- tests/plugins/tableselection/manual/integrations/clipboard/xss.html
- tests/plugins/tableselection/manual/integrations/clipboard/xss.md
Paste handler in tableselection plugin uses temporary container to handle pasted data. However it allows to paste unsafe HTML inside it. This PR adds appropriate filter.
> Add filtering to paste handler in tableselection

- plugins/clipboard/plugin.js
- tests/plugins/clipboard/paste.js
Disable clipboard API support for iOS Safari as it still is not implemented correctly.
Basically it still does not provide `text/html` type in the clipboardData, see https://bugs.webkit.org/show_bug.cgi?id=19893#c34.
This was causing clipboard not to work in the editor, and our multiple tests to fail.
Support for Safari was initially added in https://dev.ckeditor.com/ticket/16982 (87ff1a5046).
> Disable clipboard API for iOS Safari

- tests/plugins/clipboard/manual/buttons.md
Now Firefox and Safari (desktop only) also supports clipboard api allowing for copy and cut.
> Corrections in clipboard/manual/buttons test

- .github/PULL_REQUEST_TEMPLATE.md
The reason is we want to keep it as short as possible.
> Removed unnecessary line in template docs

- samples/index.html
- samples/toolbarconfigurator/index.html
Typo
1. Open `samples/index.html`.
1. See that "I found a bug" link points to the old tracker.
> Fixed issue tracker links in samples

- CHANGES.md
- plugins/tableselection/plugin.js
- tests/plugins/tableselection/keyboard.html
- tests/plugins/tableselection/keyboard.js
- tests/plugins/tableselection/manual/enterkey.html
- tests/plugins/tableselection/manual/enterkey.md
Bug fix, fixes #415.
It seems that Firefox treat <kbd>Enter</kbd> as the key that doesn't produce any character, so  `keyPressEvent.charCode` property is set to `0`. Explicitly checking if the <kbd>Enter</kbd> key is pressed seems to do the trick.
> Enter modifies only first cell 

- CHANGES.md
- gruntfile.js
- plugins/enterkey/plugin.js
- tests/plugins/enterkey/enterkey.js
- tests/plugins/enterkey/manual/noselection.html
- tests/plugins/enterkey/manual/noselection.md
http://dev.ckeditor.com/ticket/16874
---
Closes #478
> Prevent of throwing an error when is no selection.

- CHANGES.md
- plugins/tableselection/plugin.js
- tests/plugins/tableselection/_helpers/tableselection.js
- tests/plugins/tableselection/manual/nestedtablescroll.html
- tests/plugins/tableselection/manual/nestedtablescroll.md
- tests/plugins/tableselection/tableselection.html
- tests/plugins/tableselection/tableselection.js
Issue was caused by the fact that mouse handler is fired also on `mousemove` and scrolling selects cell outside the nested table. Simple check if the newly selected cell is still inside the original table should do the trick.
Closes #493.
> #17052 Error on scroll while selecting nested table

- tests/plugins/balloonpanel/positioning.inline.js
Bug fix
No. PR correct existing tests.
Prevent of running test on mobile Safari.
Mobile safari do not allow on scrolling content of iframes. That's why unit test related to balloonpanell are not pass.
Situation is reported [here](https://bugs.webkit.org/show_bug.cgi?id=172854).
Close #441
> Update ballonpanel test condition to not run on iOS Safari.

- CHANGES.md
- core/editor.js
- core/tools.js
- tests/core/editor/keystrokehandler.js
- tests/core/tools/object.js
Bug fix
unit tests only
- add new helper `CKEDITOR.tools.object.findKey()`
- fix `getCommandKeystroke` to return proper keystrokes
Close #523
> Fix for getCommandKeystroke

- CHANGES.md
- plugins/pastefromword/filter/default.js
- tests/plugins/pastefromword/manual/unorderedlist.html
- tests/plugins/pastefromword/manual/unorderedlist.md
Bug fix
I did not add any unit tests as the change is covered by existing PFW unit tests.
Replaced `JSON.stringify` call with Quirks-supported `CKEDITOR.tools.isEmpty` in PFW.
Closes #534.
> Removed JSON.stringify call so that PFW works in QM

- tests/plugins/enterkey/manual/noselection.md
task
no. There is no such need.
add missing tags to manual test: `tests/plugins/enterkey/manual/noselection`
close #539
> Adding missing tags in manual tests

- plugins/tableselection/plugin.js
Bug fix
this.path ends with a slash so the final path to tableselection.css contains a double slash. This can prevent the stylesheet from being loaded in some cases (e.g. when it is loaded from within a WebJar and not directly from the file system). Other plugins that use this.path (see a11yhelp, find, image2, link, liststyle, magicline, specialchar, table) don't prefix the path fragments appended to this.path with a slash.
> Remove double slash from tableselection.css path

- CHANGES.md
- plugins/selectall/plugin.js
- tests/plugins/selectall/manual/selectall.html
- tests/plugins/selectall/manual/selectall.md
- tests/plugins/selectall/selectall.js
Bug fix
`selectall` plugin test already exists.
selectall plugin is now checking if `createTextRange` method exists in IE.
Closes #545
> Check if document.createTextRange exists for IE in 'select all' plugin.

- CHANGES.md
- plugins/clipboard/plugin.js
- plugins/notification/plugin.js
- tests/plugins/notification/layout.js
- tests/plugins/notification/manual/notoolbarnotifications.html
- tests/plugins/notification/manual/notoolbarnotifications.md
- tests/plugins/notification/manual/notoolbarnotificationsinline.html
- tests/plugins/notification/manual/notoolbarnotificationsinline.md
- tests/plugins/notification/notoolbarlayout.js
bug fix
I hope so :)
* Made update to notification to skip section related to toolbar position, if toolbar position doesn't exists.
* Made some small changes in unit test to include toolbar in tests.
* Add few new unit test to test cases of editor without toolbar
* Add dependancy to clipboard plugin to use toolbar. It appears that earlier clipboard base on dependancy included in notification.
close #491
> Remove dependancy between toolbar and notification plugin

- CHANGES.md
- plugins/link/plugin.js
- tests/plugins/link/anchor.js
- tests/plugins/link/link.js
- tests/plugins/link/manual/anchordialog.html
- tests/plugins/link/manual/anchordialog.md
Bug fix
Yes
Add a new condition to element variable on double-click.
Closes #501
> T/501 Allow opening dialog for an empty anchor

- CHANGES.md
- plugins/stylescombo/plugin.js
- tests/plugins/stylescombo/manual/stylewithnoselection.html
- tests/plugins/stylescombo/manual/stylewithnoselection.md
- tests/plugins/stylescombo/stylescombo.js
bug fix
yes
- In case when style combo is opened and there is no selection in editor, now editable element will be returned as default one.
close #646
> Bug fix for throwing error in console where style combo was open

- CHANGES.md
- plugins/tableselection/plugin.js
- plugins/tableselection/styles/tableselection.css
- tests/plugins/table/fakeselectionadvancetab.js
- tests/plugins/table/manual/fakeselectionadvancetab.html
- tests/plugins/table/manual/fakeselectionadvancetab.md
- tests/plugins/tableselection/integrations/core/getextractselectedhtml.html
Bug fix
yes
Move classes to dataset attributes
close #579
> Fix for remaining fake selection in advance tab of table properties

- CHANGES.md
- core/dom/range.js
- tests/core/dom/range/clonecontents.js
- tests/core/dom/range/manual/clonecontentsstartnodeproblem.html
- tests/core/dom/range/manual/clonecontentsstartnodeproblem.md
bug fix
yep!
Modify `if` statement to accept situation when selection start and ends in this same element, but `startNode` has type of `element` where `endNode` has type of `text`
close #426
> `cloneContents` properly return document fragment

- CHANGES.md
- core/dom/range.js
- tests/core/dom/range/extractcontents.html
- tests/core/dom/range/extractcontents.js
- tests/core/dom/range/manual/extractcontentsreturnproperstructure.html
- tests/core/dom/range/manual/extractcontentsreturnproperstructure.md
Bug fix
yes
- pass flag `toStart` to append method in extract mode
- fix test which was wrongly design and accept previously wrong code
close #644
> Fix for `range.extractContents` to work like `cloneContents`

- CHANGES.md
- core/dom/elementpath.js
- tests/core/dom/elementpath/elementpath.html
- tests/core/dom/elementpath/elementpath.js
Bug fix
Fixes a simple bug in `elementPath.contains()` method.
Closes #684.
> Fixed elementPath.contains when fromTop is set to true.

- dev/builder/build.sh
Task
None needed, a bash script change.
The main reason for this PR is to fix #572, so that we no longer need to remember about updating some magic strings after each release.
With that I had to update some [vague bash operations](https://github.com/ckeditor/ckeditor-dev/blob/aa600bd52a147e2ac1afd726ca6bf8c32ec7437e/dev/builder/build.sh#L64-L72) including regexp tricks. Since we operate on semver compliant version in package.json we no longer need this checking, and we can simplify the check.
Closes #572.
> Automatically pick CKEditor version in bash build script

- tests/core/focusmanager/lostfocus.html
- tests/core/focusmanager/lostfocus.js
Added unit test for loosing focus in divarea editor. Problem exist in **4.6.2**.
It seems that change introduced in 13446 843720475bc05426f2c147e79f04d4cda1091dce break divarea editor.
Unit test require to have focus in view port of the browser.
> [#17020] Unit test for loosing focus in divarea editor

- CHANGES.md
- core/dom/nodelist.js
- tests/core/dom/nodeList.html
- tests/core/dom/nodeList.js
Task
Simply added new `CKEDITOR.dom.nodeList#toArray` method.
Closes #751.
> Introduced CKEDITOR.dom.nodeList#toArray method

- core/selection.js
- plugins/tableselection/plugin.js
- plugins/tabletools/plugin.js
- tests/plugins/tableselection/_helpers/tableselection.js
- tests/plugins/tableselection/integrations/clipboard/pastemerge.html
- tests/plugins/tableselection/integrations/clipboard/pastemerge.js
- tests/plugins/tableselection/integrations/tabletools/tabletools.js
- tests/plugins/tabletools/tabletools.html
- tests/plugins/tabletools/tabletools.js
Bug fix
Since paste listener was huge, and very difficult to understand I had to split the logic into smaller pieces, so that it's easier to work with it.
The biggest change is encapsulated `TableSelection` type in tableselection plugin, so that there's no `firstCell`, `lastRow` etc reassigning all over the place. Instead new types take care of that. It also features methods related to the manipulation on the table selection itself.
Also `insertRow` and `insertColumn` in tabletools now returns added DOM elements.
> Corrections to table selection pasting improvements PR

- CHANGES.md
- plugins/widget/plugin.js
- tests/tickets/gh663/manual/1.html
- tests/tickets/gh663/manual/1.md
Bug fix
I added check if `element` in widget plugin is` CKEDITOR.dom.element`
Closes #663
> check if element is dom.element

- tests/core/htmldataprocessor.js
Bug fix
PR corrects test.
PR updates `if` statement, in a way to not execute one test on IE11. IE11 started to behave like Edge in this test case, so in this same way should now be ignored.
Close #742
> Ignore test on IE11 which start to display prompt in it

- tests/plugins/notification/manual/notoolbarnotifications.html
- tests/plugins/notification/manual/notoolbarnotificationsinline.html
Task
This is a fix in the manual test itself.
Just a small change making sure that no toolbar plugin is loaded in tests:
* http://tests.ckeditor.dev:1030/tests/plugins/notification/manual/notoolbarnotifications
* http://tests.ckeditor.dev:1030/tests/plugins/notification/manual/notoolbarnotificationsinline
Without this it would load toolbar plugins on a built version of CKEditor.
> Force toolbar plugin not to be loaded in notoolbarnotifications manual tests

- plugins/tableselection/plugin.js
This can be seen in case 2 of manual test tests/plugins/tableselection/manual/integrations/image2/paste.
Bug fix
A change to make `/tests/plugins/tableselection/manual/integrations/image2/paste` test pass.
> Fix for selection after pasting a non table content

- CHANGES.md
- plugins/image2/plugin.js
- tests/plugins/image2/manual/resizerwithreadonly.html
- tests/plugins/image2/manual/resizerwithreadonly.md
- tests/plugins/image2/resizerwithreadonly.js
Bug fix
Yes
A new condition has been added to prevent initializing resizer.
---
Closes #719
> T/719 Image could be resized in read-only mode

- core/selection.js
- tests/core/selection/selection.js
- tests/plugins/tableselection/integrations/core/selection.js
Task
I've added `selection.isCollapsed` method with appropriate unit tests.
closes #800.
> Added selection.isCollapsed method

- CHANGES.md
- plugins/tabletools/plugin.js
- tests/plugins/tableselection/integrations/tabletools/columndeletion.html
- tests/plugins/tableselection/integrations/tabletools/columndeletion.js
- tests/plugins/tableselection/manual/integrations/tabletools/columndeletionerror.html
- tests/plugins/tableselection/manual/integrations/tabletools/columndeletionerror.md
- tests/plugins/tabletools/columndeletion.html
- tests/plugins/tabletools/columndeletion.js
- tests/plugins/tabletools/manual/columndeletionerror.html
- tests/plugins/tabletools/manual/columndeletionerror.md
bug fix
yes
- fix bug which forbid to delete columns when those were under colspans.
- fix bug where only last column was removed when colspan cell was selected.
- fix bug where cursor position might won't be returned, what generat the console error.
- add some brackets `{}` to if statements.
close #577
> Fix error which appear with `columnDelete` command when table contained colspans

- CHANGES.md
- plugins/dialog/plugin.js
- tests/plugins/dialog/manual/opennonfirsttabasdefault.html
- tests/plugins/dialog/manual/opennonfirsttabasdefault.md
- tests/plugins/dialog/plugin.js
task request
yes
- provide possibility to define tab which should be open as default one after loading dialog.
- `tests/plugins/dialog/plugin.js` can seems to have a lot of changes. I've wrapped entire test suite with IIFE and add `'use strict;'`. That's why there was added extra tabs in entire file. 
Close #830
> [#830] Add possibility to define default tab in dialog

- CHANGES.md
- core/tools.js
- tests/core/tools.js
- tests/core/tools/keystroke.js
New feature
Added missing method. Actually it uses pretty much original `keystrokeToString` implementation, without joining the array members at the end.
I have also extracted the unit tests into a separate file.
Closes #856.
> Introduced CKEDITOR.tools.keystrokeToArray

- CHANGES.md
- plugins/save/plugin.js
- tests/plugins/save/manual/sourcemode.html
- tests/plugins/save/manual/sourcemode.md
- tests/plugins/save/save.html
- tests/plugins/save/save.js
bug fix
Added support for save button is source mode
closes #817
> save support in source mode

- CHANGES.md
- plugins/forms/dialogs/radio.js
- tests/plugins/forms/manual/ieradiofix.html
- tests/plugins/forms/manual/ieradiofix.md
- tests/plugins/forms/radio.js
Bug fix
- include little hack designed for IE to properly check radio buttons, when those are added to editor.
Close #834
> [#834] Fix radio button selection problem when used in IE browser.

- plugins/wysiwygarea/plugin.js
- tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.html
- tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.md
- tests/plugins/widget/integration/wysiwygarea/superflousdoesntremovedivwrapper.js
- tests/plugins/wysiwygarea/superfluouselement.js
Bug fix
yes
* Modify condition which remove unnecessary `div` in Edge.
* Modify condition to work only in Edge up to 14.xxx. (Edge 15 doesn't add `div`).
* Modify tests to respect new condition related to Edge version.
Close #704
> [#704] Fix broken widget after using Ctrl+Z in Edge

- CHANGES.md
- plugins/tableselection/plugin.js
- plugins/tabletools/plugin.js
- tests/plugins/tableselection/integrations/tabletools/tabletools.html
- tests/plugins/tableselection/integrations/tabletools/tabletools.js
- tests/plugins/tabletools/manual/insertcolumnverticalsplit.html
- tests/plugins/tabletools/manual/insertcolumnverticalsplit.md
- tests/plugins/tabletools/tabletools.html
- tests/plugins/tabletools/tabletools.js
> T/13729 Table: Insert Column before and After fails if a cell vertical split exist

- CHANGES.md
- core/editable.js
- tests/core/editable/getextracthtmlfromrange.js
- tests/plugins/tableselection/integrations/core/getextractselectedhtml.html
- tests/plugins/tableselection/integrations/core/getextractselectedhtml.js
- tests/plugins/tableselection/manual/integrations/clipboard/nestedtablecut.html
- tests/plugins/tableselection/manual/integrations/clipboard/nestedtablecut.md
Bug fix
I've introduced additional check to `editable.extractHtmlFromRange` to detect if selected cells are located inside nested table.
closes #787.
> Cutting from nested table

- CHANGES.md
- dev/builder/build.sh
New feature
now build.sh script use only bash tools to get version from package.json
closes #815
> removed nodejs dependency in build.sh script

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/dnd.js
- tests/plugins/widget/manual/dragwidget.html
- tests/plugins/widget/manual/dragwidget.md
- tests/plugins/widget/undo.js
Bug fix
Yes
Allowing to drag widget only on left mouse button by detecting pressed button.
---
Closes: #711 
Blocked by #810
> T/711 Allow to drag widget only with left mouse button

- plugins/easyimage/styles/easyimage.css
Styling easyimage.
Not required.
1. Hover state:
2. Focus state:
3. Selected:
4. Figcaption focused. There is a visible gap between image and figcaption because image is wrapped by image resizer. This gap should be fixed after disabling image resize.
> Styling easyimage

- core/tools.js
- tests/core/tools.js
New feature
- Add tools for converting hexstrings to base64.
Required by #662
> Hexstring converter to base64

- CHANGES.md
- plugins/stylescombo/plugin.js
- tests/plugins/stylescombo/manual/squarebulletedlist.html
- tests/plugins/stylescombo/manual/squarebulletedlist.md
- tests/plugins/stylescombo/stylescombo.js
Bug fix
- Change styles combo to analyse `startElement` of selection if `selectedElement` return null. This will preserve functionality which was in editor before regression.
Close #862
> [#862] Fix for square bulleted list bug

- core/focusmanager.js
> Fix typo in inline code snippet

- CHANGES.md
- plugins/tabletools/dialogs/tableCell.js
- tests/plugins/tabletools/cellproperties.html
- tests/plugins/tabletools/cellproperties.js
- tests/plugins/tabletools/manual/cellproperties.html
- tests/plugins/tabletools/manual/cellproperties.md
> Cannot set cell width or height because inline styles are stripped

- CHANGES.md
- core/tools.js
- tests/_benderjs/ckeditor/static/extensions.js
- tests/core/tools/object.js
- tests/plugins/copyformatting/_helpers/tools.js
New feature
Introduce `CKEDITOR.tools.object.merge`, which merges two objects.
Closes #1053.
> #1053 Introduce CKEDITOR.tools.object.merge

- plugins/cloudservices/plugin.js
- tests/plugins/cloudservices/unit.js
New feature
Reuses logic proposed in #1052, but extracts [Code Services](https://ckeditor.com/ckeditor-cloud-services) handing into a separate type.
So far it's only a loader type, integration with the [UploadRepository](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.fileTools.uploadRepository) or UploadWidget will be added in a followup PR.
> Cloud Services file loader

- plugins/filetools/plugin.js
- plugins/uploadwidget/plugin.js
- tests/plugins/filetools/filetools.js
- tests/plugins/uploadwidget/uploadwidget.js
Allow to use custom fileLoader in uploadRepository.create and upload widget
New feature
* A new argument in [`uploadRepository.create`](http://docs.ckeditor.test/#!/api/CKEDITOR.fileTools.uploadRepository-method-create) allowing to use custom loader type.
* Added `loaderType` property in the [`CKEDITOR.fileTools.uploadWidgetDefinition`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.fileTools.uploadWidgetDefinition).
Now that we have more than one loaders (Cloud Services loader has been added in recent PR), we need a way to customize loader used by a given feature.
That way we'll be able to easily change where widgets are uploaded, etc.
> Allow to use custom fileLoader in uploadRepository.create and upload widget

- CHANGES.md
- core/tools.js
- tests/core/tools/array.js
task
- new tool method for arrays
close #1073
> New tool method for array "every"

- plugins/easyimage/plugin.js
- plugins/easyimage/samples/easyimage.html
- tests/plugins/easyimage/uploadwidget.js
- tests/plugins/uploadfile/_helpers/waitForImage.js
Other, refactoring of other PR.
This PR adds some fixes to #1052, the general idea was to simplify it and extract cloud-service (backend) stuff to a separate plugin.
There were already quite a few changes, many of which has been already fixed in #1062 and #1066.
Summary for this PR:
* [`uploadUrl`](https://github.com/ckeditor/ckeditor-dev/blob/de017b395220ebaba8136ef7650d54dd035b5411/plugins/easyima …
> Easy image upload refactoring

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/definition.js
- tests/plugins/widget/widgetapi.js
Bug fix
I've introduced `multipleUpcastsHandler`, which fires appropriate upcast method for appropriate elements.
Closes #1094
> #1094 Upcast method invoked only for specified element

- tests/_benderjs/ckeditor/static/tools.js
- tests/core/htmldataprocessor.js
Fixing failing test `/tests/core/htmldataprocessor`
A new version of Chrome 62 does not remove preceding spaces in attributes. I modified a condition a little.
---
Closes #1070
> T/1070 Failing test /tests/core/htmldataprocessor on Chrome 62+

- plugins/elementspath/plugin.js
- tests/plugins/elementspath/manual/elementspath.html
- tests/plugins/elementspath/manual/elementspath.md
Bug fix
PR fix tests
- change in elementspath plugin to use `evt.data.path` instead of `editor.elementPath()`
Close #801
> [#801] Fix elementspath plugin to work properly with Firefox 55+

- plugins/inlinetoolbar/samples/inlinetoolbar.html
- plugins/inlinetoolbar/samples/js/sample.js
Refreshed description of inline toolbar sample file in `plugins/inlinetoolbar/samples/`.
> Update sample for inline toolbar

- CHANGES.md
- plugins/balloonpanel/plugin.js
- tests/plugins/balloonpanel/balloonpanel.js
New feature
Balloon panel still support old API in `attach` method but now We are able to give options param:
```
{
focusElement: CKEDITOR.dom.element/Boolean
show: Boolean
}
```
Thanks to this we can attach balloon panel without showing it.
Closes #1118
> Balloon panel API change

- plugins/easyimage/plugin.js
- plugins/imagebase/lang/en.js
- plugins/imagebase/plugin.js
- tests/plugins/easyimage/config.html
- tests/plugins/easyimage/config.js
- tests/plugins/easyimage/manual/figuresnoclass.html
- tests/plugins/easyimage/manual/figuresnoclass.md
- tests/plugins/easyimage/widget.html
- tests/plugins/easyimage/widget.js
- tests/plugins/imagebase/imagebase.html
- tests/plugins/imagebase/imagebase.js
New feature
_coming soon_
I've introduced new plugin, `imagebase`, which creates new image widget. This plugin could be used as a base for both `image2` and `easyimage` plugins.
Currently the implementation is very basic and it does not do much beyond just displaying image.
> New widget for Easy Image

- plugins/cloudservices/plugin.js
- plugins/easyimage/plugin.js
- plugins/easyimage/samples/easyimage.html
- plugins/filetools/plugin.js
- plugins/uploadwidget/plugin.js
- tests/plugins/cloudservices/unit.js
- tests/plugins/easyimage/tools.js
- tests/plugins/easyimage/uploadwidget.js
- tests/plugins/easyimage/widget.html
- tests/plugins/easyimage/widget.js
- tests/plugins/filetools/filetools.js
- tests/plugins/uploadfile/_helpers/waitForImage.js
- tests/plugins/uploadwidget/uploadwidget.js
New feature
I've introduced upload widget for easy image, based on existing `uploadimage` widget.
Currently information about easy image is passed as additional request parameters to `fileUploadRequest` and `fileLoader`'s property to `fileUploadResponse`. Additionally there is some code duplication between `uploadimage` and current widget (especially whole handling of pasting images, which is just …
> Upload widget for Easy Image

- plugins/inlinetoolbar/plugin.js
- plugins/inlinetoolbar/skins/kama/inlinetoolbar.css
- plugins/inlinetoolbar/skins/moono-lisa/inlinetoolbar.css
- plugins/inlinetoolbar/skins/moono/inlinetoolbar.css
- tests/plugins/inlinetoolbar/buttons.js
- tests/plugins/inlinetoolbar/manual/kama.html
- tests/plugins/inlinetoolbar/manual/moono-lisa.html
- tests/plugins/inlinetoolbar/manual/moono.html
- tests/plugins/inlinetoolbar/view.js
Automatic wrapping buttons to groups in inline toolbar
I added wrapping buttons in to groups. Manual tests for skins are updated and CSS files are updated.
> Button group wrapping in inline tootlbar

- CHANGES.md
- plugins/uploadwidget/plugin.js
- tests/plugins/uploadwidget/manual/skipnotification.html
- tests/plugins/uploadwidget/manual/skipnotification.md
- tests/plugins/uploadwidget/uploadwidget.js
New feature (and a Bug fix for related issue)
To keep backward compatibility `skipNotifications` is set to `false` by default.
At the same time making a manual test required me to fix a related issue (#1068) otherwise I could not use `editor#widgetDefinition` event to make my changes.
Closes #1145, #1068.
> Added skipNotifications option to upload widget definition

- plugins/easyimage/plugin.js
- plugins/imagebase/plugin.js
- tests/plugins/easyimage/widget.js
- tests/plugins/imagebase/features/api.js
- tests/plugins/imagebase/features/link.html
- tests/plugins/imagebase/features/link.js
- tests/plugins/imagebase/features/manual/link.html
- tests/plugins/imagebase/features/manual/link.md
- tests/plugins/imagebase/imagebase.html
New feature
I've created new API for adding new features to new image widgets. Currently it's used only to add link feature to `easyimage` plugin.
The API is based on one new method in `CKEDITOR.plugins.imagebase`:
```javascript
addFeature( editor: CKEDITOR.editor, featureName: String, widgetDefinition: WidgetDefinition );
```
Every feature extends …
> Link feature for imagebase

- plugins/easyimage/plugin.js
- plugins/easyimage/styles/easyimage.css
- plugins/uploadwidget/plugin.js
- tests/plugins/easyimage/manual/progressbar.html
- tests/plugins/easyimage/manual/progressbar.md
- tests/plugins/easyimage/uploadwidget.js
- tests/plugins/uploadwidget/manual/_helpers/xhr.js
- tests/plugins/uploadwidget/uploadwidget.js
New feature
This pull requests adds a fancy progress bar to Easy Image widget:
Note that it also registers `uploadWidgetDefinition.skipNotification` which was added in #1145, but it's not in the base of current Easy Image feature branch, thus standard notification will remain in _most cases_.
> Upload progress bar for Easy Image

- tests/plugins/indent/indent.js
- tests/plugins/list/list.js
Other: fixing tests failing on newest Edge (version 16). Closes #945.
Tests are not needed as this PR is fixing tests only.
As stated in #945, the browser behaviour seems quite random. The troublesome test when executed alone or as a first test works fine.  I also tried to check which preceding test may affect it, commenting out one after another. I found a few which when enabled causes the …
> Fix unit test failing in Edge 16

- plugins/inlinetoolbar/plugin.js
- tests/plugins/inlinetoolbar/context/integration.js
Bug fix
Skipped manual tests, as it's more of an API change, which is well covered by the unit tests.
Simply check if the button was created before adding it.
> Inline Toolbar Context should not throw exception if provided with an invalid button name

- plugins/inlinetoolbar/plugin.js
- tests/plugins/inlinetoolbar/context.js
- tests/plugins/inlinetoolbar/context/_helpers/tools.js
- tests/plugins/inlinetoolbar/context/cssselector.js
- tests/plugins/inlinetoolbar/context/elements.js
- tests/plugins/inlinetoolbar/context/integration.html
- tests/plugins/inlinetoolbar/context/integration.js
- tests/plugins/inlinetoolbar/context/manager.js
- tests/plugins/inlinetoolbar/context/manual/complex.html
- tests/plugins/inlinetoolbar/context/manual/complex.md
- tests/plugins/inlinetoolbar/context/manual/context.html
- tests/plugins/inlinetoolbar/context/manual/context.md
- tests/plugins/inlinetoolbar/context/manual/toolbar.html
- tests/plugins/inlinetoolbar/context/manual/toolbar.md
- tests/plugins/inlinetoolbar/context/manual/widget.html
- tests/plugins/inlinetoolbar/context/manual/widget.md
- tests/plugins/inlinetoolbar/context/priorities.html
- tests/plugins/inlinetoolbar/context/priorities.js
- tests/plugins/inlinetoolbar/context/refresh.js
- tests/plugins/inlinetoolbar/context/widget.html
- tests/plugins/inlinetoolbar/context/widget.js
New feature
Added context classes for inline toolbar. It makes stupid easy to maintain multiple inline toolbars in a single editor.
See [`CKEDITOR.editor.inlineToolbar` (local docs link)](http://docs.ckeditor.test/#!/api/CKEDITOR.editor.inlineToolbar) for more details.
> Inline toolbar context feature

- plugins/inlinetoolbar/plugin.js
- tests/plugins/inlinetoolbar/manual/drag.html
- tests/plugins/inlinetoolbar/manual/drag.md
Bug fix
Added HTML `draggable="false"` flag to all elements inside inline toolbar.
> Disable drag function in inline toolbar elements

- CHANGES.md
- plugins/uploadimage/plugin.js
- tests/plugins/uploadimage/uploadimage.js
Bug fix
This issue is more of a workaround, as the problem is actually on a CKFinder side, but we can't quickly fix it there, so we'll patch client side first.
Now, the problem was that CKFinder had a problem handling multiple files with the same name loaded at once, so we'll generate unique file name for each one. It's a bit dirty, and optimistic, but should do the trick for now.
To be honest I had no good idea how to make a good manual test here. To make it reliable I have set a CKFinder 3 instance on my dev workstation, and added configuration to `config.js`:
By adding:
```
config.uploadUrl = '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json';
```
And adding `'uploadimage'` to the plugin list.
Closes #1213.
> Fix for race condition while uploading multiple files with uploadimage plugin

- plugins/pastefromword/filter/default.js
- plugins/pastefromword/plugin.js
- tests/plugins/pastefromword/helpers.js
Other, review corrections
In this PR I have added fixes for all of my review suggestions gave to #1214.
Please review them, and merge to your branch if you're good with it.
Then set #1214 back to a review and I think we're done 🙂
> Review corrections to Paste From Word Image merge task

- plugins/balloontoolbar/plugin.js
- tests/plugins/balloontoolbar/context.js
- tests/plugins/balloontoolbar/context/cssselector.js
- tests/plugins/balloontoolbar/context/integration.js
- tests/plugins/balloontoolbar/context/manager.js
- tests/plugins/balloontoolbar/context/manual/complex.html
- tests/plugins/balloontoolbar/context/manual/context.html
- tests/plugins/balloontoolbar/context/manual/toolbar.html
- tests/plugins/balloontoolbar/context/manual/widget.html
- tests/plugins/balloontoolbar/context/priorities.js
- tests/plugins/balloontoolbar/context/refresh.js
- tests/plugins/balloontoolbar/context/widget.js
Task: API refactoring
Closes #1237.
> Move creation API to the editor directly

- plugins/balloontoolbar/plugin.js
- tests/plugins/balloontoolbar/positioning.js
New feature
The toolbar should prefer bottom position. Reason for that is that on mobile, native context menu (e.g. in case of a ranged selection) is displayed on top (mobile chrome, ios safari, chrome on Windows).
Having our toolbar on the bottom of selection will allow user to use native and our toolbar as well.
> Balloon Toolbar should prefer bottom position

- tests/plugins/balloonpanel/cssloading.js
Failing test fix.
This PR fixes failing test, so no additional tests are needed
Ignores failing `balloonpanel/cssloading` test only for built version of CKEditor.
Closes #1251.
> Ignore balloonpanel/cssloading test on built version

- plugins/clipboard/plugin.js
- tests/plugins/clipboard/fallbackdatatransfer.js
Other, PR corrections
Corrections to #1233 PR.
Some docs adjustments, most notably `_stripHtml`. I felt like it's initial docs were not precise enough (I felt like it might remove just meta tags, which is not only the case). Actually I made a good use of inline comments within the function. :)
It also introduced `_dataTransfer` property to fallbackDataTransfer.
With my PR I have caught another small edge case that would fail.
See "test getData with getNative with custom type other sequence" in `tests/plugins/clipboard/fallbackdatatransfer.js`.
> Corrections to PR fixing asynchronous clipboard return value

- tests/plugins/balloontoolbar/cssloading.js
Bug fix
Without this fix the test will try to load moono-lisa skin.
Similar to #1251.
> Corrected Balloon Toolbar CSS loading unit test for a built version of CKEditor

- plugins/balloontoolbar/plugin.js
- tests/plugins/balloontoolbar/manual/windowresize.html
- tests/plugins/balloontoolbar/manual/windowresize.md
- tests/plugins/balloontoolbar/view.js
Bug fix
Balloon toolbar is now repositioned on window resize.
> Balloon toolbar should be repositioned on window resize

- CHANGES.md
- config.js
- dev/builder/build-config.js
- plugins/uploadimage/plugin.js
- tests/plugins/uploadimage/manual/configerror.md
- tests/plugins/uploadimage/uploadimage.js
Task
After this change `uploadimage` plugin does not throw error anymore, it silently returns.
Closes #1249.
> Enable Upload Iamge plugin and prevent logging error in case of missing configuration

- plugins/balloontoolbar/skins/default.css
- plugins/balloontoolbar/skins/kama/balloontoolbar.css
- plugins/balloontoolbar/skins/moono-lisa/balloontoolbar.css
- plugins/balloontoolbar/skins/moono/balloontoolbar.css
- tests/plugins/balloontoolbar/manual/kama.html
- tests/plugins/balloontoolbar/manual/moono.html
Task
Decreased balloon toolbar paddings (-2px). Default CSS already has 3px paddings.
> Decreased balloon toolbar paddings

- plugins/clipboard/plugin.js
Typo fix
While removing `_cache` property, we missed two references in API docs.
Without this change following warnings were logged during building docs:
```
Warning: /mnt/c/Development/htdocs/ckSource/ckeditor-dev/plugins/clipboard/plugin.js:2826: {@link #_cache} links to non-existing member
Warning: /mnt/c/Development/htdocs/ckSource/ckeditor-dev/plugins/clipboard/plugin.js:2842: {@link #_cache} links to non-existing member
```
This PR fixes this issue.
> Corrected outdated property references in the clipboard plugin docs

- tests/plugins/balloonpanel/_helpers/tools.js
- tests/plugins/balloonpanel/cssloading.js
- tests/plugins/balloontoolbar/cssloading.js
> Fix failing tests due to lack of 'document.location.origin'

- tests/plugins/balloontoolbar/view.js
Bug fix
Reason was very simple, IE8 returns HTML tags uppercased. It's preferred to use `assert.beautified.html` for HTML comparing.
Closes #1200.
> Fixed failing Balloon Toolbar test on IE8

- tests/plugins/balloontoolbar/_helpers/default.js
- tests/plugins/balloontoolbar/buttons.js
- tests/plugins/balloontoolbar/context.js
- tests/plugins/balloontoolbar/cssdefault.js
- tests/plugins/balloontoolbar/cssloading.js
- tests/plugins/balloontoolbar/cssskin.js
- tests/plugins/balloontoolbar/loading.js
- tests/plugins/balloontoolbar/manual/balloontoolbar.html
- tests/plugins/balloontoolbar/manual/drag.html
- tests/plugins/balloontoolbar/manual/fallbackstyles.html
- tests/plugins/balloontoolbar/manual/focus.html
- tests/plugins/balloontoolbar/manual/kama.html
- tests/plugins/balloontoolbar/manual/moono-lisa.html
- tests/plugins/balloontoolbar/manual/moono.html
- tests/plugins/balloontoolbar/manual/skinpath.html
- tests/plugins/balloontoolbar/positioning.js
- tests/plugins/balloontoolbar/view.js
Other, please explain:
Test update
- add ignore option in manual test for balloon toolbar
> Ignore manual tests related to balloon toolbar on old IE browsers.

- tests/plugins/balloontoolbar/positioning.js
Fix for failing tests
Added ignore for two failing tests, see https://github.com/ckeditor/ckeditor-dev/issues/1295#issuecomment-348498506 for details.
> Ignore two unstable tests for balloontoolbar

- plugins/widget/plugin.js
Bug fix
- prevent of running widget if `querrySelectorAll` is unavaialble
close #1319
> Prevent of loading widgets if querrySelectorAll is undefiend

- CHANGES.md
- plugins/link/plugin.js
- tests/plugins/link/link.js
- tests/plugins/link/manual/getselectedlink.html
- tests/plugins/link/manual/getselectedlink.md
Bug fix
Fix double click on anchor with image and text.
closes #859
> CKEDITOR.plugins.link.getSelectedLink does not fetch all links

- CHANGES.md
- plugins/clipboard/plugin.js
- plugins/pastefromword/plugin.js
- plugins/pastetext/plugin.js
- tests/plugins/clipboard/forcepasteasplaintext.js
- tests/plugins/clipboard/manual/forcepasteasplaintext.html
- tests/plugins/clipboard/manual/forcepasteasplaintext.md
Bug fix
Closes #1013.
There is one related issue #1328 which describes/covers some inconsistent paste behaviours.
> forcePasteAsPlainText adjusted to work with Paste from Word

- CHANGES.md
- plugins/balloontoolbar/plugin.js
- tests/plugins/balloontoolbar/context/focusablebuttons.js
- tests/plugins/balloontoolbar/context/manual/focusablebuttons.html
- tests/plugins/balloontoolbar/context/manual/focusablebuttons.md
Bug fix
yes
- Currently when balloon toolbar will be created then all added items will be registered in focus manager
- There is added additional array which store reference to elements which was registered is focus manager.
close #1232
> Balloon toolbar now register its items in focusmanager

- CHANGES.md
- plugins/dialogui/plugin.js
- plugins/filebrowser/plugin.js
- plugins/filetools/plugin.js
- tests/plugins/filebrowser/manual/uploadxhr.html
- tests/plugins/filebrowser/manual/uploadxhr.md
- tests/plugins/filebrowser/manual/uploadxhrwitherror.html
- tests/plugins/filebrowser/manual/uploadxhrwitherror.md
- tests/plugins/filebrowser/uploadbutton.js
- tests/plugins/filetools/_helpers/tools.js
- tests/plugins/filetools/fileloader.js
- tests/plugins/filetools/static.js
New feature
- change way how filebrowser upload files - prefer using XHR
- allow on providing custom headers to XHR used when files are uploaded
- add config flag which will force to use `form submit` behaviour when files are uploaded
Closes #643.
> Use XHR as possible uploading mechanism in filebrowser plugin

- CHANGES.md
- plugins/balloontoolbar/plugin.js
- tests/plugins/balloontoolbar/context/cssselector.js
- tests/plugins/balloontoolbar/context/manual/imgselect.html
- tests/plugins/balloontoolbar/context/manual/imgselect.md
Bug fix
This PR fixes a case when fully selected element was not considered by [`contextDefinition.cssSelector`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.plugins.balloontoolbar.contextDefinition-property-cssSelector) matchers.
Reason for this is that selection is being shrinked at the beginning of execution, so that probed path for …
> Balloon toolbar cssSelector should also consider selected element (if any)

- plugins/easyimage/plugin.js
Pull Request corrections
(both tests wre developed in original PR, and are still valid)
This PR contains coorections to the #1382 PR.
There was one aspect that keept bugging me in the original solution: https://github.com/ckeditor/ckeditor-dev/pull/1382#discussion_r158825176
I took a look on it, and the solution was rather simple.
You see, so far in …
> Certain Easy Image commands should force selection check

- plugins/easyimage/plugin.js
- tests/plugins/easyimage/manual/_helpers/tools.js
- tests/plugins/easyimage/manual/imagestretch.html
- tests/plugins/easyimage/manual/imagestretch.md
- tests/plugins/easyimage/manual/upload.html
- tests/plugins/easyimage/uploadwidget.js
Bug fix
I've added `[width]` attribute with natural dimensions of the image to the widget, which prevents stretching image if it's too small to fit editor's width.
> Prevent image stretching in Easy Image

- plugins/imagebase/plugin.js
- tests/plugins/imagebase/features/link.js
Bug fix
I forced reset of link state from `null` to `undefined`.
> Fix exception thrown by removing link with data callback after

- CHANGES.md
- core/tools.js
- tests/core/tools/style.js
Bug fix
Added regex to remove whitespaces from color model syntax to CKEDITOR.tools.style.parse.border() function.
Closes #1356
#1356: Fixed: [Border shorthand converter](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.tools.style.parse-method-border) should allow on space in color.
> Fixed bug with parsing border colors

- CHANGES.md
- plugins/balloontoolbar/skins/kama/balloontoolbar.css
Fix issue if automated static file collection process the ballontoolbar.css and doesn't find sprites.png
No.
Correct path to image file. Same like https://github.com/ckeditor/ckeditor-dev/commit/65f487e20f4a73c8cc45d314b4dab856d1b1ecd5
Closes #1426.
> Set a relative path to images sprite for Kama skin in balloon toolbar

- plugins/easyimage/plugin.js
- tests/plugins/easyimage/manual/undo.html
- tests/plugins/easyimage/manual/undo.md
- tests/plugins/easyimage/uploadwidget.js
Bug fix
I've locked snapshots before modifying HTML (in `onUploaded` and in `update` handler of progressbar) and immediately unlocked them after modifying.
> Fix unnecessary undo steps

- CHANGES.md
- core/filter.js
- tests/core/filter/manual/bordershorthandtransformation.html
- tests/core/filter/manual/bordershorthandtransformation.md
- tests/core/filter/transformations.js
- tests/plugins/pastefromword/generated/_fixtures/Tickets/11477Table_in_word/word2013/expected_ie11.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/11529Table_OO/expected.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/11529Table_OO/word2013/expected_ie11.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/11950Test_Table/expected.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/12406Doc1/expected.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/12406Doc1/word2013/expected_firefox.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/12406Document1_(3)/expected.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/3039blog_test_2003_(2)/expected.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/3039blog_test_2003_(2)/word2013/expected_ie11.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/3959Test_doc_with_date/word2013/expected_ie11.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/4427test-document/word2013/expected_ie11.html
- tests/plugins/pastefromword/generated/_fixtures/Tickets/6449Sample/word2013/expected_ie11.html
Bug fix
- change filter transformation `splitBorderShorthand` to properly split the border style and use tools method instead of having own logic,
- there exist an issue with processing border color with space which is an upstream here: #1356 
close #1010
> Fix for processing border shorthand in filter transformation

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/clipboard.js
- tests/plugins/clipboard/manual/dontcopyemptyselection.html
- tests/plugins/clipboard/manual/dontcopyemptyselection.md
Bug fix
yes
- activate copying or cutting only when selection is non-collapsed
_**Note:** Because browse doesn't allow on free access to clipboard, there is no unit test which would simulate properly this case._
Close #869
> Fixing bug which cleared clipboard when collapsed selection was copied

- CHANGES.md
- plugins/widgetselection/plugin.js
- tests/plugins/widgetselection/keys.js
- tests/plugins/widgetselection/manual/specialcharacters.html
- tests/plugins/widgetselection/manual/specialcharacters.md
Bug fix
Used [CKEDITOR.dom.event.getKeystroke](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.dom.event-method-getKeystroke) function to define content selection by `cmd/ctrl+a` key combination.  
Closes #1419
#1419: Fixed: [Widged Selection](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.plugins.widgetselection) selects editor …
> Fixed `alt + a` key combination for editor content selection on Windows

- tests/plugins/easyimage/commands.js
Failing tests fix
This PR fixes tests, so no more tests.
I've mocked `CKEDITOR.dom.element.prototype.getClientRect` in IE and Edge. Additionally I've been forced to run every unit test in new editor's instance in Edge; otherwise browser crashed…
> Fix failing easyimage/commands.js tests in IE and Edge

- .jscsrc
Task
Appened to our `.jscsrc` following line:
`"requireLineFeedAtFileEnd": true`
Which does exactly what is says.
Closes #1461
> JSCS now requires line feed at file end

- CHANGES.md
- plugins/magicline/plugin.js
- tests/plugins/magicline/magicline.js
- tests/plugins/magicline/manual/lineattribute.html
- tests/plugins/magicline/manual/lineattribute.md
New feature
Added `data-cke-magic-line="1"` attribute to the [Magic Line](https://ckeditor.com/cke4/addon/magicline) line element. 
Closes #1441
> Added identifying attribute to the Magic Line plugin

- CHANGES.md
- plugins/filebrowser/plugin.js
New feature
- change if statement to have different default option for uploading files
- change docs to be coherent with current default options.
close: #1365
> Make XHR defualt option to upload a file

- CHANGES.md
- contents.css
- plugins/widget/plugin.js
- tests/plugins/widget/manual/outline.html
- tests/plugins/widget/manual/outline.md
Task
Changed Widget ( figure selector in our css ) border and border radius to none,
added outline with same value as border, but without radius.
Changed Widget and its editable hover and focus outline to 3px and changed colors to more contrasting.
Closes #1535
> Improving color contrast on Widget hover border

- plugins/easyimage/styles/easyimage.css
- tests/plugins/easyimage/manual/scrollbarchromebug.html
- tests/plugins/easyimage/manual/scrollbarchromebug.md
Bug fix
- correct styles which might generate [flickering error](https://bugs.chromium.org/p/chromium/issues/detail?id=803045) in Chrome
- bug fix only for classic editor to not break divarea and inline cases when `vw` will be calculated for entire page not for editor
close: #1550
> Bug's workaround for flickering scrollbar in chrome

- plugins/easyimage/plugin.js
- plugins/easyimage/styles/easyimage.css
- tests/plugins/easyimage/balloontoolbar.js
- tests/plugins/easyimage/commands.js
- tests/plugins/easyimage/config.html
- tests/plugins/easyimage/config.js
- tests/plugins/easyimage/customstyles.html
- tests/plugins/easyimage/customstyles.js
- tests/plugins/easyimage/manual/customgroups.html
- tests/plugins/easyimage/manual/customgroups.md
- tests/plugins/easyimage/manual/customstyles.html
- tests/plugins/easyimage/manual/customtoolbar.html
- tests/plugins/easyimage/widget.js
Review corrections
PR with corrections to #1518. The most important change is that it reuses `CKEDITOR.styleCommand`, and does not rely on widget data.
Unit tests had a really good coverage, and I didn't have to do much there worked fine with changed solution for the most part.
Below is a more detailed list of changes:
* It reuses …
> Corrections to Easy Image styles system

- tests/plugins/imagebase/features/link.js
Task
We decided to ignore those tests for now and take care of it as a follow up in 4.9.1.
Related to #1552.
> Ignore failing imagebase link tests on IE11

- dev/builder/build.sh
- dev/langtool/_common.sh
ckbuilder.jar and langtool.jar should be downloaded via HTTPS
Bug fix - Security
URL change only - no tests needed. 
Changed the default URLs for downloading ckbuilder.jar and langtool.jar to HTTPS to prevent tampering. This is important because build.sh and _common.sh download and execute those files with no verification. 
Closes #1591.
> Use HTTPS for CKBuilder and langtool jar download

- CHANGES.md
- core/selection.js
- tests/core/selection/fake.js
- tests/core/selection/manual/readonly.html
- tests/core/selection/manual/readonly.md
- tests/core/selection/selection.js
Bug fix.
Disabled deleting selection in a readonly mode for fake selection.
Closes #1516
> Fixed: fake selection allows for removing in a readonly mode

- plugins/button/plugin.js
- plugins/easyimage/plugin.js
- tests/plugins/easyimage/customstyleicons.js
- tests/plugins/easyimage/manual/customstyleicons.html
- tests/plugins/easyimage/manual/customstyleicons.md
Task
This PR integrates #1531 with #1518 adding a proper icon paths passing from easyimage styles config object to button constructor, so that icons are visible in easyimage balloon toolbar.
To work properly it needs both #1531 and #1518 merged (unit test passes as it checks if icons path are properly propagated, however manual test is integrational …
> Integrate button icons with easyimage styles

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/manual/readonly.html
- tests/plugins/widget/manual/readonly.md
- tests/plugins/widget/widgetsintegration.js
Bug fix.
Added condition to prevent deleting focused widget when cutting using `cmd/ctrl + x` keys in read only mode.
Closes #1570
> Disabled cutting widget in a readonly mode using cmd/ctrl + x keys

- tests/plugins/widgetselection/keys.js
- tests/plugins/widgetselection/manual/specialcharacters.html
Bug (testcase) fix 
- ignore tests on non-webkit browsers, as widgetselection only affects webkit browsers.
https://github.com/ckeditor/ckeditor-dev/blob/1e4ca706d26294e969e5048231f18bc5d39b7ff3/plugins/widgetselection/plugin.js#L16-L19
close: #1593 
task which introduced this test suit and issue: #1423
> Ignore widgetselection tests on non-webkit browsers.

- plugins/easyimage/plugin.js
- tests/plugins/easyimage/manual/browsersupport.html
- tests/plugins/easyimage/manual/browsersupport.md
Bug fix
Added `return false;` when IE<11 is detected inside `init` and `afterInit`, and added manual test.
Closes #1596
> Prevented EasyImage from initializing on IE10 and lower

- plugins/easyimage/styles/easyimage.css
- plugins/imagebase/plugin.js
- tests/plugins/easyimage/manual/progressbar.md
- tests/plugins/imagebase/features/upload.js
New feature
This PR allows for improvement in uploading feedback by adding a class to a widget that is uploaded. As soon as uploading is done, the class is removed.
For the time being it adds only a slight opacity to the Easy Image during the upload, then once it's done transitions back into regular image colors.
Closes #1533.
> Improved uploading progress visual feedback

- plugins/cloudservices/plugin.js
- tests/plugins/cloudservices/manual/errors.md
Task
No need for unit tests, this is API docs correction for the most part.
Cloudservices (and Easy Image) plugin was initially targeted at 4.8.0 but we changed it to 4.9.0 release.
While Easy Image got updated, Cloud Service did not get a proper change, so this PR fixes that.
> Updated target release for the Cloud Services plugin

- tests/plugins/imagebase/features/_helpers/tools.js
Bug fix
This is fix to test itself.
When tests are running in Firefox they are fired asynchronously.
Closes #1571
> Fixed: Upload tests for Easy Image are unstable on Firefox

- tests/plugins/clipboard/mobilefix.js
I've explicitly removed offending plugins and move assertion directly into `createEditor` callback.
Closes #1615.
> Fix failing test for custom button inside mobile paste fix

- tests/plugins/balloontoolbar/context/widgetdnd.js
Other: failing test fix
The `target` was missing in simulated `mouseup` event which caused `tableselection` plugin to throw an error.
Also removed some leftover comments from the test.
Closes #1614.
> Fixed failing 'tests/plugins/balloontoolbar/context/widgetdnd ' test

- tests/core/selection/fake.js
Bugfix
Some plugins have event listeners that use property `event.data.domEvent`, and method `event.data.domEvent.getKey`. I've added such property and method to faked test event and test passes in builded version.
Closes #1612
> Fixed: Failing test on builded version: tests/core/selection/fake

- tests/plugins/widget/widgetsintegration.js
Task
The source issue of this has been described in #1632, however the change is too risky to do this in the last moment. So the unit test for Edge will be ignored the same way as it is for IEs, and we'll get back to that in 4.9.1.
> Ignored widget/widgetsintegration unit test for Edge

- tests/plugins/clipboard/manual/pastedialogwordbreak.md
Other: task
I've removed `tc` tag, which appeared after readding some old test for paste dialog.
> Remove tc test tag

- .github/ISSUE_TEMPLATE.md
Other, GH template update
No need.
Removed a section requesting for checking Trac for a duplicate and added request for checking the duplicates at the very beginning of the comment block.
> Remove Trac reference from the GitHub issue template

- plugins/easyimage/styles/easyimage.css
Restyling
It just changes styles…
Change default margins to 0 and to `1.5em` in case of side images.
Closes #1736.
> Change margins for Easy Image widget

- plugins/easyimage/styles/easyimage.css
Fix for bug fix
I've added `min-width` styles also to align left images.
> Min width fix for left-aligned Easy Image widgets

- tests/plugins/balloontoolbar/manual/balloontoolbar.html
Bug fix
This is fix to test itself.
In test `/tests/plugins/balloontoolbar/manual/balloontoolbar.html` items were added to panel on every click event. Now they are initially added which solves the problem.
Closes #1318
> Fixed: Exception after double-click on the text node

- plugins/easyimage/plugin.js
- plugins/easyimage/samples/easyimage.html
- tests/plugins/easyimage/config.js
- tests/plugins/easyimage/customstyleicons.js
- tests/plugins/easyimage/customstyles.js
- tests/plugins/easyimage/manual/customgroups.html
- tests/plugins/easyimage/manual/customstyleicons.html
- tests/plugins/easyimage/manual/customstyles.html
Variables rename
- change names of UI buttons to be coherent with other plugins. There is used global variable in plugin which easily kept button prefix use in entire plugin
- update docs with proper names
- update sample page and tests to work with new buttons' names
close #1769
> Update button names to be coherent with other plugins

- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/__template__.html
- tests/plugins/autocomplete/manual/optionselection.md
New feature
Added auto-selection for first autocomplete option on view open.
>  First autocomplete option is now focused when typing

- CHANGES.md
- core/editable.js
- tests/core/editable/manual/multilinejaws.html
- tests/core/editable/manual/multilinejaws.md
Bug fix
The reason why JAWS was leaving forms mode was that we're using [`[role="textbox"]`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_textbox_role) but no `[aria-multiline]` attr.
After adding the latter the issue is gone.
Closes #1034.
> Fixed JAWS leaving forms mode after pressing enter in CKEditor inline instances

- dev/langtool/meta/ckeditor.plugin-easyimage/meta.txt
- plugins/easyimage/lang/en.js
- plugins/easyimage/plugin.js
Bug fix
No, it's just simple language entry addition.
I've added `commands.upload` language entry to Easy Image plugin.
Closes #1792.
> Add language entry for Easy Image upload command

- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/__template__.html
- tests/plugins/autocomplete/manual/completingkeycodes.md
Feature request
Added global configuration and autocomplete options to choose completing key codes. Default key codes are now `enter` and `tab`.
>  Added option to set completing key codes

- CHANGES.md
- plugins/imagebase/plugin.js
- tests/plugins/imagebase/features/caption.html
- tests/plugins/imagebase/features/caption.js
- tests/plugins/imagebase/features/manual/captionemptyplaceholder.html
- tests/plugins/imagebase/features/manual/captionemptyplaceholder.md
Bug fix.
Changed `imagebase` plugin to refresh every caption featured widget on `selectionChange`.
Closes #1776
> Fixed blurring empty image base caption

- CHANGES.md
- plugins/imagebase/plugin.js
- tests/plugins/imagebase/features/caption.html
- tests/plugins/imagebase/features/caption.js
- tests/plugins/imagebase/features/manual/captionafterpaste.html
- tests/plugins/imagebase/features/manual/captionafterpaste.md
Caption is refreshed only when empty and without placeholder. With this change caption is preserved on paste.
Based on #1793
Closes #1592
> Fixed: easy image caption is hidden after paste

- CHANGES.md
- core/editor.js
- tests/core/command/command.js
New Feature
I've added check if `CKEDITOR.editor.addComand` has command instance passed it will register this command in editor and return it instead of creating new one.
Also added unit test to cover that case.
Closes #1582
> Added possibility to call `CKEDITOR.editor.addCommand` with `CKEDITOR.command` instance as parameter

- CHANGES.md
- plugins/autolink/plugin.js
- tests/plugins/autolink/autolink.js
- tests/plugins/autolink/manual/mail.html
- tests/plugins/autolink/manual/mail.md
Feature request
Added email support for autolink plugin.
Closes #1761
> Added email support for autolink plugin

- CHANGES.md
- plugins/filebrowser/plugin.js
- tests/plugins/filebrowser/manual/uploadckfinder.html
- tests/plugins/filebrowser/manual/uploadckfinder.md
- tests/plugins/filebrowser/uploadbutton.js
Bug fix
If upload method is set to xhr and URL contains `command=QuickUpload`, then `responseType=json` URL parameter is added.
Closes #1835.
> Fix integration with CKFinder

- CHANGES.md
- core/dom/element.js
- plugins/balloonpanel/plugin.js
- tests/core/dom/element/_assets/framerect.html
- tests/core/dom/element/_assets/rect.html
- tests/core/dom/element/absoluterect.html
- tests/core/dom/element/absoluterect.js
- tests/core/dom/element/manual/absoluterect.html
- tests/core/dom/element/manual/absoluterect.md
- tests/plugins/balloonpanel/positioning.js
- tests/plugins/balloonpanel/positioningnonstatic.js
New feature
Moved `_getAbsoluteRect` balloon toolbar private function to `core/element` as `getAbsoluteClientPosition`
I wasn't sure how to unit test this function because it behaves differently depending of used browser, monitor etc (because it depends on rendered pixels).  A tests would fail either if you open console etc. Because of that I only …
> Exposed getAbsoluteClientRect function

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/manual/nonexternalforceasplaintext.html
- tests/plugins/clipboard/manual/nonexternalforceasplaintext.md
- tests/plugins/clipboard/pastefilter.js
Bug fix
- activate content filtering during paste, when forcePasteAsPlainText is set to true, regardless of paste origin.
close #620
> forceAsPlainText will be respected inside internal and cross-editor pasting

- plugins/mentions/plugin.js
- tests/plugins/mentions/manual/casesensitive.html
- tests/plugins/mentions/manual/casesensitive.md
- tests/plugins/mentions/mentions.js
New feature
Added `caseSensitive` option to mentions plugin. Also, as default `mentions` simple feed is no longer case sensitive.
Closes #1934
> Added caseSensitive option for mentions plugin

- CHANGES.md
- plugins/tableresize/plugin.js
- tests/plugins/tableresize/manual/mergedcells.html
- tests/plugins/tableresize/manual/mergedcells.md
- tests/plugins/tableresize/tableresize.js
Bugfix
In theory I could cover this with unit test that would fail before this patch. But such test could just check if resizer appears on one spot. This should be tested manually to ensure that resizer fully acts as expected and doesn't show up in other unexpected places.
Previously resize plugin created one `pillar` after each column which is …
> Fixed: Column resize cursor shows up inside merged cells

- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/viewposition.md
Bug
After my changes iOS editor listens on a correct element for `scroll` event.
**Note:** Because of #1926 bug manual tests can be bugged. Although issue occurs randomly so you should be able to run manual tests. 
Closes #1910
> Fixed view positioning on iOS for autocomplete plugin

- plugins/mentions/plugin.js
- tests/plugins/mentions/manual/cache.html
- tests/plugins/mentions/manual/cache.md
- tests/plugins/mentions/mentions.js
New feature
Introduced URL requests caching for mentions plugin. This cache implementation is very simple and it's based on object keys. I decided to not overcompliacate it. Nevertheless, I think in the future we could replace it with implementation allowing to garbage collecting expired cache items so the cache will be refreshed after the given time. …
> Added mentions URL requests caching

- CHANGES.md
- core/tools.js
- tests/core/tools.js
- tests/core/tools/manual/throttle.html
- tests/core/tools/manual/throttle.md
New feature
Added throttling function based on `CKEDITOR.tools.eventsBuffer`.
Closes #1993
> Added throttling function

- plugins/autocomplete/plugin.js
- plugins/autocomplete/samples/customview.html
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/_helpers/utils.js
- tests/plugins/autocomplete/manual/viewstart.html
- tests/plugins/autocomplete/manual/viewstart.md
- tests/plugins/autocomplete/view.js
Bug fix
Refactored `autocomplete.view.getCaretRect` function to use the beginning of a typed word as a view starting position.
I tried to write some more integration test for text typing. However, I wasn't able to reproduce changing selection on typing. If you think we need additional integration test besides existing unit tests and manual test I will …
> Autocomplete dropdown position is now static when typing text

- plugins/autocomplete/plugin.js
- plugins/textwatcher/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/__template__.html
- tests/plugins/autocomplete/manual/outputtemplate.html
- tests/plugins/autocomplete/manual/outputtemplate.md
- tests/plugins/autocomplete/manual/throttle.html
- tests/plugins/autocomplete/manual/throttle.md
- tests/plugins/autocomplete/manual/viewposition.html
- tests/plugins/autocomplete/manual/viewstart.html
- tests/plugins/autocomplete/manual/viewtemplate.html
- tests/plugins/autocomplete/manual/viewtemplate.md
- tests/plugins/textwatcher/manual/throttle.html
- tests/plugins/textwatcher/manual/throttle.md
- tests/plugins/textwatcher/textwatcher.js
New feature
Implemented throttle feature inside `textwatcher` / `autocomplete` plugins. Refactored `autocomplete` constructor to use `CKEDITOR.plugins.autocomplete.configDefinition` abstract class.
Based on #1993 (PR #1996).
Closes #1997
> Added autocomplete throttle feature

- CHANGES.md
Changelog entry
**NOPE**, no tests.
Moved changelog entry for replaced `replace` dialog into API category with "Backward Incompatiblity" note.
> Update changelog entry for replaced dialog in find plugin

- plugins/mentions/plugin.js
New feature
Tests are available for autocomplete throttling.
I added data request throttling for each feed type with default throttling time `200` ms
I did some testing on this issue and I think that proposed throttling thresholds in #1972 ticket (70-120ms) is too low for performance profit.
Also I tried to use …
> Added mentions feed throttling

- plugins/emoji/plugin.js
- plugins/emoji/skins/default.css
task
* update usage of autocomplete API in emoji plugin.
* remove inline style used in template.
Close #2032
> Use autocomplete's config templates in emoji plugin

- plugins/tableselection/plugin.js
- tests/core/dom/range/misc.js
Other, please explain
task fix
- improve `if` statement to validate that node contains `is` method. This prevent of throwing an error, whent node will be instance of `CKEDITOR.dom.text`.
Close: #2089
> Improve node validation for removed cells in table

- plugins/textmatch/plugin.js
- tests/plugins/textmatch/manual/fillingcharsequence.html
- tests/plugins/textmatch/manual/fillingcharsequence.md
- tests/plugins/textmatch/staticfunctions.js
Bug fix
Previously I thought this issue should be fixed inside `textmatch` plugin but I think that we shouldn't mess with pattern matching which is delegated to the user implementation. The issue exists because we are using filling char sequence for styles on some browsers (probably to create clickable placeholder). I handled this issue inside …
> Mentions dropdown is now activated regardless of styling

- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/callbackcleaning.html
- tests/plugins/autocomplete/manual/callbackcleaning.md
Bug fix
Autocomplete query and id are removed on `unmatched` event so they invalidate old callback.
Because I have to add a similar manual test to existing tests I also did some refactoring to avoid code duplication.
Closes #1984
> Fixed opening autocomplete view on unmatch

- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/itemslimit.html
- tests/plugins/autocomplete/manual/itemslimit.md
New feature
Added additional `itemsLimit` configuration property allowing to limit the number of rendered items inside autocomplete dropdown.
Closes #2030, #2099
> Added items limit option for autocomplete plugin

- plugins/mentions/plugin.js
New feature
Tests are available for `autocomplete` plugin.
Added mentions items limit option.
Closes #2100
> Added mentions items limit option

- tests/core/editor/initialize_hidden.js
Fixed failing test
Due to race condition in Firefox bender added `instanceReady` listener with assertions after that event, so assertions were never fired. For that case I've added if statement which calls assertions right away if editor instance is ready.
Closes #2019
> Fixed: Failing initialize_hidden unit test

- plugins/autocomplete/plugin.js
- plugins/emoji/plugin.js
- plugins/mentions/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/_helpers/utils.js
- tests/plugins/autocomplete/model.js
New feature
Tests are already available for `autocomplete` plugin.
I updated dataCallback API to accept object instead of multiple parameters. Object exposes `autocomplete` instance.
Closes #2108
> Updated autocomplete dataCallback API

- tests/plugins/easyimage/uploadintegrations.js
Failing test
I have fixed some race condition by calling assertion as a callback to method `waitForImage` which basically calls wait() and resumes on images `load` event.
Closes #2057
> Fixed failing test on Edge 42

- tests/core/config/manual/extraplugins.html
- tests/core/config/manual/extraplugins.md
- tests/core/config/manual/plugins.html
- tests/core/config/manual/plugins.md
- tests/core/config/manual/removeplugins.html
- tests/core/config/manual/removeplugins.md
Failing test/task
It's just fix for manual tests.
I've made manual tests for #1712 mobile friendly. They also pass in built version now.
I didn't change unit tests as they got fixed in #1929.
Closes #1994.
> Make manual tests for plugins configuration mobile- & built-friendly

- tests/plugins/emoji/customemojilist.js
fialing test fix
- fix failing test: `/tests/plugins/emoji/customemojilist`, we need to stub XHR with regexp to consider cache buster in links.
> Correct failing emoji test in presets.

- core/editable.js
- tests/core/editable/manual/noneditableimage.html
- tests/core/editable/manual/noneditableimage.md
- tests/core/editable/misc.js
Bug fix
I've added `editor.focus()` to failing test.
BUT I also discovered that this test has been a false positive for 3 years 😱. Fix introduced in https://dev.ckeditor.com/ticket/13386 forced selection also of non-editable images, yet it was visible only via real interaction with the editor. I've fixed it as well, adding proper check. I've added …
> Selecting non-editable image in Edge

- tests/plugins/tableselection/integrations/core/selection.js
- tests/plugins/tableselection/integrations/tabletools/tabletools.js
- tests/plugins/tableselection/tableselection.js
I've added bunch of ignores for Edge. We should reinvestigate the issue after 4.10 release.
> Failing tableselection tests in Edge

- tests/plugins/autolink/autolink.js
Bug fix
- fix failing test for autolink. Remove dependancy where are not needed.
Close #2093
> Remove link plugin dependancy from unnecessary tests

- tests/plugins/easyimage/uploadintegrations.js
- tests/plugins/imagebase/features/_helpers/tools.js
Tests fix
I changed some tests to run asynchronously and increased paste files assertion timeout. It looks like Firefox need some more time to finish paste events. 30ms is not so long but if you thing it will make some huge impact on tests performance it can be increased only for Firefox. I think it make more sense to go for a single code path for simplicity.
Closes #1619
> Fixed failing tests for firefox tests/plugins/easyimage/uploadintegrations

- tests/plugins/textmatch/manual/fillingcharsequence.html
Test fix
Fixed `textmatch` failing  manual test by updating dataCallback API.
> Fixed textmatch failing manual test

- bender.ci.js
- plugins/mathjax/dev/mathjax.html
- plugins/mathjax/plugin.js
nit## What is the purpose of this pull request?
Task
No unit/manual tests were affected by this change.
See #2159 for description.
Along with that I had to adjust `plugins/mathjax/dev/mathjax.html` as it used old domain. Also a linter exception was required in the plugin.js.
Closes #2159.
> Bumped MatJax references version

- plugins/iframedialog/plugin.js
Other, docs fix
Not sure if changing method docs warrants test?
The `src` parameter for `CKEDITOR.dialog.addIframe` was missing (and currently still is eg. from [the documentation](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_dialog.html#static-method-addIframe)). I hope this fixes it.
> Fix docs for CKEDITOR.dialog.addIframe

- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/mouseover.html
- tests/plugins/autocomplete/manual/mouseover.md
Bug fix
On mouseover correct element is found by `data-id` attribute inside event's target node tree.
Closes #2187
> Autocomplete dropdown mouseover no longer throws an error

- CHANGES.md
- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.html
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/init.html
- tests/plugins/autocomplete/manual/init.md
Bug fix
Autocomplete recognizes editors state when attaching into an editor.
Closes #2114
> Attaching autocomplete before instanceReady event

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/manual/edgepasteimage.html
- tests/plugins/clipboard/manual/edgepasteimage.md
Fixes
Testing for custom mime types (just by trying setData with such type) makes dataTransfer inaccessible in Edge, so as a workaround for upstream issue I've added if statement which will omit such test on Edge.
Note:
I have different error in console, than described in original issue, but with my fix it looks to work fine.
Closes #2169.
> Edge 17 throws an error when pasting into editor

- CHANGES.md
- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/focus.js
- tests/plugins/autocomplete/manual/holdmousebutton.html
- tests/plugins/autocomplete/manual/holdmousebutton.md
- tests/plugins/autocomplete/view.js
Bug fix
I've registered autocomplete items in focusManager, so focusing them wont trigger editor blur event which was cause for hiding dropdown. Note `tabindex` is required for items to be focusable.
Closes #2107.
> Fixed: Holding and releasing mouse button is not inserting autocomplete item

- core/dom/documentfragment.js
Task
All docs entry are added via `@inheritdoc`, so they will always be matching to original methods.
Closes #2020
> CKEDITOR.dom.documentFragment - added missing docs on mixed methods

- CHANGES.md
- plugins/colorbutton/plugin.js
- tests/plugins/colorbutton/colorbutton.js
- tests/plugins/colorbutton/manual/automaticcolor.html
- tests/plugins/colorbutton/manual/automaticcolor.md
Bug fix
Before changes method applyColor still tried to apply style with undefined colour. After changes it is renamed to applyOrRemoveColor and it will remove styles when no colour is passed.
Closes #1084.
> Using 'Automatic' color on text with already applied color creates 'span.style=color:null'

- plugins/image/dialogs/image.js
In the `image` dialog, there is a function `switchLockRatio` which can receive a parameter `'check'` to indicate that it should try to automatically determine whether the current width/height are the result of previously having the ratio locked. However, the way this calculation is done is "too precise". For instance, if the image is 1800x1200 pixels, and the user resizes it to 500x333, the current calculation will not see 500x333 as being "the same" aspect ratio as 1800x1200. The way the calculation currently works is, the aspect ratio is scaled by 1,000 and then rounded off, which is the same as keeping three decimals. With four decimals, 1800x1200 produces an aspect ratio of 1.500, while 500x333 produces an aspect ratio of 1.502 (1.5015015...).
I think a more appropriate cutoff is 2%, …
> Improved aspect ratio matching in switchLockRatio function

- plugins/colorbutton/plugin.js
Hey!
I maintain the Symfony2 integration of CKEditor and someone reports me the custom color label are not working in egeloen/IvoryCKEditorBundle#204
Basically, something like explain in the doc is not working: http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-fileTools_defaultFileName#cfg-colorButton_colors
After debugging it, I notice the plugin fallbacks on the `colorCode` if the color trans is not found but IMO, if someone provides a explicit color label, it should be used directly and the current color code should only be involved if the label is not provided at all.
For the testing part, I'm not familiar with it and so, I was not able to add one... If someone can point me the way to go I can add them :)
> [Plugin][ColorButton] Fix color name displayed

- CHANGES.md
- plugins/colorbutton/plugin.js
- tests/plugins/colorbutton/config.js
- tests/plugins/colorbutton/manual/customlabel.html
- tests/plugins/colorbutton/manual/customlabel.md
Bug fix
There was a bug in how custom color labels are fetched. Community PR was good in that regard, I have added manual and unit tests for this case.
Closes #2271.
Follow-up of a #253.
> Fixed custom color name not being used as a label in Color Button plugin

- core/dom/document.js
- core/dom/element.js
- core/dom/range.js
Task
Skipped tests, this is doc only change.
Added an explicit information that selector is a CSS selector.
During the process I was thinking about higher DRY factor, however both methods have such documentation that it differs in details here and there, thus rendering `@inheritdoc` unfeasible.
Closes ckeditor/ckeditor-docs#43.
> Added an explicit information that find/findOne selector is a CSS selector

- core/style.js
Fixes issue #1046
Not yet - will add later
When creating a new element based on style it would remote the ID attribute to prevent duplicates.
This bit of code was added in 2011 to prevent an issue with copying links (according to the git blame and git log 235dc2a7edb21a6b8514ce189121e721b5ab2298) - I did not retest this use case as I did not know …
> Make sure the ID is always inserted if entered in the advanced dialog

- CHANGES.md
- plugins/emoji/plugin.js
- tests/plugins/emoji/basic.js
- tests/plugins/emoji/manual/spacerequired.html
- tests/plugins/emoji/manual/spacerequired.md
Bug fix
Added check for last character before colon. If it's not white space then don't show drop down.
Closes #2195
> Fixed: Emoji shows suggestion box when colon preceded with other character than white space

- CHANGES.md
- core/selection.js
- tests/core/selection/fake.js
- tests/core/selection/manual/iereadonly.html
- tests/core/selection/manual/iereadonly.md
- tests/core/selection/selection.js
- tests/plugins/widget/widgetsintegration.js
Bug fix
The first idea was to skip changing selection on keydown events for read-only mode which was little naive. I found out there is a change proposed by @mlewand which works pretty well. In this version, we are selecting widget only if it's not an entire editable for keydown events. I added an additional unit test. 
I'm not sure how to test this …
> Fixed a bug that was causing certain selection in read only mode to report an error

- CHANGES.md
- core/editable.js
- tests/plugins/tableselection/manual/firefoxrightclick.html
- tests/plugins/tableselection/manual/firefoxrightclick.md
- tests/plugins/tableselection/tableselection.html
- tests/plugins/tableselection/tableselection.js
Bug fix
I've removed part of legacy code which produced this issue.
Notes:
-This bug is only reproducible in Firefox on Windows.
-Original bug can be found here:
https://dev.ckeditor.com/ticket/5845
As I'm not able to reproduce it after this change I believe nothing is broken anymore. Also after browsing commit history I didn't find any tests for that …
> Fixed: Right click on empty paragraph inside table removes table selection on Firefox

- CHANGES.md
- core/editor.js
- core/plugins.js
- core/tools.js
- plugins/image/plugin.js
- plugins/image2/plugin.js
- tests/core/plugins/plugins.js
- tests/core/tools.js
Task
Moved `detectPluginConflict` from `CKEDITOR.tools` to `CKEDITOR.editor.prototype.plugins`. Updated tests accordingly.
Closes #2341.
> Move plugins conflict detection helper

- plugins/clipboard/plugin.js
http://tests.ckeditor.test:1030/tests/plugins/undo/change#tests%2Fplugins%2Fundo%2Fchange%20test%20no%20change%20event%20on%20create%20and%20destroy was bleeding with:
```javascript
Uncaught TypeError: Cannot read property 'on' of null
at plugin.js:606
at Object.forEach (tools.js:2094)
at Editor.<anonymous> (plugin.js:600)
at Editor.args.(anonymous function) (http://tests.ckeditor.test:1030/apps/ckeditor/core/event.js:202:16)
at Editor.listenerFirer (event.js:144)
at Editor.CKEDITOR.event.fire (event.js:290)
at Editor.CKEDITOR.editor.fire (editor_basic.js:24)
at Editor.fireOnce (event.js:334)
at Editor.CKEDITOR.editor.fireOnce (editor_basic.js:31)
at Editor.<anonymous> (themedui.js:360)
```
Error is connected with adding touch listener to paste button, as it's added after …
> Fix for bleeding undo test

- tests/plugins/tableselection/manual/nativeenterkey.html
- tests/plugins/tableselection/manual/nativeenterkey.md
Failing test
I've fixed the typo that prevented removal of `enterkey` plugin in `tests/plugins/tableselection/manual/nativeenterkey`.
> Force removal of enterkey plugin in test

- tests/core/filter/manual/classcheckinlexicalorder.md
Task
The test was missing ticket reference.
> Added a missing reference to classcheckinlexicalorder manual test

- tests/plugins/image/manual/easyimage.html
- tests/plugins/image/manual/easyimageimage2.html
- tests/plugins/image/manual/image2.html
- tests/plugins/image2/manual/easyimage.html
Ignores manual tests that rely on the console in mobile env.
Closes #2361.
> Ignore mobile unfriendly manual tests for plugins

- CHANGES.md
- plugins/contextmenu/plugin.js
- tests/_benderjs/ckeditor/static/bot.js
- tests/plugins/contextmenu/contextmenu.js
- tests/plugins/contextmenu/integration.js
- tests/plugins/contextmenu/manual/readonly.html
- tests/plugins/contextmenu/manual/readonly.md
Bug fix
I've added a simple check to open context menu only if there is selection inside the editor. In Chrome there is no selection inside the editor before the first focus. Unfortunately it required to update tests connected to context menu as many of them were fired on editor without the selection.
Closes #1181.
> Fix type error while opening context menu in readonly editor

- CHANGES.md
- core/tools.js
- tests/core/tools.js
- tests/core/tools/manual/eventbuffer.html
- tests/core/tools/manual/eventbuffer.md
- tests/core/tools/manual/throttlebuffer.html
- tests/core/tools/manual/throttlebuffer.md
Task
Refactored duplicated throttle and eventsBuffer code.
Closes #2045
> Refactored duplicated throttle and eventsBuffer code

- CHANGES.md
- core/selection.js
- tests/core/selection/editor.js
- tests/core/selection/manual/commandsrefresh.html
- tests/core/selection/manual/commandsrefresh.md
Bug fix
A selection wasn't refreshed for touch events and in the result, commands weren't correctly refreshed on iOS. I added appropriate event listeners for `selection`.
**Note:** Unit and manual tests are enabled on each browser for simplicity and future changes.
Closes #2276
> Fixed issue with invalid commands state refresh

- CHANGES.md
- plugins/tableselection/plugin.js
- tests/plugins/tableselection/manual/readonly.html
- tests/plugins/tableselection/manual/readonly.md
- tests/plugins/tableselection/tableselection.js
Bug fix.
Disabled table selection delete on `keypress` and `keydown` events in a readonly mode.
~**NOTE:** This pull request depends on #1525 fix. It was created from `t/1525` branch.~
Based on #1692
Closes #1489
> Fixed: [tableselection] table contents can be removed in a readonly mode

- CHANGES.md
- plugins/forms/dialogs/checkbox.js
- plugins/forms/dialogs/radio.js
- plugins/forms/dialogs/select.js
- plugins/forms/dialogs/textarea.js
- plugins/forms/dialogs/textfield.js
- plugins/forms/plugin.js
- tests/plugins/forms/_helpers/tools.js
- tests/plugins/forms/checkbox.js
- tests/plugins/forms/manual/required.html
- tests/plugins/forms/manual/required.md
- tests/plugins/forms/radio.js
- tests/plugins/forms/select.js
- tests/plugins/forms/textarea.js
- tests/plugins/forms/textfield.js
Bug fix
I've changed form dialog to set its property `required = true` whenever matching attribute exists on form element.
Closes #586
> Fixed required attribute not being correctly recognized by form dialog

- CHANGES.md
- plugins/panel/plugin.js
- tests/plugins/panel/manual/edgepermissiondenied.html
- tests/plugins/panel/manual/edgepermissiondenied.md
- tests/plugins/panel/panel.js
Bug fix
Edge throws 'permission denied' when trying to append an iframe with `src` attribute containing some javascript. This happens within `panel` plugin, excluded Edge from check, so `src` should be empty. After some testing it looks like nothing is broken.
Closes #2035
> [Edge] Fixed: 'Permission denied' is thrown when opening panel instance

- tests/core/tools/absoluterectposition.html
- tests/core/tools/absoluterectposition.js
- tests/plugins/balloonpanel/_helpers/tools.js
- tests/plugins/balloonpanel/positioning.inline.js
- tests/plugins/balloonpanel/positioning.js
Failing tests
`tests/core/tools/absoluterectposition`
- Firefox returned float numbers, as they were differing by less than one pixel I've rounded them
- Space filler had 2000px height, as it wasn't enough to make scrollbars visible in vertical monitors I've increased it's size to 5000px.
`tests/plugins/balloonpanel/positioning.inline`
- Firefox returned …
> Fixed failing tests on vertical screens

- plugins/htmlwriter/plugin.js
- tests/plugins/htmlwriter/htmlwriter.js
Run ampersand replacement after the  htmlEncodeAttr, otherwise the results are overwritten (https://github.com/ckeditor/ckeditor-dev/issues/965)
Bug fix
Run ampersand replacement after CKEDITOR.tools.htmlEncodeAttr() executes against the given attribute 
Closes #965.
> Fix forceSimpleAmpersand config implementation

- CHANGES.md
- plugins/balloontoolbar/plugin.js
- plugins/richcombo/plugin.js
- tests/plugins/balloontoolbar/destroy.js
- tests/plugins/balloontoolbar/manual/destroy.html
- tests/plugins/balloontoolbar/manual/destroy.md
- tests/plugins/richcombo/richcombo.js
Bugfix
I've made balloonToolbar `destroy` to call also `destroy` on each of its `_items`. And added `destroy` method to richCombo, which removes all listeners from it.
Closes #1477
> Balloon toolbar on destroy doesn't destroy its content

- CHANGES.md
- plugins/emoji/plugin.js
- tests/plugins/emoji/basic.js
- tests/plugins/emoji/manual/repeated.html
- tests/plugins/emoji/manual/repeated.md
Bug fix
Emoji symbol was incorrectly matched when tested text have duplicated symbols.
Closes #2394
> Fixed emoji text matching with repeated symbols in a single line

- .npm/README.md
Task
No need for tests, markdown only changes.
Fixed the issue of wrong images by replacing it with permalink.
The only problem with this is that readme.md when viewed offline will not show the image, but we're ok with that as we think this is a rare case.
I wanted also remove `assets/ckeditor4.png` (as the image is duplicated now), but we can't do this …
> Use permalink for npm readme image

- CHANGES.md
- plugins/uploadwidget/plugin.js
- tests/plugins/uploadwidget/manual/abortupload.html
- tests/plugins/uploadwidget/manual/abortupload.md
- tests/plugins/uploadwidget/uploadwidget.js
Bug fix.
Changed initialisation of the [upload Widget Definition](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.fileTools.uploadWidgetDefinition) to include [`onAbort`](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.fileTools.uploadWidgetDefinition-property-onAbort) method when upload status changes to `abort`.
Closes #1454
> Fixed 'uploadWidgetDefinition.onAbort' method is not called when loader is aborted

- CHANGES.md
- core/editor.js
- core/filter.js
- plugins/clipboard/plugin.js
- plugins/copyformatting/plugin.js
- plugins/widget/plugin.js
- tests/core/editor/destroy.js
- tests/core/editor/manual/filterdestroy.html
- tests/core/editor/manual/filterdestroy.md
- tests/plugins/widget/manual/nestededitablefilters.html
- tests/plugins/widget/manual/nestededitablefilters.md
- tests/plugins/widget/nestededitables.js
- tests/plugins/widget/nestedwidgets.js
Bug fix
Added additional option to `CKEDITOR.filter` constructor to pass an editor owning filter instance. Changed `editor.destroy` function to remove correct editors and refactored plugins using `CKEDITOR.filter`. With this change we are now able to remove orphaned editor filters and prevent memory leak with `CKEDITOR.filter.instances`.
Additional …
> Removed memory leak caused by CKEDITOR.filter.instances

- CHANGES.md
- plugins/link/plugin.js
- tests/plugins/link/link.js
- tests/plugins/link/manual/keystroke.html
- tests/plugins/link/manual/keystroke.md
New feature
I've added new keystroke for link command. Additionally I added tests to check if it's working alongside the old <kbd>Ctrl</kbd> + <kbd>L</kbd> one.
Closes #2478.
> Add Ctrl+K keystroke for link command

- CHANGES.md
- plugins/mentions/plugin.js
- tests/plugins/mentions/manual/diacritic.html
- tests/plugins/mentions/manual/diacritic.md
- tests/plugins/mentions/mentions.js
Bug
Fixed mentions regex to match diacritic characters.
Closes #2491
> Mentions plugin now matches diacritic characters

- CHANGES.md
- plugins/entities/plugin.js
- tests/plugins/entities/entities.js
- tests/plugins/entities/manual/additional.html
- tests/plugins/entities/manual/additional.md
Bug fix
Simple comma leftover broke the whole `entities_additional` feature. I could modify regex instead of additional trailing coma removal, although it may look nasty.
Closes #2448
> Fixed issue with incorrectly escaped additional entities

- tests/plugins/tableselection/tableselection.js
Failing test
It looks like the editor is left in an invalid state between tests for `undo` plugin ( tests passes when run separately).
Closes #2522
> Removed undo plugin causing failing tableselection test

- tests/plugins/contextmenu/manual/contentscss.html
Failing test
It looks like `CKEDITOR.skinName` is missing in built version. Not sure if it's a bug (if so, I prefer extracting it to the separate issue thus it would require some additional testing), however setting this configuration explicit fixes the issue with a manual test.
Closes #2533
> Fixed /tests/plugins/contextmenu/manual/contentscss test

- plugins/emoji/skins/default.css
- tests/plugins/emoji/manual/dropdown/dropdowninputoutline.html
- tests/plugins/emoji/manual/dropdown/dropdowninputoutline.md
Bug fix/ styling improvement
Changed styling of emoji button input field, so loupe icon is contained within it, and increased it's height to 25px.
Closes #2547
> Moved loupe icon into emoji search field, increased height of field to 25px

- tests/core/editor/manual/filterdestroy.html
Test fix
- remove not supported `addEventListener` on IE8 from manual test.
Close #2549
> Correct manual test to work on IE8

- tests/plugins/contextmenu/keystroke.js
Failing test
Ignored test for an inline editor on IE8 due to #549 issue.
Closes #2530
> Ignored tests/plugins/contextmenu/keystroke test on ie8

- plugins/contextmenu/plugin.js
- tests/plugins/contextmenu/manual/keystroke.html
- tests/plugins/contextmenu/manual/keystroke.md
Bug fix
I've forced preventing opening our menu for native `contextmenu` event fired by <kbd>Shift</kbd> + <kbd>F10</kbd> keystroke.
Closes #2548.
> Fix incorrect positioning of context menu in Firefox

- tests/plugins/table/table.js
- tests/tickets/14755/1.js
When test is run from dashbord on mobiles editable might have width < 500px, which results in different default table styling.
https://github.com/ckeditor/ckeditor-dev/blob/8b8d7fd0832330232af8dfce34e6a0484a728062/plugins/table/dialogs/table.js#L382
I fixed it by forcing editable to return 500px width.
Closes #2529
> Fixed failing tests on mobile devices

- CHANGES.md
- plugins/emoji/plugin.js
- plugins/emoji/skins/default.css
- tests/plugins/emoji/dropdown.js
- tests/plugins/emoji/manual/dropdown/scrollpagebug.html
- tests/plugins/emoji/manual/dropdown/scrollpagebug.md
Bug fix
* fix bug, when page was scrolled when group of emoji dropdown was clicked
Close #2571
> Fix bug with scrolling page after emoji group click

- CHANGES.md
- plugins/tabletools/dialogs/tableCell.js
- plugins/tabletools/plugin.js
- tests/plugins/tabletools/allowedcontent.js
- tests/plugins/tabletools/cellproperties.js
- tests/plugins/tabletools/manual/allowedcontent.html
- tests/plugins/tabletools/manual/allowedcontent.md
Bug fix
I've added `requiredContent` for each option in table cell properties dialog.
Closes #1986
> Fixed: cell properties dialog shows styles that are not allowed through allowedContent

- CHANGES.md
- core/dom/range.js
- tests/core/dom/range/gettableelement.html
- tests/core/dom/range/gettableelement.js
- tests/plugins/tableselection/integrations/clipboard/pastewrapped.html
- tests/plugins/tableselection/integrations/clipboard/pastewrapped.js
- tests/plugins/tableselection/manual/pastenestedtable.html
- tests/plugins/tableselection/manual/pastenestedtable.md
- tests/plugins/tableselection/manual/styleleak.html
- tests/plugins/tableselection/manual/styleleak.md
Bug fix
Getting table cells by range didn't work correctly when used with the inline editor - I added a condition that getting table cells should be limited to the range root element.
Closes #2403, closes #2514
> Fixed issue with tableselection styles leaking

- tests/plugins/balloontoolbar/positioning.js
Fix for failing test.
- Unignored failing test.
- Mocked window viewPaneSize.
- Included scroll position in assertions.
- Restored scroll position in setUp.
- Rounded balloon toolbar top rect on IE.
- Removed `divarea` from test names, as editor name is dynamically added to test case by `bender.tools.createTestsForEditors`.
Closes #1076
> Fix for failing test tests/plugins/balloontoolbar/positioning

- CHANGES.md
- plugins/image2/plugin.js
- tests/plugins/image2/manual/upcast.html
- tests/plugins/image2/manual/upcast.md
- tests/plugins/image2/upcast.js
Bug Fix
Added an extra check in upcasting method, so it won't throw type error.
Closes #2506
> Fix for: image2 throws an exception when empty figure with class 'image' is upcasted

- CHANGES.md
- plugins/table/dialogs/table.js
- tests/plugins/table/manual/dialogvalidate.html
- tests/plugins/table/manual/dialogvalidate.md
- tests/plugins/table/validate.js
Bug fix
As `dialog.validate` methods are defined to be used with proper context I've updated `validatorNum ` helper in table dialog.
Closes #2650
> Fix for: table dialog validator fails when function getValue is defined in global scope

- CHANGES.md
- plugins/balloontoolbar/plugin.js
- plugins/easyimage/plugin.js
- tests/plugins/balloontoolbar/manual/reposition.html
- tests/plugins/balloontoolbar/manual/reposition.md
- tests/plugins/balloontoolbar/positioning.js
New Feature
I've added method to reposition balloon toolbar.
Closes #1496
> Exposed CKEDITOR.ui.balloonToolbar.reposition

- CHANGES.md
- core/dom/documentfragment.js
- core/dom/range.js
- tests/core/dom/documentfragment.js
New feature
I've added `find` and `findOne` methods to the `CKEDITOR.dom.documentFragment`.
Closes #2021.
> Add CKEDITOR.dom.documentFragment.find and CKEDITOR.dom.documentFragment.findOne

- tests/core/tools/absoluterectposition.js
Fix for failing tests
Mocked `window.getScrollPosition` so test gives consistent results.
Closes #2566
> Fix for: Failing tests /tests/core/tools/absoluterectposition

- CHANGES.md
- core/tools.js
- tests/core/tools/array.js
New feature
Added new array tool: `CKEDITOR.tools.array.find`
Closes #2700
> Added CKEDITOR.tools.array.find

- CHANGES.md
- plugins/list/plugin.js
- tests/plugins/list/list.js
- tests/plugins/list/manual/sublistreverse.html
- tests/plugins/list/manual/sublistreverse.md
Bug fix
Using last added child (list) item as `refNode` in `mergeChildren` helper.
Closes #2721
> Fix for: Sublist order is reversed when higher level list is removed

- core/creators/inline.js
- core/creators/themedui.js
- tests/core/creators/creators.js
bug fix
Throw helpful error when bogus DOM element is passes to `inline()`, `appendTo()`, or `replace()`.
Closes #2748
> Fixes #2748 Throw friendly error for invalid/missing id's on editor creation

- CHANGES.md
- core/ckeditor.js
- core/creators/inline.js
- core/creators/themedui.js
- core/editor.js
- tests/core/ckeditor/ckeditor.js
- tests/core/creators/creators.js
- tests/core/creators/duplicates.js
- tests/core/creators/inline-textarea.js
New feature
I've replaced `throw` statements in our creators with calls to `CKEDITOR.error` with two new error codes:
* `editor-incorrect-element` – logged when user tries to attach editor to nonexistent element,
* `editor-element-conflict` – logged when user tries to attach editor to the element with already attached one.
Additionally I moved the logic …
> Enhance error messages for creators

- CHANGES.md
- plugins/image2/plugin.js
- tests/plugins/image2/manual/dialogafterresize.html
- tests/plugins/image2/manual/dialogafterresize.md
- tests/plugins/image2/manual/maxsize.html
- tests/plugins/image2/manual/maxsize.md
- tests/plugins/image2/resizehandler.js
- tests/plugins/uploadfile/_helpers/waitForImage.js
- tests/plugins/uploadfile/uploadfile.js
- tests/utils/testhelpers.js
New feature + Bugfix
- Added new config option `CKEDITOR.config.image2_maxSize` that limits maximum size that image can be resized with resizer.
- Fixed resizer `mousemove` listener to update widget data with last correct value which is same as one set on element.
Closes #2048 
Closes #2672
Closes #2714
> Added CKEDITOR.config.image2_maxSize

- .travis.yml
- bender.ci.js
- bender.js
- package.json
- tests/_benderjs/ckeditor/static/tools.js
- tests/core/config/startupfocus.js
- tests/core/dom/range/getclientrects.js
- tests/core/tools.js
- tests/plugins/balloonpanel/_helpers/tools.js
- tests/plugins/balloonpanel/cssloading.js
- tests/plugins/balloontoolbar/cssloading.js
- tests/plugins/balloontoolbar/positioning.js
- tests/plugins/easyimage/balloontoolbar.js
Bug
* Update travis config
* Add updated dependencies of bender, which are necessary for Travis
* Add new config variable `isTravis` to detect if current test is run on Travis
* Update paths in some test to be proper relative paths
* Ignore few tests, which fails on Travis
* Include new bender tools, which detects if tests are run on build version of …
> Fix Travis CI

- CHANGES.md
- plugins/emoji/plugin.js
- tests/plugins/emoji/basic.js
- tests/plugins/emoji/manual/sortingorder.html
- tests/plugins/emoji/manual/sortingorder.md
Bug fix
* Add sort algorithm, which prioritize emoji which starts from searched string
Close #2527
> Improve order of emoji in autocomplete

- plugins/emoji/plugin.js
- plugins/emoji/skins/default.css
- tests/plugins/emoji/manual/dropdown/pointercursorinnavigation.html
- tests/plugins/emoji/manual/dropdown/pointercursorinnavigation.md
- tests/plugins/emoji/manual/dropdown/scrollpagebug.html
- tests/plugins/emoji/manual/dropdown/scrollpagebug.md
- tests/plugins/emoji/manual/dropdown/smallrefactoring.md
Task.
- remove unnecessary css for emoji
- pass element to function instead of reading it twice
Close #2592
> Remove redundant code from emoji plugin

- CHANGES.md
- plugins/colorbutton/plugin.js
- tests/plugins/colorbutton/config.js
- tests/plugins/colorbutton/manual/customcolors.html
- tests/plugins/colorbutton/manual/customcolors.md
Forced plugin to set `colorCode` instead of `colorName` on text.
Reason behind this change can be found here: https://github.com/ckeditor/ckeditor-dev/issues/1478#issuecomment-444112312
Closes #1478
> Fix for:  Custom colors added to `colorButton_colors` in form label/code don't work correctly

- CHANGES.md
- plugins/autolink/plugin.js
- tests/plugins/autolink/autolink.js
- tests/plugins/autolink/manual/sourcemode.html
- tests/plugins/autolink/manual/sourcemode.md
Bug fix
Prevented on `key` listener in `sourcemode`.
Closes #2756
> Fix for: Autolink throws an error in Source Mode

- CHANGES.md
- plugins/tabletools/dialogs/tableCell.js
- plugins/tabletools/plugin.js
- tests/plugins/tabletools/allowedcontent.js
- tests/plugins/tabletools/cellproperties.js
- tests/plugins/tabletools/manual/allowedcontent.html
- tests/plugins/tabletools/manual/allowedcontent.md
- tests/plugins/tabletools/manual/filebrowserintegration.html
- tests/plugins/tabletools/manual/filebrowserintegration.md
Bug fix
Changes from #2086 were reverted by #2735 because of nasty regression #2732.
Problem comes from here:
https://github.com/ckeditor/ckeditor-dev/blob/abd2465fd64ae9e9f84c275210f73d2fec54c219/plugins/tabletools/dialogs/tableCell.js#L317-L334
And repeated in [L364-382](https://github.com/ckeditor/ckeditor-dev/blob/abd2465fd64ae9e9f84c275210f73d2fec54c2 …
> Restore reverted optimizations of table cell allowed content

- core/template.js
- tests/core/template.js
New feature
Yes
I allowed to pass a callback function that returns a template.
The main reason is I want to use it in configuration of 'mentions' plugin
Some of the users I want to mention does not have avatars, in this case I want to display their initials instead of unreachable image.
```
mentions: [
{
feed: dataFeed,
marker: '@',
itemTemplate: function(data) {
return '<li data-id="{id}" class="autocomplete-item">' +
(data.imageUrl ? '<img class="avatar" src="{imageUrl}"/>' : '<span class="initials">{initials}</span>') +
'<span>{label}</span>' +
'</li>'
},
outputTemplate: '[[{type}|{id}|{label}]]<span>&nbsp;</span>',
minChars: 1
}
]
```
Closes #2821.
> Pass a function that returns a template to CKEDITOR.template class

- CHANGES.md
- core/tools.js
- plugins/button/plugin.js
- tests/core/tools.js
- tests/plugins/button/button.js
- tests/plugins/button/manual/rightclick.html
- tests/plugins/button/manual/rightclick.md
Bug fix
I've added additional check if left mouse button was used for click. I also add ability to get info about mouse button from native DOM event in `CKEDITOR.tools.getMouseButton`.
Closes #2565.
> Fix for ability to activate buttons using right click

- CHANGES.md
- plugins/copyformatting/plugin.js
- tests/plugins/copyformatting/applyformat.js
- tests/plugins/copyformatting/manual/nestededitablefocus.html
- tests/plugins/copyformatting/manual/nestededitablefocus.md
- tests/plugins/copyformatting/manual/undointegration.html
- tests/plugins/copyformatting/manual/undointegration.md
- tests/plugins/copyformatting/undointegration.js
Bug fix
* Prevent of firing `applyFormat` command after mouse up event, when there is no stored formatting.
Closes #2780.
Closes #2655.
Closes #2470.
> Fix disappearing undo steps after multiple selection changes

- tests/plugins/tabletools/allowedcontent.js
Failing test
I've explicitly get `tablecell` menu item instead of getting the first menu item. Fixes issue with tests after merging #2746.
> Fix for failing table tests on built version

- core/tools.js
Task
👆 no need, it's just a task.
Reason for this is that JSDuck doesn't recognize the MouseEvent type.
For more details see ckeditor/ckeditor-docs#230.
> Adjusted the param type for getMosueButton

- tests/_benderjs/ckeditor/static/bot.js
- tests/_benderjs/ckeditor/static/tools.js
Bug fix
* fix failing tests - opening menu and panel simulation require information about used mouse button
* add helper to fire elements events
Close #2826, close #2827
> Add information about used left button to open menu or panel with bot

- tests/plugins/tabletools/manual/allowedcontent.html
- tests/plugins/tabletools/manual/allowedcontent.md
Task
Added `removePlugins` option in config. Tested it by adding `colordialog` plugin in corresponding `.md` file, seems to work ok.
Edit: it works on built version too.
> Force removal of color dialog in tests/plugins/tabletools/manual/allowedcontent

- CHANGES.md
- adapters/jquery.js
- core/tools.js
- plugins/adobeair/plugin.js
- plugins/dialog/plugin.js
- plugins/find/dialogs/find.js
Replacement of deprecated code.
Tests already in place.
Replaced 'arguments.callee' in 5 files, mostly using named function expressions.
Closes #2741.
> Replace deprecated 'arguments.callee'

- CHANGES.md
- plugins/table/dialogs/table.js
- tests/plugins/table/manual/onlyrowheader.html
- tests/plugins/table/manual/onlyrowheader.md
- tests/plugins/table/table.js
Bug fix
If tbodies is empty it is impossible to `instertBefore` its first child. I've changed it to use method `append` instead.
Closes #1397
> Fix for: Using dialog to remove table header when tbody is empty throws an error

- tests/plugins/uploadfile/uploadfile.js
For inline editor:
```
editor.focus();
editor.getSelection().getRanges(); // returns empty array
```
It looks like browser bug, especially that it wasn't present in previous version, but I couldn't reproduce it without CKEditor. Also no other tests seems to be affected - it looks like some edge case.
In such case I don't think we need any workarounds for the browser issue. In this PR I propose to fix TC by just creating proper selection.
Closes #2971
> Fix for: failing test on Firefox 66 plugins/uploadfile/uploadfile

- CHANGES.md
- plugins/image2/plugin.js
- tests/plugins/image2/manual/resizerwithreadonly.html
- tests/plugins/image2/manual/resizerwithreadonly.md
- tests/plugins/image2/resizerwithreadonly.js
Bugfix
Yes
Resize handler does not show up on hover if content is not editable. I added one css rule for that.
Also unit test logic has been changed - now it checks if resize handler is properly initialized in all scenarios.
Closes #2816.
Closes #2874.
> Fix for: Resize handler was visible after entering read-only mode manually

- CHANGES.md
- core/ckeditor.js
- core/loader.js
- core/scriptloader.js
- core/skin.js
- plugins/autocomplete/plugin.js
- plugins/codesnippet/plugin.js
- plugins/dialog/plugin.js
- plugins/image2/plugin.js
- plugins/magicline/plugin.js
- plugins/widget/plugin.js
- tests/core/editor/currentInstance.js
- tests/core/loader.js
- tests/core/scriptloader.js
- tests/plugins/autocomplete/autocomplete.html
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/codesnippet/highlighter.js
- tests/plugins/image2/dialoglistener.html
- tests/plugins/image2/dialoglistener.js
- tests/plugins/magicline/magicline.js
- tests/plugins/magicline/memory.js
- tests/plugins/magicline/widgets.js
Bug fix
List of found and fixed memory leaks/ potential memory leaks:
Magicline plugin exposes `backdoor` object property for debugging purposes in `CKEDITOR.plugins.magicline`, this object is replaced with each editor creation.
To fix memory leaks I've moved this property into `editor._.magicLineBackdoor`, so all references are removed along with editor …
> Fix for: memory leaks

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/manual/readonlystate.html
- tests/plugins/clipboard/manual/readonlystate.md
- tests/plugins/clipboard/readonly.js
Bugfix
Included `editor.readOnly` in check for command state function.
Closes #2775
> Fix for: Paste buttons has wrong state in read-only mode

- tests/plugins/balloontoolbar/positioning.js
Failing test
Balloon toolbar uses few events to reposition itself. In failing TC we manually fire `change` to force reposition, however sometimes it is triggered by some other event due to some race condition. 
There are few ways to fix this:
1. Change assertion type from `reposition.callCount === 1` to` >= 1`. However if `change` listener was removed this would lead to false positive test as balloon could still be repositioned due to other listeners.
1. Wrap test function with `setTimeout`. It seems to help, however you never know if it won't fail in future.
1. Cancel other events used by balloon toolbar.
So I chose the last option.
Closes #2979
> Fixed unstable test in `tests/plugins/balloontoolbar/positioning`

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/manual/pastewidget.html
- tests/plugins/widget/manual/pastewidget.md
- tests/plugins/widget/nestededitables.js
Bug fix
I've added check to `toData` callback to ensure that only nested editables, that are inside upcasted widgets, will be downcasted.
Closes #1469.
> Check if nested editable has upcasted widget parent

- CHANGES.md
- core/selection.js
- plugins/tableselection/plugin.js
- tests/plugins/tableselection/integrations/clipboard/pastemerge.html
- tests/plugins/tableselection/integrations/clipboard/pastemerge.js
- tests/plugins/tableselection/integrations/core/selection.js
- tests/plugins/tableselection/manual/ignore.html
- tests/plugins/tableselection/manual/ignore.md
- tests/plugins/tableselection/tableselection.js
New feature
**Note** Keyboard listeners don't need this improvement thus they handle faked table selection only which should be already disabled for the given element.
Closes #2945
> Add method to disable tableselection feature for the given element

- tests/plugins/emoji/dropdown.js
Fix failing tests
Original issue reported only one case, however I could see three different reasons for tests to fail on Firefox.
Sometimes tests were run earlier resulting in type error. This is fixed by adding `waitForEmoji` which is delaying each test case until Emoji List is loaded. Related issue: #3094.
- expected: `'<p>⭐</p>'`
- actual: `'<p>⭐</p><p> </p>'`
Fixed by adding `result.replace( regex )` to cut empty paragraph.
Firefox seems to not respond very well to multiple synchronous changes of `scrollTop` of various elements, and that's what we do in our implementation of `scrollIntoView`. When this TC fails scroll position is incorrect. Fixed by calling native `scrollIntoView` for Firefox.
Additionally take a look at the code: …
> Fix for: Failing test `tests/plugins/emoji/dropdown`

- CHANGES.md
- core/selection.js
- plugins/tableselection/plugin.js
- tests/plugins/tableselection/integrations/image/imageurl.html
- tests/plugins/tableselection/integrations/image/imageurl.js
- tests/plugins/tableselection/manual/integrations/image/nestedimage.html
- tests/plugins/tableselection/manual/integrations/image/nestedimage.md
Bug
As this was a specific issue and required opening context menu by right-click (keyboard shortcuts were working fine before fix) there is just a short 15 seconds manual test included.
I made `Table Selection` treat images from `Image` plugin the same way it operates on widgets, etc from `Enhanced Image` plugin (i.e. an early return in function checking …
> Fix for: Image in table cell has an empty URL field when edited from context menu opened by right-click

- CHANGES.md
- core/editable.js
- tests/core/editable/enterdiv.js
- tests/core/editable/manual/enterdiv.html
- tests/core/editable/manual/enterdiv.md
Bug fix
When a `div` is to be inserted in another empty `div` I've forced triggering logic which is normally trigerred when element is not allowed in selection.
Closes #2751
> Fix for: Editor with enterMode set to ENTER_DIV alters content on paste

- tests/plugins/tableselection/integrations/image/imageurl.js
Other
I've removed unnecessary version tag from `tests/plugins/tableselection/integrations/image/imageurl` test.
> Remove unnecessary version tag from imageurl test

- tests/plugins/mathjax/mathjax-mock.js
- tests/plugins/widget/_helpers/tools.js
Task
none
`config.ignoreStyle` passed to `widgetTools.addTests` can now be function type. Also updated uses in `mathjax-mock` test.
Closes #3173
> Allow passing config.ignoreStyle to widgetTools.addTests as function type

- CHANGES.md
- core/style.js
- tests/plugins/tableselection/integrations/basicstyles/basicstyles.html
- tests/plugins/tableselection/integrations/basicstyles/basicstyles.js
- tests/plugins/tableselection/manual/integrations/basicstyles/native.html
- tests/plugins/tableselection/manual/integrations/basicstyles/native.md
Bug fix
I removed the code responsible for selecting detached DOM elements. The issue has been introduced with https://github.com/ckeditor/ckeditor-dev/commit/d4907f5634 commit as a part of https://dev.ckeditor.com/ticket/16755 feature.
I couldn't spot any issues after code removal nor manual or unit tests referencing the issue from comment. Not sure why …
> Fix for incorrect selection when styling table using native selection

- CHANGES.md
- core/tools.js
- tests/core/tools/array.js
New feature
This PR introduces `CKEDITOR.tools.array.some` method. Alongside this change I slightly enhanced existing API docs and tests.
Closes #3154.
> Add CKEDITOR.tools.array.some method

- tests/core/dom/range/getclientrects.js
None
Edge 18 returns same rects as other browsers, so I've updated expected value.
Closes #3183
> Fix for failing test in tests/core/dom/range/getclientrects

- tests/plugins/easyimage/uploadintegrations.html
- tests/plugins/easyimage/uploadintegrations.js
None
Failing TC compares html, it's purpose is to make sure progress bar is not downcasted. In Edge 18 it happens before image natural width can be reached hence the `width` attribute remains unset. I've removed `width`, as it's irrelevant to this TC.
Closes #2057
> Fix for: Failing tests in /tests/plugins/easyimage/uploadintegrations

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/editing.js
Bug fix
```
* [#3261](https://github.com/ckeditor/ckeditor-dev/issues/3261): Fixed: [Widget](https://ckeditor.com/cke4/addon/widget) initialized using dialog has incorrect owner document.
```
Passing the same document for detached wrapper element as for editor instance.
Closes #3261
> Pass the same document for detached widget wrapper element as for editor instance

- tests/plugins/filetools/fileloader.js
- tests/plugins/uploadwidget/additionalrequestparameters.js
Fix failing tests
None
Tests are failing due to upstream issue, so I ignored one of them, and forced polyfill which is used in IE for another test.
Closes #3184
> Fix for: failing filetools related tests 

- CHANGES.md
- plugins/undo/plugin.js
- plugins/widget/plugin.js
- tests/plugins/undo/filter.js
- tests/plugins/widget/manual/undo.html
- tests/plugins/widget/manual/undo.md
- tests/plugins/widget/undo.js
Bug fix + new feature
```
Bug Fixes:
* [3198](https://github.com/ckeditor/ckeditor-dev/issues/3198) Fixed: Blurring and focusing editor creates undo step.
API Changes:
* [3245](https://github.com/ckeditor/ckeditor-dev/issues/3245) Added [`UndoManager.filter`]() class which is responsible for filtering Undo snapshot contents.
```
- New class …
> Fix for: Additional undo step created when editor is blurred while widget focused

- CHANGES.md
- core/dom/element.js
- core/tools.js
- plugins/listblock/plugin.js
- plugins/menu/plugin.js
- plugins/panel/plugin.js
- plugins/richcombo/plugin.js
- tests/_benderjs/ckeditor/static/bot.js
- tests/_benderjs/ckeditor/static/tools.js
- tests/core/dom/element/element.js
- tests/core/tools.js
- tests/plugins/button/button.js
- tests/plugins/listblock/listblock.js
- tests/plugins/listblock/manual/rightclick.html
- tests/plugins/listblock/manual/rightclick.md
- tests/plugins/menu/manual/rightclick.html
- tests/plugins/menu/manual/rightclick.md
- tests/plugins/menu/menu.js
- tests/plugins/panel/manual/keydown.html
- tests/plugins/panel/manual/keydown.md
- tests/plugins/panel/panel.js
- tests/plugins/richcombo/manual/rightclick.html
- tests/plugins/richcombo/manual/rightclick.md
- tests/plugins/richcombo/richcombo.js
Bug fix
```
Fixed Issues:
* [IE, Edge] Fixed: Various editor's UI elements react to right mouse button click:
* [#2845](https://github.com/ckeditor/ckeditor-dev/issues/2845): [Rich Combo](https://ckeditor.com/cke4/addon/richcombo).
* [#2857](https://github.com/ckeditor/ckeditor-dev/issues/2857): [List Block](https://ckeditor.com/cke4/addon/listblock).
* …
```
> Fix for activating various UI items via right click

- CHANGES.md
- core/tools.js
- tests/core/tools.js
New feature
I just restored this PR from https://github.com/ckeditor/ckeditor-dev/pull/2862 with some changes during a review. Kudos to @msamsel for most of the feature.
* Extend bind method to accepts more arguments passed to bound functions.
* Feature extracted from PR related to #1479.
```
* [#3247](https://github.com/ckeditor/ckeditor-dev/issues/3247): …
```
> Improve tools.bind function with bound arguments

- CHANGES.md
- core/dom/node.js
- core/dom/range.js
- core/dom/text.js
- tests/core/dom/range/bookmarks.js
- tests/core/dom/range/manual/followingfcs.html
- tests/core/dom/range/manual/followingfcs.md
- tests/core/dom/text.js
Bug fix
```
Fixed Issues:
* [#3158](https://github.com/ckeditor/ckeditor-dev/issues/3158): [Chrome] Fixed: [Undo](https://ckeditor.com/cke4/addon/undo) plugin breaks with soft enter characters.
API Changes:
* [#3326](https://github.com/ckeditor/ckeditor-dev/issues/3326): Added [`text.isEmpty()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_t …
```
> Treat chromium filling char sequence text node as empty

- core/dom/event.js
Typo fix
I don't think tests are needed for a documentation change.
Fixed: Typo in [`CKEDITOR.dom.event.getKey()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_event.html#method-getKey) API documentation
Change "is" -> "if" in the documentation for `event.getKey()`
> Typo for for `event.getKey()` docs

- CHANGES.md
- core/editable.js
- tests/core/editable/domfix3.js
- tests/core/editable/manual/edgefirstfocus.html
- tests/core/editable/manual/edgefirstfocus.md
Bug fix
It's just a dirty hack for Edge. I've added check in `domFix` to allow reselection in Edge only if the editor was previously focused. To check it I use `editor._.previousActive`.
The real source of the issue is buried deep in our selection. It seems that call to `selection.removeAllRanges` somehow prevents Edge from changing selection. The …
> Edge loses selection position when focused the first time

- CHANGES.md
- plugins/bbcode/plugin.js
- tests/plugins/bbcode/bbcode.js
- tests/plugins/bbcode/manual/strikethrough.html
- tests/plugins/bbcode/manual/strikethrough.md
New feature
```
* [#3315](https://github.com/ckeditor/ckeditor-dev/issues/3315): Added support for strikethrough in [BBCode](https://ckeditor.com/cke4/addon/bbcode) plugin. Thanks to [Alexander Kahl](https://github.com/akahl-owl)!
```
This is a copy of https://github.com/ckeditor/ckeditor-dev/pull/217 PR rebased onto latest `major`. There is another PR …
> Support strikethrough in BBCode plugin

- CHANGES.md
- core/dom/range.js
- tests/core/dom/range/gettableelement.js
- tests/core/dom/range/manual/gettableelement.html
- tests/core/dom/range/manual/gettableelement.md
- tests/core/dom/range/misc.js
Bugfix
redundant
```
* [#3101](https://github.com/ckeditor/ckeditor-dev/issues/3101): Fixed: [`range._getTableElement()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_range.html#method-_getTableElement) return `null` instead of a table element for edge cases. 
```
Replace `range.startContainer` and `range.endContainer` with …
> Fix for: range._getTableElement which sometimes not return a table element

- CHANGES.md
- core/editable.js
- tests/core/editable/enterdiv.js
- tests/core/editable/manual/insertgetdata.html
- tests/core/editable/manual/insertgetdata.md
Bug fix
```
* [#3379](https://github.com/ckeditor/ckeditor-dev/issues/3379): Fixed: Incorrect [`CKEDITOR.editor#getData`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-getData) call when inserting content into the editor.
```
I've reversed the conditional introduced by #2776 and forced `getData` to be called as an internal …
> Fix for incorrect getData when content is inserted into the editor

- CHANGES.md
- core/selection.js
- tests/core/selection/manual/tableselection.html
- tests/core/selection/manual/tableselection.md
- tests/core/selection/tableselection.html
- tests/core/selection/tableselection.js
Bug fix
```
* [#3136](https://github.com/ckeditor/ckeditor-dev/issues/3136) [Firefox] Fixed: Clicking on [Balloon Toolbar](https://ckeditor.com/cke4/addon/balloontoolbar) items removes selection.
```
When clicking on button command execution causes `editor.focus()`, however the click itself blurs editor. In case of inline editors we restore last selection …
> Fix for: Table selection moved into the topmost element when clicking balloon button

- CHANGES.md
- core/tools.js
- tests/core/tools/object.js
Bug fix
```
* [#3381](https://github.com/ckeditor/ckeditor-dev/issues/3381): [IE8] Fixed: [`CKEDITOR.tools.object.keys`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools_object.html#method-keys) does not accept non-objects.
```
I've added support for non-objects, including strings in IE8.
Closes #3381.
> Add support for non-object in CKEDITOR.tools.object.keys in IE8

- CHANGES.md
- core/dom/element.js
- plugins/dialog/plugin.js
- plugins/dialog/styles/dialog.css
- plugins/floatpanel/plugin.js
- skins/kama/dialog.css
- skins/moono-lisa/dialog.css
- skins/moono/dialog.css
- tests/core/dom/element/element.js
- tests/plugins/dialog/manual/inputfocus.html
- tests/plugins/dialog/manual/inputfocus.md
- tests/plugins/dialog/manual/inputfocusmobile.html
- tests/plugins/dialog/manual/inputfocusmobile.md
- tests/plugins/dialog/manual/skins/kama.md
- tests/plugins/dialog/manual/skins/moono.md
- tests/plugins/dialog/manual/skins/moonolisa.md
- tests/plugins/dialog/positioning.js
Bug fix
This is early PR with proposal of solution.
When soft keyboard appears on touch devices it causes 'resize' event on which we were recalculating center position of fixed dialog. After that browser tried to scroll into view of input but it took wrong position, probably before moving it.
Such complex way of centering dialog is unnecessary, as dialog …
> Fix for: focused input in dialog is scrolled out of viewport when soft keyboard appears

- CHANGES.md
- plugins/link/dialogs/link.js
- plugins/link/plugin.js
- tests/plugins/link/link.js
- tests/plugins/link/manual/protocol.html
- tests/plugins/link/manual/protocol.md
New feature
```
[#2227](https://github.com/ckeditor/ckeditor-dev/issues/2227): Added [`config.link_defaultProcotol`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-link_defaultProtocol) configuration option that allows setting default URL protocol for [Link](https://ckeditor.com/cke4/addon/link) plugin dialog.
```
Closes #2227
> Add link protocol field customization

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/dnd.js
- tests/plugins/widget/manual/clipboardhtml.html
- tests/plugins/widget/manual/clipboardhtml.md
- tests/plugins/widget/manual/clipboardhtmlselectall.html
- tests/plugins/widget/manual/clipboardhtmlselectall.md
- tests/plugins/widget/widgetsintegration.js
Feature request
```
* [#3138](https://github.com/ckeditor/ckeditor-dev/issues/3138): Use [`widgetDefinition.getClipboardHtml()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_widget.html#method-getClipboardHtml) method to customize [Widget](https://ckeditor.com/cke4/addon/widget) HTML during copy, cut and drag operations.
```
Added new …
> Enable widget clipboard manipulation

- plugins/image/dialogs/image.js
- tests/plugins/forms/imagebutton.js
- tests/plugins/forms/manual/editingmode.md
Bug fix/new feature
No changelog entry, as it's fix for yet unreleased feature.
That was a little tricky one. We missed it during development, because `imagebutton` is available only when `image` plugin is used and it uses `image`'s dialog. I've updated `image`'s `getModel()` to fetch also `input[type=image]`.
Closes #3436.
> Add support for new dialog model API for image buttons

- plugins/iframe/dialogs/iframe.js
- tests/plugins/iframe/iframe.js
- tests/plugins/iframe/manual/editingmode.html
- tests/plugins/iframe/manual/editingmode.md
Bug fix/new feature
None, as it's part of unreleased feature.
I've added missing support for model API to `iframe` dialog (basically copied it from `flash` one).
Closes #3442.
> Add support for getModel to iframe dialog

- plugins/link/dialogs/anchor.js
- tests/plugins/link/anchor.js
- tests/plugins/link/manual/anchorselection.html
- tests/plugins/link/manual/anchorselection.md
Bug fix
```
* [#3437](https://github.com/ckeditor/ckeditor4/issues/3437): [Safari] Fixed: Can't get selected anchor when selection is in anchor's text.
```
I've added additional mechanism to fetch tex't parent element if selection is inside the text.
Closes #3437.
> Fix for incorrect getSelectedAnchor result

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/manual/customtypes.md
- tests/plugins/clipboard/manual/customtypesasync.md
- tests/plugins/clipboard/paste.js
Bug fix
```
*[#3354](https://github.com/ckeditor/ckeditor4/issues/3354) Fix: Broken paste in iOS 13.
```
Mark current iOS Safari version as supported for custom copy/cut and mark it as trusted browsers. This flags generally change the way how we treat pasted and copied data:
https://github.com/ckeditor/ckeditor4/blob/98cae96bbe874496a63cdedd0dd9a8f869e3a0b …
> Fix broken paste in iOS 13

- core/selection/optimization.js
- tests/core/selection/manual/optimization.html
- tests/core/selection/manual/optimization.md
- tests/core/selection/optimization.js
Bug fix
None, since it is a bugfix for a new feature.
It turns out that after `setData()` call or switching to `source mode` or using `new page` button, new editable is created (AFAIU for Iframe editor only), and thus listeners attached to editable on `editor#instanceReady` event are no longer valid. Attaching listener to editable should be done on …
> Fix for: editor.setData breaks shift+arrow selection behavior

- tests/core/tools/amd.js
Failing test
None needed
I've forced waiting for the iframe being loaded via appropriate events. Additional 500ms after load is needed for older IEs to actually fetch the polyfill.
Closes #3425.
> Fix unstable test for AMD

- CHANGES.md
- plugins/menu/plugin.js
- tests/plugins/menu/manual/quotes.html
- tests/plugins/menu/manual/quotes.md
- tests/plugins/menu/menu.js
Bug fix
```
*[#3413](https://github.com/ckeditor/ckeditor4/issues/3413): Fixed: Menu items with labels containing double quotes are rendered incorrectly.
```
I've enabled encoding of HTML attributes via `CKEDITOR.tools.htmlEncodeAttr` for labels that are used inside attributes.
Closes #3413.
> Fix for menu items with double quotes

- CHANGES.md
- core/selection.js
- tests/core/selection/editor.js
- tests/core/selection/manual/plaintextpasteinfirefox.html
- tests/core/selection/manual/plaintextpasteinfirefox.md
- tests/core/selection/manual/tableselection.md
Bug fix
```
* [#3475](https://github.com/ckeditor/ckeditor4/issues/3475) [Firefox] Fix: broken paste of plain text.
```
* Correct comparison expression to use correct data types.
Closes: #3475
> Fix broken paste of plain text in firefox

- CHANGES.md
- plugins/link/dialogs/link.js
- tests/plugins/link/emailprotectionencode.html
- tests/plugins/link/emailprotectionfunctionalcall.html
- tests/plugins/link/emailwithatsign.html
- tests/plugins/link/emailwithatsign.js
- tests/plugins/link/manual/emailwithatsign.html
- tests/plugins/link/manual/emailwithatsign.md
Bug fix
`[(#2027)](https://github.com/ckeditor/ckeditor-dev/issues/2027): Fix for: Incorrect handling email display text starting with '@'.`
Link plugin was changing email display text to be the same as email address every time it found '@' in display text. This condition was removed.
Closes #2027.
> Fix for: Invalid display name for links with mailto href

- tests/plugins/clipboard/drop.js
Failing test
None needed.
Seems like Firefox on Windows changed handling of new line character and produces `\n\r` instead of `\r`. I've updated expected output for Firefox on Windows.
Closes #3517.
> Fix unstable drop test

- CHANGES.md
- plugins/specialchar/dialogs/specialchar.js
- tests/plugins/specialchar/dialog.js
- tests/plugins/specialchar/manual/presentationrole.html
- tests/plugins/specialchar/manual/presentationrole.md
Bug fix
```
* [#3544(https://github.com/ckeditor/ckeditor4/issues/3544) Fix: Empty table cells at the end of the dialog of [Special Characters](https://ckeditor.com/cke4/addon/specialchar) plugin was read by assistive technologies.
```
* Remove adding empty table cells in special char dialog.
* Hoist variables to the top to prevent jshint errors.
Closes: …
> Remove empty table cells from the dialog of specialchar plugin

- CHANGES.md
- plugins/balloontoolbar/plugin.js
- tests/plugins/balloontoolbar/manual/divareascroll.html
- tests/plugins/balloontoolbar/manual/divareascroll.md
- tests/plugins/balloontoolbar/positioning.js
- tests/plugins/balloontoolbar/view.js
Bug fix
```
* [#1653](https://github.com/ckeditor/ckeditor4/issues/1653) Fix: Missing reposition of [balloon toolbar](https://ckeditor.com/cke4/addon/balloontoolbar) when the editable was scrolled in the [divarea](https://ckeditor.com/cke4/addon/divarea) editor.
```
Improve listener which now detects elements with scrollbar holding the editable and attach …
> Fix missing reposition of balloon toolbar after scrolling the editable

- CHANGES.md
- core/htmlparser/filter.js
- tests/core/htmlparser/filter.js
Bug fix
```
* [#3593](https://github.com/ckeditor/ckeditor4/issues/3593): Fixed: Can't access to text or comment node when is replaced with [`CKEDITOR.htmlParser.filter`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_htmlParser_filter.html)
```
Add missing 3rd argument to filter method, when an element is replaced with a text or a comment.
Fix …
> Add full support for replacing element node with text or comment node in htmlparser

- tests/plugins/widget/manual/outline.html
fix
I've ignored widget manual test on IE8. This test fails due to problem with widget inside inline editor on IE8.
Closes #1641
> Failing test ignore on IE8: /tests/plugins/widget/manual/outline

- tests/core/editable/misc.js
Bug fix
None
If FF 70 or later is detected, test will trim the result before comparing with expected to get rid of trailing `\n`.
Closes #3633.
> Fix failing tests /tests/core/editable/misc

- tests/plugins/pastefromword/generated/functions.js
- tests/plugins/pastefromword/generated/heuristics.js
- tests/plugins/pastefromword/helpers.js
- tests/plugins/pastefromword/pasteimage.js
- tests/plugins/pastetools/_helpers/ptTools.js
- tests/plugins/pastetools/filter/functions.js
- tests/plugins/pastetools/filter/parsestyles.js
Failing test
None needed.
I've moved loading filters as a part of `async:init` to force loading them after creating editor for tests.
Closes #3424.
> Improve stability of Paste Tools tests with filters

- CHANGES.md
- plugins/emoji/plugin.js
- plugins/emoji/skins/default.css
- tests/plugins/emoji/basic.js
- tests/plugins/emoji/dropdown.js
- tests/plugins/emoji/manual/emojimatchlabel.html
- tests/plugins/emoji/manual/emojimatchlabel.md
- tests/plugins/emoji/manual/font.html
- tests/plugins/emoji/manual/font.md
New feature/task
Changed emoji suggestion box item template to show `item.name` instead of `item.id`.
```
* [#2583](https://github.com/ckeditor/ckeditor-dev/issues/2583): Changed [Emoji](https://ckeditor.com/cke4/addon/emoji) suggestion box to show matched emoji name instead of an ID.
```
Closes #2583
> Show matched emoji name instead of an ID in emoji suggestion box

- CHANGES.md
- plugins/dialog/plugin.js
- tests/_benderjs/ckeditor/static/bot.js
- tests/plugins/dialog/_helpers/tools.js
- tests/plugins/dialog/focus.js
- tests/plugins/dialog/manual/focus.html
- tests/plugins/dialog/manual/focus.md
Bug fix
```
* [#3474](https://github.com/ckeditor/ckeditor4/issues/3474): Fixed: Incorrect focus order after tab in dialog navigation was clicked.
* [#3689](https://github.com/ckeditor/ckeditor4/issues/3689): Fixed: Cannot change dialog tabs focus with keyboard arrows after focusing with any tab with mouse click.
```
After clicking into the tab in …
> Set correct focus on tab in dialog when is clicked

- plugins/widget/plugin.js
- tests/plugins/widget/manual/selectallsourcemode.html
- tests/plugins/widget/manual/selectallsourcemode.md
- tests/plugins/widget/widgetselection.js
Bug fix
```
*[#3704](https://github.com/ckeditor/ckeditor4/issues/3704): Fixed: Error is thrown while typing inside source area.
```
I've bound checking selection to `key` only if `contentDom` event appeared earlier.
Closes #3704.
> Fix for error while typing in source mode

- CHANGES.md
- core/selection.js
- tests/plugins/widget/_helpers/tools.js
- tests/plugins/widget/integration/selection/inputselection.js
- tests/plugins/widget/integration/selection/manual/ieinputwidget.html
- tests/plugins/widget/integration/selection/manual/ieinputwidget.md
- tests/plugins/widget/integration/selection/manual/ietextareawidget.html
- tests/plugins/widget/integration/selection/manual/ietextareawidget.md
Bugfix
```
* [#3587](https://github.com/ckeditor/ckeditor4/issues/3587): [Edge, IE] Fix: textarea and input elements inside widget are not possible to focus with a mousedown.
```
Prevent to run logic responsible for the entire widget selection on IE and Edge, when the target element is a textarea or an input inside a widget.
Closes #3587.
> Fix focus inside widget for textarea and input elements

- CHANGES.md
- plugins/richcombo/plugin.js
- tests/plugins/richcombo/manual/select.html
- tests/plugins/richcombo/manual/select.md
- tests/plugins/richcombo/richcombo.js
New feature
```
[#3387](https://github.com/ckeditor/ckeditor-dev/issues/3387): Added the [CKEDITOR.ui.richCombo#select](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_ui_richCombo.html#method-select) method.
```
Add new method in richcombo to select proper value based on a callback function. 
Closes: #3387
> Add "select" method to rich combo

- CHANGES.md
- plugins/colorbutton/plugin.js
- plugins/panelbutton/plugin.js
- tests/plugins/colorbutton/colorcommand.js
- tests/plugins/colorbutton/colorcommandnoui.js
- tests/plugins/colorbutton/manual/colorcommand.html
- tests/plugins/colorbutton/manual/colorcommand.md
- tests/plugins/colorbutton/manual/colorcommandwithwidget.html
- tests/plugins/colorbutton/manual/colorcommandwithwidget.md
- tests/plugins/panelbutton/command.js
New feature
```
* [#3306](https://github.com/ckeditor/ckeditor-dev/issues/3306): Added new commands `textColor` and `bgColro` which applies the selected color from color panel.
```
* extract logic which applies color to a command.
Closes #3727
Closes #3748
> Implement textColor and bgColor commands

- CHANGES.md
- core/selection/optimization.js
- tests/core/selection/manual/tripleclick.md
- tests/core/selection/optimization.js
Bug fix
```
*[#3705](https://github.com/ckeditor/ckeditor4/issues/3705): Fix for: Safari incorrectly removes blocks after selecting all.
```
The actual reason for this issue was selection optimization introduced in #3213 (with breaking commit [06b94a6](https://github.com/ckeditor/ckeditor4/commit/06b94a64713e34ae8cb41196f2ce00618468a76a)). When it is …
> Fix for: Safari incorrectly removes blocks after selecting all

- tests/plugins/emoji/dropdown.js
Test case fix for CI
**No entry**
Added transparent div with higher z-index than emoji panel, which prevents mouse interaction with the panel.
It seems that cursor on CI is located in the middle of the screen and since Chrome v79 it has started to interact with the emoji panel.
Closes #3744.
> Fix emoji dropdown tests

- tests/plugins/pastefromword/pasteimage.js
- tests/plugins/pastetools/_helpers/ptTools.js
- tests/plugins/pastetools/filter/common.js
- tests/plugins/pastetools/filter/image.js
don't need
Remove script load function and create helper based on promise.
The probably source of the issue was situation that filters could be loaded before the plugin. So reference to filter was overwritten. The change now loads when editor is ready, whats guarantee that all plugins are loaded already.
Closes #3800, closes #3798
> Fix failing test for paste tools filters

- CHANGES.md
- plugins/dialog/plugin.js
- tests/plugins/dialog/_helpers/tools.js
- tests/plugins/dialog/focus.js
- tests/plugins/dialog/manual/ariaselected.html
- tests/plugins/dialog/manual/ariaselected.md
New feature
```
*[#3547](https://github.com/ckeditor/ckeditor4/issues/3547): Active [dialog](https://ckeditor.com/cke4/addon/dialog) tab has now `aria-selected="true"` attribute.
```
Add and remove `aria-selected` attribute along with a `cke_dialog_tab_selected` class.
Closes #3547.
> Add `aria-selected` attribute for active dialog tab

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/dnd.js
- tests/plugins/widget/manual/clipboardhtmldnd.html
- tests/plugins/widget/manual/clipboardhtmldnd.md
New feature
```
*[#3441](https://github.com/ckeditor/ckeditor4/issues/3441) Added support for dragging and dropping multiple [widgets](https://ckeditor.com/cke4/addon/widget).
```
I've added additional `drop` handler, which fires only if there are more than one widget in the selection or there is something else alongside the widget (e.g. text). …
> Add support for d&d multiple widgets

- tests/plugins/pastefromlibreoffice/generated/generic.js
- tests/plugins/pastefromlibreoffice/generated/genericwithword.js
Task
None is needed
I've enabled PfLO unit tests in IE11 with necessary custom filters and ignoring fixtures.
Closes #3835.
> Enable PfLO unit tests in IE11

- plugins/colorbutton/plugin.js
- tests/plugins/colorbutton/manual/select.html
- tests/plugins/colorbutton/manual/select.md
- tests/plugins/colorbutton/select.js
New feature
Not required as it's an internal change.
Introduced new color button selection method. Due to fact that it's unlikely this method will be used by …
> Expose colorbutton#select method

- plugins/pastetools/plugin.js
Other, please explain
add docs entry
Closes #3802
> Add missing docs description

- tests/plugins/easyimage/pasteintegration.js
Not needed
I've forced clearing the editable before every test. It seems that IE has issues with selecting incorrectly inserted image.
Closes #3869.
> Fix for failing test tests/plugins/easyimage/pasteintegration

- CHANGES.md
- plugins/emoji/plugin.js
- plugins/emoji/skins/default.css
- tests/plugins/emoji/dropdown.js
- tests/plugins/emoji/manual/cors.html
- tests/plugins/emoji/manual/cors.md
Bug fix
```
* [#2607](https://github.com/ckeditor/ckeditor4/issues/2607): Fixed: Emoji SVG icons are not loaded due to CORS .
```
Instead of external SVG …
> Fix CORS issue for Emoji SVG icons

- core/editor.js
To fix inconsistent API Docs about `setData()` method. 
It was caused by maintaining backward compatibility, as mentioned above: https://github.com/ckeditor/ckeditor4/blob/52ec0b185b005611368b3eccd59275ba4294526a/core/editor.js#L1106-L1108 Still, as using `internal` parameter is valid, I added reference to it.
Closes #3417.
> Add reference about the old parameter 'internal' parameter in 'setData()' method

- CHANGES.md
- core/creators/inline.js
- tests/core/creators/inline.html
- tests/core/creators/inline.js
- tests/core/creators/manual/inlinereadonly.html
- tests/core/creators/manual/inlinereadonly.md
Bug fix
```
*[#3866](https://github.com/ckeditor/ckeditor4/issues/3866): Fixed: [`config.readOnly`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html …
```
> Fix for config not considered for startup read-only mode of inline editor

- CHANGES.md
- core/selection.js
- tests/core/selection/manual/unlockerror.html
- tests/core/selection/manual/unlockerror.md
- tests/core/selection/selection.js
Bug fix
```
*[#3931 ](https://github.com/ckeditor/ckeditor4/issues/3931): [IE] Fixed: Error is thrown when pasting using paste button and Clipboard Access …
```
> Fix for: Selection throws error when pasting with Clipboard Access Prompt

- CHANGES.md
- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/navigation.md
Bug fix
```
*[#3938](https://github.com/ckeditor/ckeditor4/issues/3938): Fixed: Autocomplete loses navigation keybindings after switching source mode.
``` …
> Fix issue with loosing keybindings for autocomplete panel with sourcemode

- plugins/emoji/plugin.js
Bug fix
```
*[#3951](https://github.com/ckeditor/ckeditor4/issues/3951): Added private scope for loadSVGNavigationIcons method (emoji plugin).
```
Added …
> Added private scope for loadSVGNavigationIcons method (emoji plugin)

- CHANGES.md
- plugins/tableresize/plugin.js
- tests/plugins/tableresize/manual/iebordercollapse.html
- tests/plugins/tableresize/manual/iebordercollapse.md
Bug fix
```
*[#2823](https://github.com/ckeditor/ckeditor4/issues/2823): [IE] Fixed: Can't resize the last table column using [Table …
```
> Fix for resizing last table column in IE

- samples/toolbarconfigurator/index.html
Bug fix.
```
*[#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few simple …
```
> Fix JS error in Toolbar Configurator

- plugins/dialog/dialogDefinition.js
- plugins/filetools/plugin.js
Docs
Not needed.
I created one PR to fix two API docs issues since these changes are really small. As for outdated `unicode.org` links see …
> API docs fixes

- CHANGES.md
- plugins/removeformat/plugin.js
- tests/plugins/removeformat/manual/collapsed.html
- tests/plugins/removeformat/manual/collapsed.md
- tests/plugins/removeformat/manual/selection.md
- tests/plugins/removeformat/plugin.js
Bug fix
```
*[#4008](https://github.com/ckeditor/ckeditor4/issues/4008): Fixed: [Remove format](https://ckeditor.com/cke4/addon/removeformat) doesn't work with …
```
> Remove format button should work with collapsed selection

- CHANGES.md
- plugins/tableresize/plugin.js
- tests/plugins/tableresize/manual/maximizeddivarea.html
- tests/plugins/tableresize/manual/maximizeddivarea.md
- tests/plugins/tableresize/manual/maximizedinlinedivarea.html
- tests/plugins/tableresize/manual/maximizedinlinedivarea.md
Bug fix - Tableresize not working in maximized mode when using divarea
Tableresize not working in maximized mode when using divarea
z-index of resizer in maximized mode too low.
Set z-index of resizer to 10000
Closes #1959.
Closes #909.
> Bugfix - Tableresize not working in maximized mode with divarea

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/keystroke.js
- tests/plugins/widget/manual/keystroke.html
- tests/plugins/widget/manual/keystroke.md
Bug fix.
```
*[#3998](https://github.com/ckeditor/ckeditor4/issues/3998): Fix widget plugin when using keystrokes to get to source code.
```
Added some checks …
> Fix widget plugin when keystorke is pressed

- tests/plugins/emoji/manual/cors.html
The test has been incorrectly ignored as the editor is loaded inside iframe via an external source.
> Ignore unsupported browsers for emoji manual test

- CHANGES.md
- plugins/htmlwriter/plugin.js
- tests/plugins/htmlwriter/htmlwriter.js
- tests/plugins/htmlwriter/manual/dataindentationchars.html
- tests/plugins/htmlwriter/manual/dataindentationchars.md
Fixes this bug: https://github.com/ckeditor/ckeditor4/issues/3795
Yes, but I haven't been able to run the test, since running `bender server run` returns `Potentially unhandled rejection [1] ReferenceError: primordials is not defined`.
```
*[#3795](https://github.com/ckeditor/ckeditor4/issues/3795): Fixed a bug where setting the dataIndentationChars …
```
> Fixed dataIndentationChars empty string bug

- CHANGES.md
- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/sourcemode.html
- tests/plugins/autocomplete/manual/sourcemode.md
Bug fix
```
*[#4107](https://github.com/ckeditor/ckeditor4/issues/4107): Multiple autocomplete instances cause keyboard navigation issues.
```
Again our event …
> Fix autocomplete navigation with multiple instances

- CHANGES.md
- core/editor.js
- tests/core/editor/custom_config_race.js
- tests/core/editor/manual/customconfigrace.html
- tests/core/editor/manual/customconfigrace.md
Bug fix
```
* [#3361](https://github.com/ckeditor/ckeditor4/issues/3361): Fixed: Loading multiple [custom editor …
```
> Fix customConfig race condition

- CHANGES.md
- plugins/richcombo/plugin.js
- tests/plugins/richcombo/manual/ariaexpanded.html
- tests/plugins/richcombo/manual/ariaexpanded.md
- tests/plugins/richcombo/richcombo.js
Bug fix
```
* [#4007](https://github.com/ckeditor/ckeditor4/issues/4007): Fixed: Screen readers don't announce [`Rich Combo` …
```
> Add aria-expanded attribute for rich combo buttons

- CHANGES.md
- plugins/colorbutton/plugin.js
Docs fix
```
* [#3693](https://github.com/ckeditor/ckeditor4/issues/3693): Fixed: incorrect default values for several [Color …
```
> Fix incorrect defaults for colorbutton config variables

- CHANGES.md
- plugins/easyimage/plugin.js
- tests/plugins/easyimage/manual/safarizerodimensions.html
- tests/plugins/easyimage/manual/safarizerodimensions.md
Bug fix
```
* [#4183](https://github.com/ckeditor/ckeditor4/issues/4183): [Safari] Fixed: Incorrect images dimensions when using [Easy …
```
> Fix incorrect images dimensions in Safari

- tests/_benderjs/ckeditor/static/extensions.js
Task
Skip.
Introduced `bender.loadExternalPlugins` helper which should be used by external plugins in tests so test can be both run from external repo and main …
> Add `bender.loadExternalPlugin` helper

- tests/core/command/command.js
Test fix
Skip.
The cmd is enabled in readonly mode thus should be ingored in this test as it fails now
None.
> Ignore exportPdf cmd in readonly commands test

- CHANGES.md
- plugins/dialog/plugin.js
- tests/plugins/dialog/plugin.js
Task
Changelog entry should be placed under `Other Changes`.
```
* [#4262](https://github.com/ckeditor/ckeditor4/issues/4262): Removed global reference to …
```
> Keep stylesLoaded out of global context (taken over)

- CHANGES.md
- core/tools.js
- plugins/tableresize/plugin.js
- tests/core/tools/array.js
- tests/plugins/tableresize/manual/rowspan.html
- tests/plugins/tableresize/manual/rowspan.md
```
* [#3961](https://github.com/ckeditor/ckeditor4/issues/3961): Table resize prevents editing merged cells.
```
Rowspans are not taken into consideration …
> Fix resize table with rowspan cells

- CHANGES.md
- core/style.js
- plugins/format/plugin.js
- plugins/stylescombo/plugin.js
- tests/plugins/stylescombo/manual/removeblockformat.html
- tests/plugins/stylescombo/manual/removeblockformat.md
- tests/plugins/stylescombo/stylescombo.js
Bug fix
```
* [#3649](https://github.com/ckeditor/ckeditor4/issues/3649): Fixed: Applying a [block format](https://ckeditor.com/docs/ckeditor4/latest/features/f …
```
> Remove block styles when changing format if a new block format doesn't contain them

- CHANGES.md
- core/creators/inline.js
- tests/core/creators/inlineallonalreadyinlined.html
- tests/core/creators/inlineallonalreadyinlined.js
- tests/core/creators/manual/inlineallonalreadyinlined.html
- tests/core/creators/manual/inlineallonalreadyinlined.md
Bug fix
```
* [#4293](https://github.com/ckeditor/ckeditor4/issues/4293): Fixed: [`CKEDITOR.inlineAll`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR. …
```
> Fix CKEDITOR.inlineAll inlining also elements with editor already attached to them

- .github/workflows/stalebot.yml
Let's check if it will work correctly without `:` character. I see that closing labels has been normally added so it's probably safe to leave them for now.
Please, when merging this PR, also rename `status:stale` label to `stale`.
> Change stale label for stalebot

- tests/plugins/tableselection/integrations/tabletools/tabletools.js
- tests/plugins/tableselection/manual/safaritheadlastcolumn.html
- tests/plugins/tableselection/manual/safaritheadlastcolumn.md
- tests/plugins/tableselection/manual/safaritheadlastcolumnmouse.html
- tests/plugins/tableselection/manual/safaritheadlastcolumnmouse.md
Task
Not needed
I've ignored the unit test that fails in Safari and added a manual one to check if the upstream issue is still present.
Closes #4287.
Closes …
> Tests for table selection in Safari

- CHANGES.md
- core/editable.js
- tests/core/editable/manual/pastearabic.html
- tests/core/editable/manual/pastearabic.md
- tests/core/editable/manual/pastearabicenterbr.html
- tests/core/editable/manual/pastearabicenterbr.md
- tests/core/editable/manual/typeime.html
- tests/core/editable/manual/typeime.md
- tests/core/editable/textnormalization.js
Bug fix.
```
* [#848](https://github.com/ckeditor/ckeditor4/issues/848): Fixes arabic text not being "bound" correctly when pasting.
```
Edit by @f1ames:
> This change uses the native Element.prototype.normalize method to merge sibling TextNodes automatically, if the method is available.
> Should cause Chrome to trigger ligatures/"bounding" correctly.
I have rework the fix to only normalize text node in Chrome since it is Chrome only issue. Since this is a core change, the changes should be precise to not touch browsers where it works fine.
> I'm not entirely clear on how to add a test here, …
> Fix issue #848, arabic text not being "bound" correctly when pasting

- tests/plugins/autogrow/_helpers/tools.js
- tests/plugins/autogrow/autogrow.js
- tests/plugins/autogrow/autogrowborderless.js
Skip
The reason for tests failure on Firefox (btw I also reproduced it on Chrome and Safari) were vertical scrollbars in two places: in the …
> Fix failing tests/plugins/autogrow/autogrow test

- tests/core/creators/manual/inlineallonalreadyinlined.html
- tests/plugins/tableresize/manual/rowspan.html
Bug fix: ignore impracticable tests for mobile
```
Skip
```
Add `assert.ignore()` for manual tests if run on mobile (based on `bender.tools.env.mobile`). …
> Fix: impracticable tests ignore for mobile

- CHANGES.md
- plugins/editorplaceholder/plugin.js
- tests/plugins/editorplaceholder/editorplaceholder.js
Bug fix
```
* [#4253](https://github.com/ckeditor/ckeditor4/issues/4253): Prevent index-reading from undefined variable.
```
Check `RegExp` match results …
> Fix: Editor Placeholder plugin throws an error during editor initialization when used with bbcode and fullpage

- core/dom/range.js
Bug fix
```
* [#4300 ](https://github.com/ckeditor/ckeditor4/issues/4300):Fix Images in docs does not displaying correctly (due to Easy Image)
```
*Give an …
> Fix Images in docs does not displaying correctly (due to Easy Image)

- CHANGES.md
- core/_bootstrap.js
- tests/core/ckeditor/manual/_assets/hctest.html
- tests/core/ckeditor/manual/hcdetection.html
- tests/core/ckeditor/manual/hcdetection.md
- tests/core/ckeditor/manual/hcdetectionajax.html
- tests/core/ckeditor/manual/hcdetectionajax.md
- tests/core/ckeditor/manual/hcdetectionunsupported.html
- tests/core/ckeditor/manual/hcdetectionunsupported.md
Bug fix
- [] Unit tests
```
* [#4379](https://github.com/ckeditor/ckeditor4/issues/4379): [Edge] Fixed: incorrect detection of the high contrast mode.
```
I've …
> Fix incorrect high contrast mode detection

- CHANGES.md
- plugins/ajax/plugin.js
- tests/plugins/ajax/ajax.js
New feature - according to #4394 
```
* [#4394 ](https://github.com/ckeditor/ckeditor4/issues/4394): Added ajax predefined loading methods for: binary - …
```
> Explicit Ajax helpers for new response types

- tests/plugins/autoembed/autoembed.js
- tests/plugins/autoembed/autoembednotifications.js
- tests/plugins/autoembed/getwidgetdefinition.js
Ignoring tests
skip
Ignored tests failing on IEs because of the native browser implementation is now the only one working. Manual tests are still passing. …
> Ignore failing autoembed tests on IEs

- tests/plugins/ajax/ajax.js
Fix failing test for IE
```
Skip
```
There were two tests for loading XML asynchronously.
The oldest one has IE ignore.
The newest one was …
> Remove duplicated test, add IE ignore

- CHANGES.md
- core/editable.js
- tests/core/editable/enterdiv.js
- tests/core/editable/manual/enterdivemptypaste.html
- tests/core/editable/manual/enterdivemptypaste.md
Bug fix
```
* [#4301](https://github.com/ckeditor/ckeditor4/issues/4301): Fixed: pasted content overwritten when pasted in initially empty editor with [`div` …
```
> Fix overwriting text on paste

- CHANGES.md
- plugins/richcombo/plugin.js
- tests/plugins/richcombo/manual/arialabel.html
- tests/plugins/richcombo/manual/arialabel.md
- tests/plugins/richcombo/richcombo.js
Bug fix
```
* [#4493](https://github.com/ckeditor/ckeditor4/issues/4493): Fixed: [Rich Combo](https://ckeditor.com/cke4/addon/richcombo) label does not …
```
> Enhance accessiblity of richcombo label

- tests/plugins/balloontoolbar/positioning.js
Bug fix
Skip
The tests seem to fail because of the roundings. `getClientRect()` method rounds left balloon position of
`48.6953125` to `48.6875` (it's `11/16`) …
> Fix failing "out of view" tests in `/tests/plugins/balloontoolbar/positioning`

- CHANGES.md
- core/tools/color.js
- tests/core/tools/color.js
New feature
```
* [#4583](https://github.com/ckeditor/ckeditor4/issues/4583): Added support for new, comma-less color syntax to …
```
> Add support for new syntaxes in `CKEDITOR.tools.color`

- tests/plugins/widget/manual/deleteparagraph.md
- tests/plugins/widget/manual/deleteparagraphbetween.md
Typo fix
```
none
```
In https://github.com/ckeditor/ckeditor4/pull/4433 I've merged to `master` manual tests with the wrong bender tags: `4.16.0` (should be …
> Fix tags for tests

- CHANGES.md
- core/htmldataprocessor.js
- plugins/widget/plugin.js
- tests/plugins/widget/dnd.js
- tests/plugins/widget/manual/parentdnd.html
- tests/plugins/widget/manual/parentdnd.md
- tests/plugins/widget/nestededitables.js
Bug fix
```
* [#4509](https://github.com/ckeditor/ckeditor4/issues/4509): Fixed: incorrect handling of drag & drop inside widgets and nested editables.
``` …
> Fix for incorrect drag & drop handling for widgets and nested editables

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/datatransfer.js
- tests/plugins/clipboard/manual/isfiletransfer.html
- tests/plugins/clipboard/manual/isfiletransfer.md
New feature
```
Fixed Issues:
*[#4604](https://github.com/ckeditor/ckeditor4/issues/4604): Fixed: [`CKEDITOR.plugins.clipboard.dataTransfer#getTypes()`](https:/ …
```
> Enhance getting types from dataTransfer

- CHANGES.md
- core/tools/color.js
- tests/core/tools/color.js
Bug fix
```
* [#4597](https://github.com/ckeditor/ckeditor4/issues/4597): Fixed: incorrect color conversion for HSL/HSLA values.
```
Due to the issue mentioned …
> Fix incorrect HSL/HSLA conversion

- core/tools/color.js
API docs fixes
nope
1) `CKEDITOR.tools.color.TYPE_RGB` and `CKEDITOR.tools.color.TYPE_HSL` should've been link using `#` instead of `.`, which was causing the …
> Fix API docs issues in `CKEDITOR.tools.color`

- plugins/widget/plugin.js
Bug fix
none
With https://github.com/ckeditor/ckeditor4/pull/4539, in `ENTER_BR` mode we were inserting nested `<br>` elements after widget. It happened on all …
> Fix inserting `<br>` element after widget in `ENTER_BR` mode

- dev/docs/codestyle.md
Add code-style note about indentation in manual tests.
```
* SKIP
```
As I talk F2F with @f1ames, I made a PR without any issue creation. Our code style didn't …
> Add code-style note about indentation in manual tests

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/manual/pasteimage.md
Bug fix
```
* [#3757](https://github.com/ckeditor/ckeditor4/issues/3757): [Firefox] Fixed: pasted images are not inserted as Base64-encoded images.
```
It …
> Fix for regression with pasting images in Firefox

- CHANGES.md
- plugins/autocomplete/plugin.js
- tests/plugins/autocomplete/a11y.js
- tests/plugins/autocomplete/autocomplete.js
- tests/plugins/autocomplete/manual/a11ydivarea.html
- tests/plugins/autocomplete/manual/a11ydivarea.md
- tests/plugins/autocomplete/model.js
- tests/plugins/autocomplete/view.js
Bug fix
```
* [#4617](https://github.com/ckeditor/ckeditor4/issues/4617): Fixed: [Autocomplete](https://ckeditor.com/cke4/addon/autocomplete) is not accessible …
```
> Enhance accessibility of autocomplete

- CHANGES.md
- plugins/dialog/plugin.js
- tests/plugins/dialog/_helpers/tools.js
- tests/plugins/dialog/manual/hidingcover.html
- tests/plugins/dialog/manual/hidingcover.md
- tests/plugins/dialog/plugin.js
- tests/plugins/dialog/positioning.js
Bug fix
```
* [#3638](https://github.com/ckeditor/ckeditor4/issues/3638): Fixed: opening the same dialog twice causes it to become hidden under the dialog's …
```
> Fix for broken dialogs after opening the same one twice

- CHANGES.md
- plugins/colorbutton/plugin.js
- tests/plugins/colorbutton/colorbutton.js
- tests/plugins/colorbutton/manual/customclasstext.html
- tests/plugins/colorbutton/manual/custompanelrender.html
- tests/plugins/colorbutton/manual/custompanelrender.md
Bug fix 
```
* [#<4247>](https://github.com/ckeditor/ckeditor4/issues/4247): Fixed: [Color Button](https://ckeditor.com/cke4/addon/colorbutton) Incorrect …
```
> Incorrect rendering of the color button on first opening

- tests/plugins/widget/manual/deleteparagraph.html
- tests/plugins/widget/manual/deleteparagraphbetween.html
Failing mobile test.
skip
Tests that cannot be reproduce on mobile devices have been skipped.
* `tests/plugins/widget/manual/deleteparagraphbetween`
* …
> Skip test that cannot be reproduce on mobile devices

- tests/plugins/autocomplete/manual/a11ydivarea.html
Failing mobile test.
skip
Skipped mobile manual test that cannot be reproduced on mobile. 
* `tests/plugins/autocomplete/manual/a11ydivarea`
Closes …
> Skip a11ydivarea manual test on mobile

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/manual/pasteimage.html
- tests/plugins/clipboard/manual/pasteimage.md
- tests/plugins/clipboard/pasteimage.js
New feature
```
* [#4612](https://github.com/ckeditor/ckeditor4/issues/4612): Allow pasting images as Base64 in all browsers
```
Enabling pasting images as …
> Enable paste images as base64 from clipboard.

- .travis.yml
- bender-runner.config.json
Task
```
Skip.
```
This PR switches our Travis job to custom benderjs/browser launcher. The main purpose and motivation was to allow testing on browser …
> Switch CI testing to benderjs runner

- CHANGES.md
- plugins/font/plugin.js
- tests/plugins/font/customfontdefinition.js
- tests/plugins/font/manual/nestingclasses.html
- tests/plugins/font/manual/nestingclasses.md
Bug fix
```
* [#4555](https://github.com/ckeditor/ckeditor4/issues/4555): Fixed: [Font](https://ckeditor.com/cke4/addon/font) styles with attributes are not …
```
> Fix incorrect nesting of font styles

- CHANGES.md
- core/htmldataprocessor.js
- plugins/widget/plugin.js
- tests/plugins/widget/nestedwidgets.js
Bug fix
```
* [#4777](https://github.com/ckeditor/ckeditor4/issues/4777): Fixed: Html comments in widgets not processed correctly
```
The origin of this …
> Fix: Html comments in widgets not processed correctly

- CHANGES.md
- plugins/autocomplete/plugin.js
- tests/plugins/emoji/manual/editablenullerror.html
- tests/plugins/emoji/manual/editablenullerror.md
Bug fix
```
* [#4782](https://github.com/ckeditor/ckeditor4/issues/4782): Fixed: TypeError in autocomplete for FF.
```
I just added some prevention in one `if` …
> Prevent invocation on not existing editable [FF]

- CHANGES.md
- plugins/a11yhelp/dialogs/lang/ar.js
- plugins/a11yhelp/dialogs/lang/bg.js
- plugins/a11yhelp/dialogs/lang/en-gb.js
- plugins/a11yhelp/dialogs/lang/en.js
- plugins/a11yhelp/dialogs/lang/fo.js
- plugins/a11yhelp/dialogs/lang/gu.js
- plugins/a11yhelp/dialogs/lang/hi.js
- plugins/a11yhelp/dialogs/lang/km.js
- plugins/a11yhelp/dialogs/lang/lt.js
- plugins/a11yhelp/dialogs/lang/mk.js
- plugins/a11yhelp/dialogs/lang/mn.js
- plugins/a11yhelp/dialogs/lang/th.js
- plugins/a11yhelp/dialogs/lang/tt.js
- tests/plugins/a11yhelp/manual/focusinfo.html
- tests/plugins/a11yhelp/manual/focusinfo.md
Bug fix
```
* [#4783](https://github.com/ckeditor/ckeditor4/issues/4783): Fixed: [Accessibility Help](https://ckeditor.com/cke4/addon/a11yhelp) dialog does not …
```
> Fix lack of info about moving focus upon activating a toolbar button

- tests/core/editable/keystrokes/delbackspacequirks/manual/nbspdeleting.md
Not needed
I've updated incorrect key info in `tests/core/editable/keystrokes/delbackspacequirks/manual/nbspdeleting`.
Closes #4830.
> Fix for incorrect button name in `tests/core/editable/keystrokes/delbackspacequirks/manual/nbspdeleting`

- tests/plugins/uploadwidget/manual/escapecssuploadimage.html
Not needed
I've used `bender.tools.ignoreUnsupportedEnvironment` to skip the test in browsers that do not support File API.
Closes #4831 .
> Ignore `tests/plugins/uploadwidget/manual/escapecssuploadimage` test in unsupported browsers

- tests/plugins/toolbar/manual/hover/androidrichcombo.md
```
skip
```
I've changed the description of test because now we have a situation that during the long-tapping on rich combo buttons we have a …
> Change the manual test description

- tests/core/filter/editor.js
It's no longer valid since fakeobjects plugin is using ACF
```
skip
```
I removed the failing assertion. This assertion is …
> Fix failing tests/core/filter/editor

- tests/core/editor/detaching.js
Ignore failing test
```
skip
```
Added unstable test (fails 1/3 runs) to ignored for IE11. It also causes failure of the next test case. During tests when I …
> Ignore unstable test on IE11

- tests/core/dom/range/getclientrectsabsolute.js
- tests/plugins/magicline/magicline.js
```
skip
```
I added the `toFixed` method in assertions, which compares the values taken from mobile screens due to cases where there is a …
> Preventing comparisons between thousandths of a decimal place in unit tests

- CHANGES.md
- plugins/dialogui/plugin.js
- skins/kama/dialog.css
- skins/moono-lisa/dialog.css
- skins/moono/dialog.css
- tests/plugins/dialogui/manual/required/__template__.html
- tests/plugins/dialogui/manual/required/required.md
- tests/plugins/dialogui/manual/required/requiredkama.md
- tests/plugins/dialogui/manual/required/requiredmoono.md
- tests/plugins/dialogui/required.js
New feature
```
* [#3433>](https://github.com/ckeditor/ckeditor4/issues/3433): [dialog]: Added asterisks to required fields.
```
I've added asterisks to each …
> Add asterisks to required fields

- CHANGES.md
- core/dom/event.js
- plugins/maximize/plugin.js
- tests/plugins/maximize/manual/historyapi.html
- tests/plugins/maximize/manual/historyapi.md
- tests/plugins/maximize/manual/historyapihash.html
- tests/plugins/maximize/manual/historyapihash.md
- tests/plugins/maximize/manual/historyapioff.html
- tests/plugins/maximize/manual/historyapioff.md
- tests/plugins/maximize/maximize.js
New feature
```
* [#4374](https://github.com/ckeditor/ckeditor4/issues/4374): Integrated [Maximize](https://ckeditor.com/cke4/addon/maximize) plugin with …
```
> Integrate maximize plugin with History API

- tests/plugins/preview/manual/previewcdn.html
```
skip.
```
Due to addition of `MutationObserver` feature on the `major` branch, there was a problem trying to use `CKEDITOR` namespace. It …
> Failing test fix: Set fake observableParent element  

- CHANGES.md
- plugins/dialog/plugin.js
- tests/plugins/dialog/manual/setstatenook.html
- tests/plugins/dialog/manual/setstatenook.md
- tests/plugins/dialog/plugin.js
Bug fix
```
* [#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/4888): Fixed: [ `CKEDITOR.dialog#setState()`](https://ckeditor.com/docs/ckeditor4/l …
```
> Fix for `CKEDITOR.dialog#setState()` throwing error when there is no "Ok" button in the dialog

- CHANGES.md
- plugins/autolink/plugin.js
- tests/plugins/autolink/autolink.js
- tests/plugins/autolink/manual/encoding.html
- tests/plugins/autolink/manual/encoding.md
Bug fix
```
* [#4858](https://github.com/ckeditor/ckeditor4/issues/4858): Fixed: [Autolink](https://ckeditor.com/cke4/addon/autolink) plugin incorrectly …
```
> Fix issue with double escaped autolink special characters

- CHANGES.md
- plugins/templates/dialogs/templates.js
- tests/plugins/templates/manual/checkboxposition.html
- tests/plugins/templates/manual/checkboxposition.md
- tests/plugins/templates/manual/inserttemplate.md
- tests/plugins/templates/manual/inserttemplatereplace.md
New feature
```
* [#4901](https://github.com/ckeditor/ckeditor4/issues/4901): Move replace checkbox to the top to be in the reading direction and improve …
```
> Move replace checkbox to the top to be in the reading direction

- CHANGES.md
- plugins/preview/plugin.js
- tests/plugins/preview/manual/previewtitle.html
- tests/plugins/preview/manual/previewtitle.md
- tests/plugins/preview/preview.js
Other: It is a PR for the [Issue 4026](https://github.com/ckeditor/ckeditor4/issues/4026)
No, it does not.
1. I am not sure if this change requires a test.
2. bender exits with a failure. I tried to follow the steps described in the corresponding documentation (Setting up tests, run tests, etc.). Too time consuming for this simple test.
- None, as explained above
- [X ] PR is consistent with the code style guide
```
* [#4026](https://github.com/ckeditor/ckeditor4/issues/4026): Preview addon should use editor's "title" property for the title of the new window
```
Changed `title = …
> Use editor's title for new preview window

- tests/plugins/pagebreak/pagebreak.js
Bug fix
```
skip.
```
This issue is related to #4885. It's failing only in Safari >14.x in place with getting proper offset values.
Closes #4690.
> Ignore manual test

- core/editable.js
- tests/core/editable/manual/enterbr.html
- tests/core/editable/manual/enterbr.md
Bug fix
```
* [#3858](https://github.com/ckeditor/ckeditor4/issues/3858): Fixed pasting content in ENTER_BR mode.
```
The problem was with the …
> Prevent br normalization in ENTER_BR mode

- tests/plugins/preview/manual/previewcdn.html
Bug fix.
```
skip
```
When trying to load the editor from CDN on the built package there was a problem with loading `scayt` and `exportpdf` plugins. These …
> Remove unnecessary plugins from `previewcdn` test

- plugins/dialogui/plugin.js
- skins/kama/dialog.css
- skins/moono-lisa/dialog.css
- skins/moono/dialog.css
- tests/plugins/dialogui/manual/required/required.md
- tests/plugins/dialogui/manual/required/requiredkama.md
- tests/plugins/dialogui/manual/required/requiredmoono.md
- tests/plugins/dialogui/required.js
Bug fix
skip
I've slightly enhanced required fields indicator:
* they're now a little bit bigger (120%),
* instead of read they're bold,
* they're ignored by a …
> Required field indicator a11y improvements

- CHANGES.md
- plugins/tableselection/plugin.js
- tests/plugins/tableselection/manual/draganddropimage.html
- tests/plugins/tableselection/manual/draganddropimage.md
- tests/plugins/tableselection/manual/draganddropmixedcontent.html
- tests/plugins/tableselection/manual/draganddropmixedcontent.md
- tests/plugins/tableselection/manual/draganddroptext.html
- tests/plugins/tableselection/manual/draganddroptext.md
Bug fix
```
* [#547](https://github.com/ckeditor/ckeditor4/issues/547): Fixed: Element/Image drag to move within the table is no longer available.
```
D&D in …
> Allow basic d&d element/image in tables when tableselection is on

- CHANGES.md
- samples/toolbarconfigurator/js/fulltoolbareditor.js
Some 3rd party plugin like Zoom does not define any toolbar option when they add a toolbar button or richcombo and the toolbar configurator crash with error:
> Uncaught TypeError: currBtn.toolbar is undefined
>     groupButtons file:///C:/ckeditor/samples/toolbarconfigurator/js/fulltoolbareditor.js:215
>     init file:///C:/ckeditor/samples/toolbarconfigurator/js/fulltoolbareditor.js:54
in the …
> Fix toolbar configurator undefined error

- tests/core/ckeditor/manual/assetscachekeycdn.html
- tests/core/ckeditor/manual/assetscachekeycdn.md
Task
skip
I've added a manual test for cache keys and CDN. It uses the same technique proposed by @KarolDawidziuk in `/tests/plugins/preview/manual/previewcdn` …
> Add manual test for cache keys in CDN

- CHANGES.md
- plugins/find/dialogs/find.js
- tests/plugins/find/find.js
- tests/plugins/find/manual/findandreplacedoublespacepattern.html
- tests/plugins/find/manual/findandreplacedoublespacepattern.md
Bug fix
```
* [#4987](https://github.com/ckeditor/ckeditor4/issues/4987): Fixed: [Find/Replace](https://ckeditor.com/cke4/addon/find) Find and replace a word …
```
> Fix find and replace words with double space

- CHANGES.md
- plugins/imagebase/plugin.js
- tests/plugins/easyimage/manual/wordintegration.html
- tests/plugins/easyimage/manual/wordintegration.md
- tests/plugins/easyimage/uploadintegrations.js
- tests/plugins/imagebase/features/_helpers/tools.js
- tests/plugins/imagebase/features/upload.js
Bug fix
```
* [#4994](https://github.com/ckeditor/ckeditor4/issues/4994): Fixed: content from Word is pasted as image when [Easy …
```
> Fix for integration between Word and Easy Image

- tests/plugins/find/find.js
Fix failing tests
```
skip
```
The `entities` plugin treats some of the Unicode as HTML Entities in the output instead of `' '` (blank space). So I added an …
> Fix `find&replace` failing tests

- plugins/find/dialogs/find.js
- tests/plugins/find/find.js
- tests/plugins/find/manual/replacedoublespace.html
- tests/plugins/find/manual/replacedoublespace.md
Bug fix
```
* [#5061](https://github.com/ckeditor/ckeditor4/issues/5061): Fixed: [Find / Replace](https://ckeditor.com/cke4/addon/find) plugin incorrectly …
```
> Fix for incorrect replacing with phrases with several spaces inside

- tests/core/ckeditor/manual/assetscachekey.html
Failing test
```
skip
```
The test steps from `tests/core/ckeditor/manual/assetscachekey` were not possible to reproduce in IE8 due to the lack of the …
> Ignore test on unsupported browser

- CHANGES.md
- skins/kama/reset.css
- skins/moono-lisa/reset.css
- skins/moono/reset.css
- tests/core/skin/manual/_assets/multiselectfix.css
- tests/core/skin/manual/kamamultiselect.html
- tests/core/skin/manual/kamamultiselect.md
- tests/core/skin/manual/moonolisamultiselect.html
- tests/core/skin/manual/moonolisamultiselect.md
- tests/core/skin/manual/moonomultiselect.html
- tests/core/skin/manual/moonomultiselect.md
Bug fix for issue #5044 
This patch contains a simple addition of CSS rules, to bring styling back to multiple select controls for when they lose focus. The browser styling is reset by the skins, so new styling needs to be reinstated for such specific cases.
- 
```
* [#5044](https://github.com/ckeditor/ckeditor4/issues/5044):
* add rule for selected options of multiple selects, to skins/kama/reset.css
* add rule for selected options of multiple selects, to skins/moono-lisa/reset.css
* add rule for selected options of multiple selects, to skins/moono/reset.css
```
Added rule in the stylesheets …
> Add style for unfocused multiselection list

- plugins/find/dialogs/find.js
Docs task
Probably we can skip it
I've removed `characterRange` class used inside Find dialog from `CKEDITOR.plugins.find` namespace. In fact, this class was …
> Remove `characterRange` class from `CKEDITOR.plugins.find` namespace

- CHANGES.md
- plugins/basicstyles/plugin.js
- plugins/bidi/plugin.js
- plugins/blockquote/plugin.js
- plugins/button/plugin.js
- plugins/copyformatting/plugin.js
- plugins/justify/plugin.js
- plugins/list/plugin.js
- plugins/maximize/plugin.js
- plugins/sourcearea/plugin.js
- tests/plugins/basicstyles/aria.js
- tests/plugins/bidi/aria.js
- tests/plugins/blockquote/aria.js
- tests/plugins/button/_helpers/buttontools.js
- tests/plugins/button/aria.js
- tests/plugins/button/manual/togglebutton.html
- tests/plugins/button/manual/togglebutton.md
- tests/plugins/button/manual/togglebuttons.html
- tests/plugins/button/manual/togglebuttons.md
- tests/plugins/button/manual/togglebuttonscreenreader.html
- tests/plugins/button/manual/togglebuttonscreenreader.md
- tests/plugins/copyformatting/aria.js
- tests/plugins/justify/aria.js
- tests/plugins/list/aria.js
- tests/plugins/maximize/aria.js
- tests/plugins/maximize/manual/togglebutton.html
- tests/plugins/maximize/manual/togglebutton.md
- tests/plugins/menubutton/manual/menubuttonscreenreader.html
- tests/plugins/menubutton/manual/menubuttonscreenreader.md
- tests/plugins/sourcearea/aria.js
New feature
```
New features:
* [#2444](https://github.com/ckeditor/ckeditor4/issues/2444): Togglable toolbar buttons are now exposed as toggle buttons in the …
```
> Expose toggle buttons in accessibility tree

- CHANGES.md
- core/dom/range.js
- tests/core/ckeditor/manual/strictmode.html
- tests/core/ckeditor/manual/strictmode.md
Bug fix
```
* [#5049](https://github.com/ckeditor/ckeditor4/issues/5049): Fix editor fails in strict mode.
```
Removed `this` from IIFE in …
> Fix editor failing in strict mode

- CHANGES.md
- core/creators/inline.js
- core/creators/themedui.js
- core/editor.js
- tests/core/creators/_helpers/tools.js
- tests/core/creators/detachedinline.js
- tests/core/creators/detachedreplace.js
- tests/core/creators/manual/detachedcancelinterval.html
- tests/core/creators/manual/detachedcancelinterval.md
New feature
```
* [#4641](https://github.com/ckeditor/ckeditor4/issues/4641): Add cancelation for delayed editor creation.
```
A new config …
> Add functionality to cancel awaiting for delayed editor creation

- CHANGES.md
- core/htmlparser/fragment.js
- tests/core/htmlparser/fragment/fromhtml.js
- tests/core/htmlparser/manual/preserveinlinestyling.html
- tests/core/htmlparser/manual/preserveinlinestyling.md
- tests/core/htmlparser/manual/shiftlinebreak.html
- tests/core/htmlparser/manual/shiftlinebreak.md
New feature
```
* [#4986](https://github.com/ckeditor/ckeditor4/issues/4986): Added [`config.shiftLineBreaks`](https://ckeditor.com/docs/ckeditor4/latest/api/CK …
```
> Allow preserving line breaks at the end of inline elements

- plugins/wysiwygarea/plugin.js
- tests/core/creators/aria.js
Bug fix
N/A
Instead of using `&nbsp;` entity I've used a raw character for setting `iframe`'s `title` when there is no editor label.
Closes #5189.
> Use raw non-breaking space for an empty `iframe`'s `title`

- plugins/wysiwygarea/plugin.js
- tests/plugins/wysiwygarea/fullpage.js
Bug fix
N/A
I've updated the regex for stripping ARIA attributes to accommodate IE8's oddities – as it uses uppercase for elements' names and sometimes it …
> Fix incorrect stripping of ARIA attributes in full-page mode in IE8

- tests/plugins/tab/manual/focusafteraddednewrownative.html
N/A
I've forced the removal of the `tableselection` plugin so the test would use the native selection inside the table.
Closes #5198.
> Remove `tableselection` plugin from `tests/plugins/tab/manual/focusafteraddednewrownative`

- tests/plugins/button/manual/togglebuttons.html
Fix manual test.
```
skip.
```
IE older than version 10 has a problem with inserting generated content into `tbody` element. To fix this, I created the entire …
> Fix manual test: `plugins/button/manual/togglebuttons`

- tests/plugins/pastefromword/generated/tickets1.js
- tests/plugins/pastefromword/generated/tickets2.js
```
skip
```
Added `CKEDITOR.env.safari` to be ignored in two tests suites:
- tests/plugins/pastefromword/generated/tickets1
- …
> Fix failing test: Ignores test on safari

- tests/plugins/pastefromword/generated/tickets1.js
- tests/plugins/pastefromword/generated/tickets2.js
I mislook the original issue. We didn't intend to disable these tests on Safari but accommodate iPad for testing purposes.
Reverts ckeditor/ckeditor4#5235
> Revert "Fix failing test: Ignores test on safari"

- CHANGES.md
- plugins/dialogui/plugin.js
- tests/plugins/dialogui/api.js
Bug fix
```
* [#5135](https://github.com/ckeditor/ckeditor4/issues/5135): dialogui - make .setValue() chainable for checkboxes and radio buttons
```
That's a …
> dialogui - make .setValue() chainable for checkboxes and radio buttons - follow up

- CHANGES.md
- plugins/tableselection/plugin.js
- tests/plugins/tabletools/manual/mergecells.html
- tests/plugins/tabletools/manual/mergecells.md
- tests/plugins/tabletools/tabletools.html
- tests/plugins/tabletools/tabletools.js
Bug fix
```
* [#4284](https://github.com/ckeditor/ckeditor4/issues/4284): Fixed: [Tableselection](https://ckeditor.com/cke4/addon/tableselection) Merging cells …
```
> Fix merging cells with rowspan

- CHANGES.md
- core/tools.js
- tests/core/tools.js
```
* [#5158](https://github.com/ckeditor/ckeditor4/issues/5158): Fixed: [tools.convertToPx()](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools.htm …
```
> Fix #5158 - assure that calculator element is always attached to DOM

- CHANGES.md
- plugins/elementspath/plugin.js
- plugins/toolbar/plugin.js
- tests/_benderjs/ckeditor/static/tools.js
- tests/plugins/elementspath/elementspath.js
- tests/plugins/elementspath/manual/focus.html
- tests/plugins/elementspath/manual/focus.md
- tests/plugins/toolbar/basic.js
- tests/plugins/toolbar/manual/focus.html
- tests/plugins/toolbar/manual/focus.md
Bug fix
```
* [#438](https://github.com/ckeditor/ckeditor4/issues/438): Fixed: There was impossible to navigate to the …
```
> Add keystroke handlings for `elementspath` and `toolbar` plugins

- CHANGES.md
- plugins/dialog/plugin.js
- tests/plugins/dialog/functions.js
- tests/plugins/dialog/validatorinlinestyle.js
- tests/plugins/dialog/validators.js
Bug fix
```
[#4473](https://github.com/ckeditor/ckeditor4/issues/4473): Fix: [dialog.validate methods](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_d …
```
> Fix: dialog validators  accept value only from inner getValue method

- CHANGES.md
- plugins/find/dialogs/find.js
- tests/plugins/find/find.js
- tests/plugins/find/manual/findbykeyboard.html
- tests/plugins/find/manual/findbykeyboard.md
- tests/plugins/find/manual/replacebykeyboard.html
- tests/plugins/find/manual/replacebykeyboard.md
Bug fix
```
* [#5022](https://github.com/ckeditor/ckeditor4/issues/5022): Fixed: [Find/Replace](https://ckeditor.com/cke4/addon/find) Find and replace does not …
```
> Add enter key support for `Find&Replace`

- CHANGES.md
- plugins/toolbar/plugin.js
- tests/plugins/toolbar/config.js
- tests/plugins/toolbar/manual/removebuttons.html
- tests/plugins/toolbar/manual/removebuttons.md
New feature
```
* [#5122](https://github.com/ckeditor/ckeditor4/issues/5122): Added ability to provide a list of buttons as an array to the …
```
> Add support for array in the `config.removeButtons`

- CHANGES.md
- plugins/entities/plugin.js
- tests/plugins/entities/entities.js
- tests/plugins/entities/manual/encodeentities.html
- tests/plugins/entities/manual/encodeentities.md
- tests/plugins/entities/manual/entitiesprocessnumericalforce.html
- tests/plugins/entities/manual/entitiesprocessnumericalforce.md
Bug fix
```
* [#4941](https://github.com/ckeditor/ckeditor4/issues/4941): Fix: Some entities get wrongly encoded, when using `entities_processNumerical = true` …
```
> Fix encoding entities

- CHANGES.md
- plugins/autolink/plugin.js
- tests/plugins/autolink/autolink.js
Previously there was no possibility to override url regexp completely and it worked improperly.
```
* …
```
> Bug fix: Autolink url regexp config fix

- CHANGES.md
- plugins/tableresize/plugin.js
- tests/plugins/tableresize/manual/scrollupdate.html
- tests/plugins/tableresize/manual/scrollupdate.md
- tests/plugins/tableresize/tableresize.html
- tests/plugins/tableresize/tableresize.js
Bug fix
```
* [#4889](https://github.com/ckeditor/ckeditor4/issues/4889): Fixed: incorrect position of the [Table …
```
> Fix for incorrect table resize cursor position after scrolling the editor

- CHANGES.md
- plugins/basicstyles/plugin.js
- tests/plugins/basicstyles/basicstyles.js
- tests/plugins/basicstyles/manual/toggleexistingsubsupscript.html
- tests/plugins/basicstyles/manual/toggleexistingsubsupscript.md
- tests/plugins/basicstyles/manual/togglesubsupscript.html
It's a follow-up to https://github.com/ckeditor/ckeditor4/pull/5312
Changes:
* Renamed config option to `coreStyles_toggleSubSup`.
* Fixed a bug that removed sup and superscript elements when pasting content containing these elements via sourcemode and then attempting to disable one of them in toolbar.
Screencast with bug:
https://user-images.githubusercontent.com/18471998/190137470-66757ee2-3ec0-4e3e-9605-88e3425fcf45.mov
* Added unit test to cover fix for the above issue.
* Updated changelog.
> Improvement for allowing subscript and superscript at the same time

- CHANGES.md
- core/selection/optimization.js
- plugins/selectall/plugin.js
- tests/core/selection/manual/optimizationlist.html
- tests/core/selection/manual/optimizationlist.md
- tests/core/selection/optimization.js
Bug fix
```
* [#4931](https://github.com/ckeditor/ckeditor4/issues/4931): Fix: selection optimization skips list elements and disallow list removal.
```
*Give …
> Fix: selection optimization in list disallow full list removal

- CHANGES.md
- plugins/tabletools/dialogs/tableCell.js
- plugins/tabletools/plugin.js
- tests/plugins/tabletools/_helpers/cellproperties.js
- tests/plugins/tabletools/cellproperties.html
- tests/plugins/tabletools/cellproperties.js
- tests/plugins/tabletools/manual/allowedcontent.html
- tests/plugins/tabletools/manual/cellproperties.html
- tests/plugins/tabletools/manual/cellpropertiescelltype.html
- tests/plugins/tabletools/manual/cellpropertiescelltype.md
- tests/plugins/tabletools/manual/scopedheaders.html
- tests/plugins/tabletools/manual/scopedheaders.md
New feature
```
* [#5084](https://github.com/ckeditor/ckeditor4/issues/5084): Added the [`config.tabletools_scopedHeaders`](https://ckeditor.com/docs/ckeditor4/ …
```
> Introduce `CKEDITOR.config.tabletools_scopedHeaders`

- tests/plugins/entities/entities.js
```
skip.
```
It looks like `&apos` -> `'`is unsupported on IE8 so I just removed it from the test case.
Closes #5330
> Fix failing test `tests/plugins/entities/entities`

- CHANGES.md
- plugins/table/dialogs/table.js
- tests/plugins/table/headers1row1col.js
- tests/plugins/table/headers1row2col.js
- tests/plugins/table/headers2row1col.js
- tests/plugins/table/headers2row2col.js
- tests/plugins/table/manual/changescopeattribute.html
- tests/plugins/table/manual/changescopeattribute.md
- tests/plugins/table/manual/scopeattribute.html
- tests/plugins/table/manual/scopeattribute.md
Bug fix
```
* [#2996](https://github.com/ckeditor/ckeditor4/issues/2996): Fix: Table header "scope" attribute is incorrect for 'header: both' option.
* …
```
> Fix adding and change scope `both` attribute in tables

- CHANGES.md
- plugins/tableselection/plugin.js
- tests/plugins/tableselection/manual/tabbackspace.html
- tests/plugins/tableselection/manual/tabbackspace.md
Bug fix
```
* [#4802](https://github.com/ckeditor/ckeditor4/issues/4802): Fixed: Caret moves to the previous cell after tabbing into the next cell and then …
```
> Fix for caret moving to the previous cell after tabbing into the next cell and then removing its content

- CHANGES.md
- plugins/uploadimage/plugin.js
- tests/plugins/uploadimage/manual/clipboardintegration.html
- tests/plugins/uploadimage/manual/clipboardintegration.md
- tests/plugins/uploadimage/uploadimage.js
Bug fix
```
* [#5333](https://github.com/ckeditor/ckeditor4/issues/5333): Fixed: original name of the uploaded image was not preserved in the [Upload …
```
> Fix broken integration between `uploadimage` and `clipboard`

- CHANGES.md
- plugins/colorbutton/plugin.js
- tests/plugins/colorbutton/manual/_assets/customstyle.css
- tests/plugins/colorbutton/manual/customstyle.css
- tests/plugins/colorbutton/manual/customstyle.html
- tests/plugins/colorbutton/manual/customstyle.md
Add possibility to add custom styles for colorbutton layout.
```
* [#5352](https://github.com/ckeditor/ckeditor4/issues/5352): Allows using custom styles from …
```
> Allow using custom styles from config.colorButton_css for Colorbutton plugin

- CHANGES.md
- plugins/widget/plugin.js
- tests/plugins/widget/manual/startupdata.html
- tests/plugins/widget/manual/startupdata.md
- tests/plugins/widget/widgetapi.js
New feature
```
* [#3540](https://github.com/ckeditor/ckeditor4/issues/3540): The startup data passed to the widget's command is now used to also populate …
```
> Populate widget template with startup data

- CHANGES.md
- plugins/embedsemantic/plugin.js
- plugins/widget/plugin.js
- tests/plugins/widget/inlineeditables.js
- tests/plugins/widget/manual/inlineeditable.html
- tests/plugins/widget/manual/inlineeditable.md
No, it's a minor change. Let me know if this is necessary.
```
* [#698](https://github.com/ckeditor/ckeditor4/issues/698): Fix "Cannot read property 'attributes' of null".
```
Checked that `element` and `widgetElement` are non-null before accessing `attributes`.
Closes #698.
> Fix "Cannot read property 'attributes' of null"

- CHANGES.md
- plugins/tab/plugin.js
- tests/plugins/tab/manual/tabpreserveundostep.html
- tests/plugins/tab/manual/tabpreserveundostep.md
- tests/plugins/tab/tab.js
Bug fix
```
* [#4829](https://github.com/ckeditor/ckeditor4/issues/4829): Fix: Undo reverse entire table content instead of single cell.
```
In the `tab` …
> Fix undo in single cell when using tab key

- CHANGES.md
- plugins/maximize/plugin.js
- tests/plugins/maximize/maximize.js
Bug fix
```
* [#5396](https://github.com/ckeditor/ckeditor4/issues/5396): Fix: window listeners for `popstate` and `hashchange` was not removed when destroying …
```
> Remove the historyAPI listeners in the `maximize` plugin when destroying the editor instance

- CHANGES.md
- plugins/easyimage/plugin.js
- plugins/uploadimage/plugin.js
- plugins/uploadwidget/plugin.js
- tests/plugins/easyimage/manual/changeevent.html
- tests/plugins/easyimage/manual/changeevent.md
- tests/plugins/easyimage/uploadintegrations.js
- tests/plugins/uploadfile/manual/changeevent.html
- tests/plugins/uploadfile/manual/changeevent.md
- tests/plugins/uploadfile/uploadfile.js
- tests/plugins/uploadimage/manual/changeevent.html
- tests/plugins/uploadimage/manual/changeevent.md
- tests/plugins/uploadimage/uploadimage.js
- tests/plugins/uploadwidget/uploadwidget.js
Bug fix
```
* [#5414](https://github.com/ckeditor/ckeditor4/issues/5414): Fixed: File and image uploaders based on the [Upload Widget …
```
> Fire the `change` event after uploading is done

- tests/plugins/easyimage/uploadintegrations.js
skip
I've added check if the `change` event is fired after the upload is finished (after the `widget#uploadDone` event). Thanks to that, …
> Fix for failing `change` event test in Easy Image plugin

- CHANGES.md
- plugins/uploadimage/plugin.js
- tests/plugins/uploadimage/manual/customsupportedtypes.html
- tests/plugins/uploadimage/manual/customsupportedtypes.md
- tests/plugins/uploadimage/uploadimage.js
New feature
Added a new configuration parameter, `uploadImage_supportedTypes`, dedicated to the image upload plugin that allows to specify additional supported image types, such as 'image/webp' format.
```
* [#4400](https://github.com/ckeditor/ckeditor4/issues/4400): new configuration parameter `uploadImage_supportedTypes` dedicated to upload image plugin.
```
Closes #4400.
> Making the upload image plugin supporting 'image/webp' format.

- tests/_benderjs/ckeditor/static/bot.js
- tests/core/dom/range/getclientrectswidget.js
- tests/plugins/easyimage/uploadintegrations.js
- tests/plugins/widget/definition.js
- tests/plugins/widget/editing.js
Failing tests fix
N/A
I've forced selection in `bot#setData()` method when it's called with an empty string and the editor is `iframe`-based one. Additionally, …
> Fix failing tests in Chrome

- CHANGES.md
- plugins/clipboard/plugin.js
- tests/plugins/clipboard/dropimage.js
- tests/plugins/clipboard/manual/dropnotificationdisablehandleimages.html
- tests/plugins/clipboard/manual/dropnotificationdisablehandleimages.md
- tests/plugins/clipboard/manual/pastenotificationdisablehandleimages.html
- tests/plugins/clipboard/manual/pastenotificationdisablehandleimages.md
- tests/plugins/clipboard/notifications.js
- tests/plugins/clipboard/pasteimage.js
- tests/plugins/uploadimage/manual/customsupportedtypes.md
Bug fix
```
* [#5431](https://github.com/ckeditor/ckeditor4/issues/5431): Fix: No notification is shown for unsupported image types.
```
.
Closes #5431.
> Fix showing notification about unsupported files when `clipboard_handleImages` is OFF

- CHANGES.md
- plugins/preview/plugin.js
- tests/plugins/preview/manual/previewcdn.md
- tests/plugins/preview/manual/previewpreservelinks.html
- tests/plugins/preview/manual/previewpreservelinks.md
Task
```
* [#5412](https://github.com/ckeditor/ckeditor4/issues/5412): Prevent using `document.domain` by Firefox in the `preview` plugin.
```
In the previous …
> Prevent using `document.domain` by Firefox in the `preview` plugin

- CHANGES.md
- plugins/listblock/plugin.js
- plugins/richcombo/plugin.js
- plugins/stylescombo/plugin.js
- tests/plugins/stylescombo/langattribute.js
- tests/plugins/stylescombo/manual/langattribute.html
- tests/plugins/stylescombo/manual/langattribute.md
New feature
```
* [#5410](https://github.com/ckeditor/ckeditor4/issues/5410): Added the ability to indicate the language of styles via [config.styleSet config …
```
> Add ability to indicate the language of styles

- CHANGES.md
- plugins/listblock/plugin.js
- tests/plugins/listblock/listblock.js
- tests/plugins/listblock/manual/ariaselected.html
- tests/plugins/listblock/manual/ariaselected.md
Bug fix
```
* [#5437](https://github.com/ckeditor/ckeditor4/issues/5437): Fix: incorrect indication of selected items in comboboxes.
```
I've discovered that …
> Fix incorrect selection handling in the Rich Combos

- CHANGES.md
- skins/kama/notification.css
- skins/moono-lisa/notification.css
- skins/moono/notification.css
- tests/plugins/notification/manual/linkcontrastkama.html
- tests/plugins/notification/manual/linkcontrastkama.md
- tests/plugins/notification/manual/linkcontrastmoono.html
- tests/plugins/notification/manual/linkcontrastmoono.md
- tests/plugins/notification/manual/linkcontrastmoonolisa.html
- tests/plugins/notification/manual/linkcontrastmoonolisa.md
Bug fix
```
* [#5495](https://github.com/ckeditor/ckeditor4/issues/5495): Fixed: insufficient color ratio for links inside …
```
> Fix insufficient contrast ratio for links in notifications

- tests/plugins/listblock/listblock.js
N/A
I've replaced a click event for the item in the combo with a direct call to `combo.onClick()`.
Closes #5498.
> Fix for failing `listblock` test in IE 11

- tests/plugins/pastefromword/generated/keep_margins_in_lists.js
- tests/plugins/pastefromword/generated/keep_zero_margins_in_lists.js
- tests/plugins/pastefromword/generated/list_margins.js
Failing tests fix
```
Skip.
```
On the built version of the editor, the tests added additional attributes to the resulting HTML, which in this case should not …
> Fix failing tests
